### ISSUE TITLE
Perk Idea: Achievement

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#100]
**Describe the solution you'd like**
A perk that can be configured to create and grant an `achievement`.

**Why is this feature needed**
Saw someone asking for it in `?questions`, figured it would be a candidate for a perk.

**Comment by Caltinor** [comment]
Achievements have to be created in data.  given that we don't want to be reloading data on behalf of the server ops, I think this is captured via the command perk?

**Comment by SomewhatDamaged** [comment]
`/achievement` only awards existing ones. I take it creating new ones is not possible at this point in the data load?

**Comment by Caltinor** [comment]
Perks run during the game, so we'll after data is loaded.  If the suggestion is to have the perk create the advancement as the server is loading, then that's certainly doable, but wooo is that a doozy of work.

**Comment by SomewhatDamaged** [comment]
I doubt this is urgent in any way, shape, or form. Either back-burner it or just drop it. `/achievement` can be easily used to award achievements.

**Comment by Caltinor** [comment]
I think making advancements via perks is going to be too complex for users to configure or just be too limited. Since we use datapacks for configs anyways, they can create their advancements there and invoke them with the command perk.
