### ISSUE TITLE
[1.19.2] Slowness & Mining Fatigue requirement penalty debuff does not go away

### ISSUE THREAD

**Issue by RedBeast1959** [Caltinor/Project-MMO-2.0#106]
**Describe the bug**
Biome or Equipment requirement penalty that gives negative effect like slowness 2 and mining fatigue 2... it seems that function is broken. Even I leave certain biome(ex: Jungle) or throw away high end equipment(ex: netherite sword), slowness and mining fatigue don't go away. Unlike negative effects, positive effects of certain biome do go away though.

**To Reproduce**
0. Start a game
1. Enter Biome like jungle or pick up things that's not enough skill for you to hold(diamond/netherite tools)
2. Check negative debuff and leave biome or throw away tools immediately
3. Watch never-ending duration of negative debuff

**Screenshots**
![2022-10-15_17 11 32](https://user-images.githubusercontent.com/100399264/195976599-876f6024-3e5a-42c7-b4ec-6425f429021b.png)

**Versions:**
 - Minecraft: 1.19.2
 - Loader: Forge 43.1.43
 - PMMO: pmmo-1.19-0.5.0.jar

**Comment by Caltinor** [comment]
I have a few questions:
1. Does this happen in survival or just creative, like your screenshot?
2. Are you actually still debuffed or are the visual indicators just not going away?

**Comment by RedBeast1959** [comment]
1. Both creative and survival
2. I tried to dig something but it became very slow. So, yeah, it actually debuffed.

By the way, here's update.
Suprisingly, after delete the map file and try new game, that debuff sustaining problem is gone.
I never changed modpack but it happened. Probably I have to try out few more times.

**Comment by Caltinor** [comment]
Thank you for the quick update.  I did have this behavior before while testing, but like you, I noticed it isn't consistent, so I couldn't pinpoint the cause or even be sure it wasn't just some random dev glitch.  The fact that you are getting it though does mean it exists outside of dev, which is closer to the solution.  i will test more, but if you find reliable reproduction steps, that will help a ton.

**Comment by RedBeast1959** [comment]
A little update here:

I found that when bug happens, only way to remove that infinite debuff is switching to auto value required modded item.
Only vanilla equipments cause infinite debuff, and when you hold and throw away modded equipment which has auto value, debuff will soon disappear.

**Comment by Caltinor** [comment]
I figured out the cause.  I'll have a fix in the next update.
