### ISSUE TITLE
Crafting Requirement Ignored After Creative Mode [1.16.5]

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#109]
**Describe the bug**
This bug only shows up if enter creative mode before entering survival and trying to craft.
Adding a crafting requirement of `"cooking": 30` to `minecraft:golden_carrot` in `req_craft.json` shows up in tooltip fine but doesn't stop you from crafting it.

**Expected behavior**
The item should not be able to be crafted by a player without the required amount of `cooking`.

**To Reproduce**
1. Add a requirement of `"cooking": 30` to `minecraft:golden_carrot` in `req_craft.json`  https://pastebin.com/9tJWFM31
2. Create a game in creative mode
3. Give yourself 1 carrot, 8 gold nuggets, and a crafting table
4. Enter survival mode
5. Try crafting a golden carrot
6. Get golden carrot

**Screenshots**
![image](https://user-images.githubusercontent.com/6394544/196341971-a2d79d02-8c99-4da9-9e9d-448987d94353.png)
![image](https://user-images.githubusercontent.com/6394544/196342002-8c398d08-4120-4c30-a207-d16e9235f442.png)

**Versions:**
 - Minecraft: 1.16.5
 - Loader: 36.2.39
 - PMMO: 1.16.5-3.67.6

**Comment by Caltinor** [comment]
Crafting reqs are busted.  Every dev i've talked to that tries to implement something that limits crafting has had the same issue.  Outside of hardcoding something directly into the GUIs that handle crafting (which you can't really do for other mods, and so you can only really affect vanilla), there is no clean or sure-fire way to do it.  This is why crafting reqs were removed in the rework.  It works only some of the time in the legacy implementation and breaks quite easily when other mods are introduced.

**Comment by SomewhatDamaged** [comment]
Oof. Fair enough.
