### ISSUE TITLE
Directionality to the vein miner and/or vein patterns.

### ISSUE THREAD

**Issue by Caltinor** [Caltinor/Project-MMO-2.0#11]
Allow the vein miner to have veining shapes such as being able to vein stairs or tunnels as an alternative to the chaining method currently available.

**Comment by SomewhatDamaged** [comment]
A good idea for one mode would be to look at how the "building wands" work and mimic their flexibility but with removing blocks instead.

So say you mine out a 3x3 gap by hand, then target a block on the newly exposed face, activate "autoshape vein miner" and dig, and it will carve out the next 3x3 section. Shouldn't be hard to search nearest blocks with "air" in the direction the player is mining from, right? This could also let you bypass target types—so you could mine every block in that area (assuming you have enough charge).
