### ISSUE TITLE
Skill Bonuses Multiplying When Saving and Restarting

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#111]
**Describe the bug**
Every time the game is reloaded, leather armor (haven't tested with others) bonuses get larger and the game lags more.

**Expected behavior**
The bonuses should be consistent despite reloading and there shouldn't be this lag.

**To Reproduce**
1. Give yourself leather armor
2. Put on leather armor
3. Save and exit, then load game again. Observe bonus is larger (and you gain more xp)
4. Keep doing 3 and notice lag is increasing too

**Screenshots**
![image](https://user-images.githubusercontent.com/6394544/197369940-65672a72-8046-4917-8825-8f0537e516c9.png)
![image](https://user-images.githubusercontent.com/6394544/197369954-9fd17a5a-6f9d-44ac-b10a-b396dd3e5d9a.png)
![image](https://user-images.githubusercontent.com/6394544/197369974-c29dd5ab-c775-4588-ac77-80bf039251da.png)

**Versions:**
 - Minecraft: 1.19.2
 - Loader: Forge 43.1.34
 - PMMO: 1.19.2-0.5.2

**Additional context**
Exiting the game and starting it fresh resets back to normal values again.

**Comment by Caltinor** [comment]
Note to self.
- add `TooltipRegistry#clearRegistry`
- call `TooltipRegistry.clrearRegistry()` in `CP_ClearData#handle`

the cause is due to multiple entries into the list for the same item which occurs during client join when the `CP_SyncData_Objects` packet calls `Core#registeryNBT`.
