### ISSUE TITLE
A Keyword for Datapack Files to Force the Datapack Version

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#114]
**Describe the solution you'd like**
A keyword like `"strict_override" = true` for datapack files such that they completely replace any other version of the file lower in the datapacks priority.

**Why is this feature needed**
Right now, to ensure you override all the settings in the default configs, you have to fill in all the values of the default config and set them to a default value. Ex: This biome overwrite https://pastebin.com/tSGkssCY

So with a `strict_override` it would look like:
```
{
    "strict_override":true
}
```

**Comment by Caltinor** [comment]
This is what vanilla's datapack filters already do.  You can use `/pmmo genData disabler` to have a pack automatically created to disable lower data. 

This disabler pack only has a `pack.mcmeta` with filters which you can cut/paste to your own pack or use as reference.  This specific filter disables all lower priority pmmo data, however, you can add specific filters to only disable things like biomes while leaving the rest intact.

**Comment by SomewhatDamaged** [comment]
Oh! Didn't know about that one. Perfect!
