### ISSUE TITLE
Agility doesn't work properly

### ISSUE THREAD

**Issue by StepM4Sherman** [Caltinor/Project-MMO-2.0#127]
So my agility skill isn't providing any bonuses, I think it bugged after one of my deaths but i'm not 100% sure.
Playing the modpack "Roguelike adventures and Dungeons 2"
Is there a way to reset the skill?

![bug](https://user-images.githubusercontent.com/117384854/199796891-4d3c4fe9-6f17-4b18-98d9-ad8558173c3c.PNG)

**Versions:**
 - Curse Forge-36.2.33
 - PMMO: 1.16.5-3.67.6

**Comment by Caltinor** [comment]
The settings which control the speed bonus are in pmmo-common.toml.  make sure the modpack hasn't changed the settings to give no bonus.

**Comment by StepM4Sherman** [comment]
I'm guessing it's supposed to be the "speedBoostPerLevel" at the bottom?
If yes, where can I check what it's base value is supposed to be?

![bug2](https://user-images.githubusercontent.com/117384854/199829424-f0ee3d27-63a6-4617-a8f9-3685294194dc.PNG)

**Comment by Caltinor** [comment]
you could stash this config somewhere and let a new one generate for reference.  the default value is `0.5` though.
