### ISSUE TITLE
Having statscreen visible makes the game lag horribly sometimes

### ISSUE THREAD

**Issue by Pawelnougoed** [Caltinor/Project-MMO-2.0#130]
**Describe the bug**
Having the stat screen open (Lalt)  makes the game slow down to a crawl
This has also been experienced by someone playing with me on one server.

**Expected behavior**
This has not been happening before. FPS should be normal.

**To Reproduce**
1 Show stats in corner
2 Game slows down
3 Hide the stats
4 Game returns to normal state

**Versions:**

    Minecraft: 1.19.2
    Loader: Forge-43.1.52
    PMMO: 1.19.2-0.5.5

**Comment by Caltinor** [comment]
Somehow i overlooked this issue in my two previous sweeps.  this has been fixed in the most recent version.
