### ISSUE TITLE
Perk Suggestion: A Perk That Gives Skill XP Bonuses

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#133]
**Describe the solution you'd like**
A toml-based perk that can apply a bonus to PMMO XP gains for specific skills.

**Why is this feature needed**
Currently there is no perk to modify XP gains.

**Describe alternatives you've considered**
Maybe an idea for the expansion perks pack proposed?

**Comment by Caltinor** [comment]
This is lumped together with #81.  Basically, perks were never designed to interact with XP.  I added a way for them to provide XP, but even then the regular XP just gets added on, and no perk has been created yet (to my knowledge) which uses this feature.  This request plus the other need some serious design considerations and probably a rather large rewrite of certain areas of the code.  just like #81, i'm going to have to backburner this until I can come up with a clean way to make that change.

**Comment by Caltinor** [comment]
I think the new 1.21 project will capture this better.
