### ISSUE TITLE
An Event (able to trigger perks) For Specific Player Effects

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#134]
**Describe the solution you'd like**
An event that triggers on effects, that could take requirements of what the specific effect and level is.

**Why is this feature needed**
To be able to trigger perks based off status effects (like `luck` effect giving various minor perk-based buffs).

**Describe alternatives you've considered**
Playing a tower defense game on my phone.

**Comment by Caltinor** [comment]
This is already under works via #10 .  The existence of an XP awarding event implies the ability to have perks associated with it.

**Comment by SomewhatDamaged** [comment]
Oh, cool!
