### ISSUE TITLE
Dynamic Tree compat issue cause CTD when trying to mine.

### ISSUE THREAD

**Issue by VirtualGaming1** [Caltinor/Project-MMO-2.0#135]
So when ever I try to hit a Dynamic Tree the client CTD but the server keeps going and did not log anything about the issue.

Here is the crash log. (at first I thought it was dynamic tree side but look more into the crash log it saying null for "Level")

[crash-2022-11-20_01.19.48-client.txt](https://github.com/Caltinor/Project-MMO-2.0/files/10049083/crash-2022-11-20_01.19.48-client.txt)

**Comment by Caltinor** [comment]
This is a known issue.  It's caused by AutoValues. Give DT blocks manual XP/req values and it goes away.

**Comment by VirtualGaming1** [comment]
how in a way I am able to do that?

**Comment by Caltinor** [comment]
Run `/pmmo gebData` then go to your datapack folder for that world, find the `data/dynamic trees/blocks/` folder, and edit each file to have break XP to your liking and reqs of zero.

**Comment by VirtualGaming1** [comment]
will try that

**Comment by VirtualGaming1** [comment]
just want to make sure. it should be /pmmo genData not geb

**Comment by Caltinor** [comment]
correct.

**Comment by VirtualGaming1** [comment]
this is all im am seeing in data folder
![image](https://user-images.githubusercontent.com/20447403/202897813-773975c6-19f1-4bd0-b4b3-2f9048ff9ca0.png)

**Comment by Caltinor** [comment]
you're in the `world/data` folder.  go to `world/datapacks/generated_data/data/dynamictrees/blocks`

**Comment by VirtualGaming1** [comment]
I was just about to edit and say I found it. sorry my head been hurting when I woke up

**Comment by VirtualGaming1** [comment]
What would I need to do to reload?

**Comment by Caltinor** [comment]
`/reload`

**Comment by VirtualGaming1** [comment]
I would recommend be able to do /genData (modname) just incase there is server have lots of mods with it. it also auto override for the mods

**Comment by Caltinor** [comment]
you can just delete the other folders if you don't need them.

**Comment by VirtualGaming1** [comment]
doing that right now but I do have over 200 mods and it is about to take 20 mins so far

**Comment by VirtualGaming1** [comment]
im going to roll back. this will be an issue if I have to keep on doing this when I run into more issue like this.
