### ISSUE TITLE
Option to display Powerlevel or other calculated "strength" stat by player name

### ISSUE THREAD

**Issue by MattB70** [Caltinor/Project-MMO-2.0#15]
**Describe the solution you'd like**
A method to quickly identify and compare player's power in multiplayer.

**Why is this feature needed**
Displaying a player's local powerlevel or another strength related stat would be an effective way to improve the PVP experience. Identifying threats as well as equals is needed when players can be wearing identical gear while not on equal footing.

**Describe alternatives you've considered**
With #8, this effect can be achieved with commands, but it would be taxing on the server.

I have already written the script to pull powerlevel (though the command does not have a return value so it doesn't work) and concat it with player names. Using this level+name string as the name of an invisible armour stand and moving it with the player achieves the effect at a great cost.

_I'd love for these features to be present in 1.18.2, but I understand if the focus is on 1.19._

**Comment by Caltinor** [comment]
@MattB70 I need to understand this request a bit more to implement it.  From my perspective, power level is not easily calculated.  For example, i could configure HP, Speed, and Damage to all use different skills which then poses the problem of how do you define a power level?  HP is going to heavily outweigh damage and speed in raw value, and even if i do some balancing calculation, if HP is based on smithing, how does that provide any useful information for your pvp scenario?  Lastly, power level is only a measure of how strong mobs become, so I don't know how it would relate to PVP.  If you could help elaborate on this feature, I would greatly appreciate it.  Feel free to ping me in discord if you want to chat about it.

**Comment by MattB70** [comment]
I think the reason as for why I want to display a power level above players has changed from that of PVP to instead clearly understanding how mobs will scale when playing PVE with a group. Players on my server often die due to not knowing they are playing with someone with a much higher mob scaling factor than themselves.

The power level I would like displayed would be the number used to calculate mob scaling. In the original PMMO I believe this was `max(strength,magic,endurance)`, though whatever your new PMMO rework uses would of course be more useful.

Additionally, having getters in-game for something like my computer craft scripts to collect player data as for use in big physical scoreboards, calculating difficulty for events, or even something as simple as alerting the player when the nearby power level has exceeded a certain threshold and will be too difficult (a sort of "you are too weak for this" warning), would be really cool.

After playing with PMMO and getting feedback from players on my server, these seem to be the most wanted QOL features.

Thanks for the ping on Discord, I often have to fish through a lot of Github emails to find issue comments. :P

**Comment by Caltinor** [comment]
this is fixed via https://github.com/Caltinor/Project-MMO-2.0/commit/6de17135e98507040685c02973886d99c2fc21b6

In effect by using skill groups users can make their own "power level" scale, or even multiple scales.  The synergy of these two features completes this feature request.
