### ISSUE TITLE
CTD

### ISSUE THREAD

**Issue by EldrinFal** [Caltinor/Project-MMO-2.0#150]
**Describe the bug**
Game crashed out to the desktop.  I tried to punch some leaves.  Happened to be infected with Zombie disease at the time.

**Expected behavior**
I expected to break the leaves and the game not to crash.

**To Reproduce**
I will try again in the same world and see if it happens again.

**Screenshots**
N/A

**Versions:**
 - Minecraft: 1.18.2
 - Loader: Forge-40.1.85)
 - PMMO: 1.18.2-4.0.1

**Additional context**
Very early in the game.  Heavily modded setup.
[crash-2022-12-03_16.38.41-client.txt](https://github.com/Caltinor/Project-MMO-2.0/files/10147628/crash-2022-12-03_16.38.41-client.txt)

**Comment by EldrinFal** [comment]
Loaded the same world and the same thing happened.  CTD.  Created a new world and when I try to punch anything it crashes out.  
[crash-2022-12-03_17.01.57-client.txt](https://github.com/Caltinor/Project-MMO-2.0/files/10147636/crash-2022-12-03_17.01.57-client.txt)

**Comment by Caltinor** [comment]
It's caused by the BreakSpeed perk.  until I can get a fix released.  remove all references to "pmmo:break_speed" from you pmmo-perks.toml

**Comment by EldrinFal** [comment]
Ok, will do. Thanks!
