### ISSUE TITLE
Max Level resetting to 329 if value entered is higher. 

### ISSUE THREAD

**Issue by malice936** [Caltinor/Project-MMO-2.0#151]
Describe the bug
When changing the "Max Level" setting to anything higher than 329 in the pmmo-server.toml the value resets to 329 when loading the world or reloading configs, even when using the "Configured" mod which claims the default is 1523.

Expected behavior
I expected to be able to set it higher than 329...

To Reproduce
Create a world, and try to change the value to something higher than 329....

Versions:
Minecraft: 1.19.2
Loader: Forge-43.1.55
PMMO: pmmo-1.19-1.0.1

Additional context
Have repeated across several worlds with the same result.

**Comment by Caltinor** [comment]
This is intended behavior.  Based on the XP formula you have in the [Levels] section, the max level is set by the level a player would have after getting 9,223,372,036,854,775,807 xp in a skill.  If you would like a higher max level, flatten the curve of your exponential formula.

**Comment by malice936** [comment]
Ah, Thanks, I was planning on ignoring experience all together.

**Comment by Caltinor** [comment]
In that case, use a linear formula that gives like one level perXP so you have have a stupid high max level then whatever you set will stick.

**Comment by malice936** [comment]
eh was mostly testing to see how endurance affects max health, which no matter what I set it to it seems to be 5 additional hearts, which iirc you need a mod to bypass, thanks again for the help.

**Comment by Caltinor** [comment]
actually this might be the implied max boost.  PMMO ships with a default max boost so that getting 1000 levels doesn't give a player 50 extra hearts.  try adding the property `max_boost = 20` in your pmmo-perks.toml and you should get values up to 10 extra hearts.

**Comment by malice936** [comment]
ah thanks, sorry for all the trouble. lol
