### ISSUE TITLE
PMMO crashes when breaking trees with Dynamic trees

### ISSUE THREAD

**Issue by Monikette** [Caltinor/Project-MMO-2.0#153]
**Describe the bug**
PMMO crashes the game when breaking any tree with Dynamic trees installed.

**To Reproduce**
Install Dynamic trees [https://www.curseforge.com/minecraft/mc-mods/dynamictrees](url) and
break any tree.

**Screenshots**
No, full crash log here: [https://pastebin.com/EBGz8zpz](url)

**Versions:**
 - Minecraft: 1.16.5
 - Loader: Forge-36.2.39
 - PMMO: Latest for said version

**Additional context**
Removing PMMO solves the crash issue.

**Comment by Monikette** [comment]
It hasnt been updated in months for 1.16.5 so i thought it wll suffice.
The version is 3.67.6
I tried setting 0 for break speed and extra chance for logs but it still crashes, i will try the xp now aswell.

*edit*
Set all involving wood to 0 and false and still crashes.

**Comment by Caltinor** [comment]
You have to use the beta version of dynamic trees, not the release.

**Comment by Monikette** [comment]
Okay got that, replaced the release, still crashed same way...
Here`s the crash log: https://pastebin.com/Guu2Kiw5

Read on another issue that might be somekind of "mining perk" this mod adds, as dynamic trees hates when mods alter block breaking, maybe something with that?

**Comment by Caltinor** [comment]
I know this is basically a meme, but it works more often than not.  what happens when you remove optifine?

**Comment by Monikette** [comment]
Ill test it next time im on, then report back :)

**Comment by Monikette** [comment]
Did one better even and made new instance with just dynamic trees and PMMO guess what happened?
It still crashed just as i expected it to at this point...same way with same no such method error.

**Comment by Caltinor** [comment]
I honestly have no idea what is going on.  Others have been able to use DT with PMMO without issue.  I even looked through the DT repo on GH and could not find that class anywhere in their repo or history.  You've got something going on that isn't normal and until that comes to light, there's nothing i can do.
