### ISSUE TITLE
Error loading in a server modpack

### ISSUE THREAD

**Issue by caamillo** [Caltinor/Project-MMO-2.0#159]
**Describe the bug**
Mod loading error has occurred

**Expected behavior**
Loading the server

**To Reproduce**
Starting the server on raspberry with java 11

**Screenshots**
https://pastebin.com/RugJhXPM

**Comment by Caltinor** [comment]
You have to use the beta versions of FTBQ with PMMO 3.67.x

**Comment by caamillo** [comment]
with FTBQ you mean [FTBQBorealis-1.0.6.jar](https://www.curseforge.com/minecraft/mc-mods/ftbqborealis/files/3235443)?

**Comment by caamillo** [comment]
version 1.0.6?
