### ISSUE TITLE
Lvl bug for ex gaining with Dynamic Tree (maybe other as well)

### ISSUE THREAD

**Issue by VirtualGaming1** [Caltinor/Project-MMO-2.0#164]
**Describe the bug**
With Dynamic Trees, for some reason the smaller base "1x1 trunk" after reaching lvl 2 for woodcutting it stop giving xp.
also before you ask me. I will not use 4.0 version because it is not Large modpack friendly for data editing.

**Expected behavior**
should still be getting XP

**To Reproduce**
step 1: chopdown dynamic tree before level 2 (for compairing)
step 2: level up to level 2 (any way, just gaining Xp or use command)
step 3: chopdown another tree.

**Versions:**
 - Minecraft: 1.18.2
 - Loader: 40.1.85
 - PMMO: Project_MMO-1.18.2-3.69.11

**Additional context**
Dose not give out any kind of log about it. confusing why it is doing it. It dose work with the bigger tree trunk and new planted trees.

**Comment by Caltinor** [comment]
This seems like either an interaction effect or a config problem.  In any case, this version of pmmo is no longer supported.  Version 4.0 includes a tool which will migrate your current data to the new datapack format.  The upcoming version 5.x will also support traditional tags in the "isTagFor" section.

You are welcome to use whatever version you like, but bug reports are for supported versions.
