### ISSUE TITLE
Death Auto Value Not Disabling

### ISSUE THREAD

**Issue by Tyrius1** [Caltinor/Project-MMO-2.0#17]
**Describe the bug**
When the auto value for Death is set to false mobs continue to grant large amounts of endurance experience when slain.

**Expected behavior**
To not grant any experience on death when disabled.

**To Reproduce**
1. disable death auto value in config
2. kill mob
3. get granted 100s of endurance xp

**Versions:**
 - Minecraft: 1.19
 - pmmo-1.19-0.0.4.jar

**Comment by Tyrius1** [comment]
It is able to be disabled when removing the entries from the default xp values.
			[Auto_Values.Xp_Awards.Entities."DEATH Default Xp Award"]

**Comment by Caltinor** [comment]
Good to know. Thank you.  I think I might know the cause of the issue.
