### ISSUE TITLE
Way to manually add mod tools to PMMO

### ISSUE THREAD

**Issue by ByucknahTheRed** [Caltinor/Project-MMO-2.0#170]
**Describe the solution you'd like**
I think it would be handy if there way a way to add custom tools to Project MMO and classify what they fall under in terms of experience, use restriction, etc.

For example, take Simply Tools which adds hammers and excavators to the game which mine/dig in a 3wx3hx1d area. It would be nice to be able to add a tool to a config file and set the skill requirements for the items.

**Why is this feature needed**
For better synergy with add-ons that add new tools to be related to PMMO.

**Comment by TheTaterLord** [comment]
you can add items to the configs? thats the whole point of the mod in 1.19 this is all done via datapack and for 1.16 its all done in configs and you can make your own mod to add items just make sure they fire off the correct events for pmmo to listen for.
