### ISSUE TITLE
Can't use sword but should be able to

### ISSUE THREAD

**Issue by Themporal** [Caltinor/Project-MMO-2.0#171]
**Describe the bug**
I can't use weapons that I should be able to use. The bug only just started happening.

**Expected behavior**
I should be able to use the weapon

**To Reproduce**
1. Hit mob
2. Get message "You are not skilled enough to use..."

**Screenshots**
![2022-12-30_15 56 20](https://user-images.githubusercontent.com/38329479/210083671-bffe437a-e20e-46b9-a10f-c19914a9d1b4.png)
![2022-12-30_15 56 26](https://user-images.githubusercontent.com/38329479/210083675-8f0c5b18-39ff-4b10-b17e-0e1b64eed81a.png)

**Versions:**
 - Minecraft: 1.16.5
 - Loader: Forge - 36.2.33
 - PMMO: ?

**Additional context**
The bug is ocuring in the latest version of 'Roguelike Adventures and Dungeons 2' '0.95a Beta'

**Comment by Caltinor** [comment]
Modpacks can customize a lot of settings. You will need to ask the pack authors.
