### ISSUE TITLE
No crafting XP when crafting items

### ISSUE THREAD

**Issue by comradeflats** [Caltinor/Project-MMO-2.0#175]
**Describe the bug**
When I make something in the crafting table, I don't get crafting XP. Items display how much crafting XP tey should give, but I don't get it. 

**Expected behavior**
When I craft an item, I should get a certain amount of XP for crafting it as shown in the crafting GUI. 

**To Reproduce**
1. Go to the crafting menu, arrange items, view the outcome and hover over it to see how much XP it should give. 
2. Craft the item, no XP is given. 

**Screenshots**[
Drive-link of me recreating the issue ](https://drive.google.com/file/d/1HWMvXuKppDeuMrB7YQgtTeJTPtjvOnYE/view?usp=sharing)

**Versions:**
 - Minecraft: 1.19.2
 - Loader: (Forge - 1.19.2 - 43.2.1
 - PMMO: pmmo-1.19-1.0.0

**Additional context**
All other XP is coming in just fine, but no crafting XP.

**Comment by Caltinor** [comment]
please confirm this bug still exists on pmmo-1.19-2.1.2.

**Comment by DaddyP1G** [comment]
Try SHIFT CLICKING an item.  I had that bug before

**Comment by comradeflats** [comment]
> please confirm this bug still exists on pmmo-1.19-2.1.2.

It's working now that I switched to pmmo-1.19-2.1.2

Thanks!
