### ISSUE TITLE
All items can be Salvaged- no longer gives "This item can not be salvaged" when no info is available

### ISSUE THREAD

**Issue by DaddyP1G** [Caltinor/Project-MMO-2.0#176]
**Describe the bug**
Every item can be shift click on the smithing table.  it takes the item away even if it has no salvage recipe.   Some magical items like a ring with an effect will give you that effect and take the time.  The effect disappears when you log.

**Expected behavior**
receive the "This item can not be salvaged" message as before. 

**To Reproduce**
1. Salvage an item without a salvage data

**Screenshots**

**Versions:**
 - Minecraft: 1.19.2
 - Loader: Forge 43.2.2
 - PMMO: 1.19.2.1.3 V1 (beta)

**Additional context**

**Comment by Caltinor** [comment]
As an additional aspect of this bug, I also noticed that level reqs were not being enforced.  I will be including a fix for that in this as well.
