### ISSUE TITLE
XP duping from pumpkin seed

### ISSUE THREAD

**Issue by HollishKid** [Caltinor/Project-MMO-2.0#178]
**Describe the bug**
When I plant a pumpkin seed in a spot where it can not properly grow (no free adjacent spot) and stand still next to it, I will receive farming XP continuously. 

**Expected behavior**
The farming XP should maybe not be granted when the source is a mature pumpkin plant.

**To Reproduce**
See the bug description.

**Versions:**
 - Minecraft: 1.16.5
 - Loader: Forge-36.2.39
 - PMMO: 1.16.5-3.67.6

**Comment by Caltinor** [comment]
interesting cheese.   So you've blocked all of the places the pumpkin block can spawn, but the stem continuously tries to place it and you are getting XP as a consequence?

**Comment by HollishKid** [comment]
> interesting cheese. So you've blocked all of the places the pumpkin block can spawn, but the stem continuously tries to place it and you are getting XP as a consequence?

That is exactly what happens. I actually found it by mistake.
