### ISSUE TITLE
Translation (1.19.2)

### ISSUE THREAD

**Issue by Sova626** [Caltinor/Project-MMO-2.0#184]
**Describe the bug**
Translation into russian does not work instead some hieroglyphs.

**Expected behavior**
The previous version was fine until I updated the mod.

**Screenshots**
![0](https://user-images.githubusercontent.com/105182565/212502959-a0a5e482-730f-4e3f-b4be-be4d8cccb27b.png)
![1](https://user-images.githubusercontent.com/105182565/212502967-67d1c918-6b98-4f0c-b0ba-8cac07166ed6.png)

**Versions:**
 - Minecraft: (1.19.2)
 - Loader: (Forge-43.2.3)
 - PMMO: 1.19.2-2.1.3

**Additional context**

**Comment by Caltinor** [comment]
Thank you.  it appears to be an issue with the writing of the files because the text in code is properly using the Cyrillic alphabet.  I'll try and get a fix out asap.  i'm sure Russian isn't the only language affected.

**Comment by Sova626** [comment]
And in Ukrainian the same error

**Comment by Caltinor** [comment]
Yeah i notice it on the Chinese translations too.  I'll have it fixed tomorrow and push a hotfix for the issue.  Thank you again for bringing this to my attention.

**Comment by Sova626** [comment]
Happy to help) I will look forward to your update

**Comment by half5life** [comment]
Same issue with Minecraft: (1.20.1) and PMMO: 1.20.1-1.0.2

**Comment by Caltinor** [comment]
It reemerged?  well damn.  alright.  I'll figure out why the encoding is failing to stick.  Thanks for the report.
