### ISSUE TITLE
RE: Anti-Cheese Implementation - Range From Source

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#192]
**Describe the solution you'd like**
Additional features for https://github.com/Caltinor/Project-MMO-2.0/issues/189

A way to cut off XP after a particular range from an XP source.

Options:
Distance in blocks. (Maybe allow for diminishing returns?)
Same biome.
Same dimension.

**Why is this feature needed**
To stop intentional subversion of risk vs reward.

**Comment by Caltinor** [comment]
I don't fully understand the use case.  the only telegains i can think of are ones that you would want to be able to earn remotely.  could you elaborate?

**Comment by SomewhatDamaged** [comment]
My thought was to restrict automatable experience actions (farming, smelting, etc) to have a range limit of some sort. 

At least in my play experience, farming always seems to be my #1 skill because it is always ticking.

**Comment by Caltinor** [comment]
That's what I thought you were referring to.   🤔 I would not normally add such a restriction on the grounds that such a restriction would force players to hang around an area and not explore the world, or else they stagnate in farming and smelting.  I see that as forcing them to choose which XP they have to grow.   However, that may be a design decision of the packmaker.  It doesn't hurt to add this functionality without making it default behavior.

**Comment by Caltinor** [comment]
This feature is not feasible with the current setup of PMMO.  XP awards are not relationally sensitive to the player for which they are applied.  as such there is no mechanism which would seamlessly allow this kind of tracking without serious disruption of major systems.  This feature will not be implemented
