### ISSUE TITLE
Found Incompatibility with Enhanced AI

### ISSUE THREAD

**Issue by Nagasena12** [Caltinor/Project-MMO-2.0#196]
When running both this mod and EnhancedAI, mobs get insane speed and attacked damage. I tried to edit the serverconfig and also the config but it not worked.

**Versions:**
 - Minecraft: 1.18.2 
 - Loader: Forge 40.2.0 
 - PMMO: 1.18.2-5.1.3
 - (Incompatible mod): Enhanced AI 1.6.5 for 1.18.2
 - (Enhanced AI LIB): InsaneLib 1.5.3 for 1.18.2

**Comment by Caltinor** [comment]
It's not a mod incompatibility.  Turn off mob scaling in pmmo-server.toml

**Comment by Nagasena12** [comment]
I tried to set in the server config both Mobs scaling to false and exponential and "use exponential formula" to false but nothing chenged. I had to uninstall one of the 2 mods to fix their speed and attack damage

**Comment by Nagasena12** [comment]
I just made a new modpack and tried again. Now it seems to be solved. I don't know why in my previous modpack it was bugged beacause i was running only pmmo and enhanced AI. Maybe I needed to change mobs scaling to false before giving me pmmo levels by commands. Anyway now it's working properly. Thanks for your help and sorry for this inconvenience
