### ISSUE TITLE
[1.16.5-3.67.7] Not able to use a weapon despite meeting level requirement.

### ISSUE THREAD

**Issue by SSampyla** [Caltinor/Project-MMO-2.0#197]
**Describe the bug**
I sporadicly get this message "you are not skilled enough to use X as a weapon!", when using spartan weaponry throwable weapons, despite meeting the level requirement. This happens when hitting any mobs but does not trigger every time. It also prevented dealing damage, if the relevant setting was enabled in the config. I tried this on sheeps and zombies in a clean install without other mods and with default configs. 

**Expected behavior**
I expect to not get this message, when I meet the level requirement for the weapon.

**To Reproduce**
1. Spawn multiple sheeps
2. Get for example stone javelin from spartan weaponry mod
3. Get the required level
4. Throw the weapon at sheep a few times 
5. See message: "You are not skilled enough to use stone javelin as a weapon!"

**Screenshots**
![message](https://user-images.githubusercontent.com/106827080/215894372-44cac7a7-5b37-4d40-97ea-43c7a74800aa.png)
![enoughlevels](https://user-images.githubusercontent.com/106827080/215894407-7ebe7b63-ca0f-4098-80c5-8a2121dd9417.png)

**Versions:**
 - Minecraft: (eg 1.16.5)
 - Loader: Forge-36.2.35 (occured in Forge-36.2.39 too)
 - PMMO: 1.16.5-3.67.7
 - Spartan Weaponry: 1.16.5-2.2.0-rc-2

**Additional context**
We bumped on this issue on a server with 200 other mods, all players had this issue. One player had held spartan weapons randomly broken in hand but I was not able to reproduce this.

**Comment by XxInvictus** [comment]
I will have to do some testing but I believe this is due to the magic damage check. There is no check for if the damageType is thrown before deciding "if at distance then use magic xp/requirements". The same would probably also be a bug of the Trident too.

**Comment by XxInvictus** [comment]
A little bit of initial discovery is that Spartan Weaponry does not use alternative damageType values. All are "player" similar to melee attacks. Investigating alternative methods of detection.
