### ISSUE TITLE
Gain less xp

### ISSUE THREAD

**Issue by maipley** [Caltinor/Project-MMO-2.0#198]
Is there a way to gain less xp for all?
Without needing to raise the needed level for each item
for example a config to make that you always gain 0.5 of normal xp so you level up at half the speed

**Comment by SomewhatDamaged** [comment]
What version of the _mod_ are you using?

**Comment by maipley** [comment]
i'm using 36.1 forge
and Project_MMO-1.16.4-3.50.1.jar

**Comment by SomewhatDamaged** [comment]
In the `minecraft\config\pmmo-common.toml` file is an option `globalMultiplier = 1.0`.

Modify this value to adjust how much XP everyone gets. In your case, setting it to `0.5`.

**Comment by maipley** [comment]
ohhhh
but i have 2 files like that, pmmo-common.toml and pmmo-common2.toml
why are there 2?
and which one is the "correct" one?
also another thing, what can i do to make the maximum hearts to 10?

**Comment by SomewhatDamaged** [comment]
Only `pmmo-common.toml` should be used, as far as I know. 

In that same file, under `[Endurance]`, is an entry for `maxExtraHeartBoost = 100`

This is the maximum number of hearts granted. So setting it to 10 would mean people could have the 10 base hearts and 10 bonus ones.

**Comment by maipley** [comment]
thanks!
and last thing 
i moved the heart slider inside of the config when i had 1 heart and i lost it, then moved it to 1 again and i don't get it back
what can i do?

**Comment by SomewhatDamaged** [comment]
Uh, no clue on that sorry. I didn't know PMMO had sliders for that. I just use the config files to set it up.

**Comment by maipley** [comment]
and is there a way to reduce 1 level my endurance? 
cause i just hit 10 and i think every time i hit a level like 10 20 30 i get a heart

**Comment by SomewhatDamaged** [comment]
`/pmmo admin` and follow the prompts. You can add/remove levels and xp that way.
