### ISSUE TITLE
[Feature Idea] NBT Value to Bypass Requirements

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#200]
**Describe the solution you'd like**
A specific NBT value that can be set on item rewards that would allow players to use them no matter the skill requirements.

**Why is this feature needed**
It would, for example, allow exceptional one-time rewards that, to players, _feel_ special because they are something special. Maybe even include a special tooltip stating this.

**Describe alternatives you've considered**
Grinding up some beans, brewing a pot of coffee, and sitting down to relax and caffinate myself.

**Additional context**
Just another random idea for a _Cool Thing™️_ pack makers could use.

**Comment by Caltinor** [comment]
This is already possible.  consider this as an example as a tool req on a pickaxe 
```json5
"nbt_requirements": {
  "TOOL": [
    {"behavior_to_previous":"ADD_TO", "should_cases_add":false,
    //uses the existence of a property to give the base item a default value. "Damage" is an example
     "cases": ["paths":["Damage"], "criteria":[{"operator":"EXISTS", "value":{"mining":100}}]]
    },
    //SUB_FROM subtracts the default value from the item if our "Reqless" property is present
    {"behavior_to_previous":"SUB_FROM", "should_cases_add":false,
     "cases": ["paths":["Reqless"], "criteria":[{"operator":"EXISTS", "value":{"mining":100}}]]
    },
  ]
}
```
