### ISSUE TITLE
Bug with the glossary

### ISSUE THREAD

**Issue by Sova626** [Caltinor/Project-MMO-2.0#203]
Describe the bug
Can't open the glossary

Expected behavior
The previous version was fine until I updated the mod.

**Screenshots**
![0](https://user-images.githubusercontent.com/105182565/216796513-b8f4488f-1e14-4477-aa88-4c868833f70e.png)
expected it to open
![1](https://user-images.githubusercontent.com/105182565/216796938-01c3eb0c-8146-4f1b-ac13-b902db6bddbe.png)

**Versions:**
Minecraft: (1.19.2)
Loader: (Forge-43.2.4)
PMMO: 1.19.2-3.0.0

**Additional context**
Hello went into the world of mods did not crash, but as soon as I pressed the "P" key in the air to open the glossary game froze then crashed what is the problem ?
[crash-2023-02-04_19.07.54-client.txt](https://github.com/Caltinor/Project-MMO-2.0/files/10610015/crash-2023-02-04_19.07.54-client.txt)

**Comment by Caltinor** [comment]
Thank you. This will be fixed Tommie via hotfix. Thank you.

**Comment by Sova626** [comment]
Ok I will wait for your update
