### ISSUE TITLE
language

### ISSUE THREAD

**Issue by Sova626** [Caltinor/Project-MMO-2.0#206]
**Describe the bug**
All languages are gone except English

**Expected behavior**
The previous version was fine until I updated the mod.

**Versions:**
Minecraft: (1.19.2)
Loader: (Forge-43.2.4)
PMMO: 1.19.2-3.0.1

**Additional context**

**Comment by Caltinor** [comment]
🤦 I didn't run data before building.  I'll get another hotfix out to get them in. Thank you for bringing this to my attention.
