### ISSUE TITLE
Is there a way for me to change/add the requested xp levels in tools?

### ISSUE THREAD

**Issue by Twigdev** [Caltinor/Project-MMO-2.0#210]
I'm currently developing a modpack for minecraft 1.19 based on pmmo skill points progression

And as huge modpack, there is plenty of new weapons and tools that I can't add any level requirement. For example I added the "Simply Sword" mod and I coundn't find a way to add combat levels requirement to the new swords added, this would brake my modpack as you wuold be able to skip the tool progression by simply finding diamonds in loot chests and craft one of the strongest weapons on your first days 

I would like to know if there is a way for doing it because I can't publishe it wile this is not fixed

**Comment by Caltinor** [comment]
https://github.com/Caltinor/Project-MMO-2.0/wiki/Configuring-PMMO
