### ISSUE TITLE
Option to disable fireworks

### ISSUE THREAD

**Issue by Clinkr1000** [Caltinor/Project-MMO-2.0#211]
**Describe the solution you'd like**
Please bring back the options to control fireworks the newer versions

**Why is this feature needed**
fireworks are annoying, and when i first used this mod i would always disable them. now that option has been removed in recent releases. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by SomewhatDamaged** [comment]
Fireworks are Perks, which can be configured in `minecraft/saves/<yoursave>/serverconfig/pmmo-perks.toml`

An example of what to add/remove for a firework looks like

```
[[Perks.For_Event.SKILL_UP.fishing]]
    skill = "fishing"
    perk = "pmmo:fireworks"
```

Each skill that should have fireworks should have a perk in the SKILL_UP block of the config.

To remove a firework from a particular skill, delete/comment-out the firework perk section from the config.

**Comment by Clinkr1000** [comment]
couldnt there be an easier way, instead of having to manually delete/comment out blocks of text many times in a save file? like putting a global toggle in the pmmo-client.toml file?

**Comment by SomewhatDamaged** [comment]
The issue is that fireworks, in modern Minecraft, are handled server-side. It cannot be done on a per-client basis anymore.

**Comment by Clinkr1000** [comment]
couldnt it be put in server config then? if it can be disabled in pmmo-Perks.toml, which is saved client-side, there should be some way to do this.

**Comment by SomewhatDamaged** [comment]
`pmmo-Perks.toml` is a server-side config file. When you play singleplayer, Minecraft makes a server and you automatically connect to it.

**Comment by Clinkr1000** [comment]
darn.
