### ISSUE TITLE
[Question] What is Power Level?

### ISSUE THREAD

**Issue by okzerus** [Caltinor/Project-MMO-2.0#213]
I wanna modify the mob's difficulty scaling with the player's progression, but I don't quite understand the meaning of Power Level.
found zero information about it, and didn't find any links for support, so I'll just ask here. I'm sorry just in case.

**Comment by Caltinor** [comment]
I am going to assume you are on 1.16 or 1.12. In that case, the power level combines your combat, endurance, and archery skills. When mobs spawn, the average power level of all players near where that mob is spawning is used to calculate its scaling.

**Comment by okzerus** [comment]
thank you very much. do you mind making some sort of a support discord server for questions like mine? I have one more, but still not sure if it is the right place to ask it. and yeah, I'm playing on 1.16.

**Comment by okzerus** [comment]
just in case, I won't ask to ask, so here is my question: is it possible to give custom attributes to custom skill?
for example, I have a "corruption" skill, and it should decrease the player's health at each level, so I just stole some configuration from Endurance skill and did this:
![image](https://user-images.githubusercontent.com/78618619/219946452-f7a2f918-f9f2-4a2a-bb63-23e5c4d8fa17.png)
will it work?

**Comment by Caltinor** [comment]
https://discord.gg/5NVNkNB
and that configuration won't work.  1.16 was very hard-coded for things like that.  if you want that level of customization, you'll need to jump to 1.18 or 1.19.
