### ISSUE TITLE
[1.16.5] Track Mods Updating to Forge Tagging

### ISSUE THREAD

**Issue by XxInvictus** [Caltinor/Project-MMO-2.0#216]
**Describe the solution you'd like**
This is for the purpose of giving an Issue in this repo to link back to from other repo's and track requests for those mods to update to forge tagging.

**Why is this feature needed**
To ensure appropriate compatibility between mods and allow cleaner Smelting XP configs

**Additional context**
I am currently reworking Cooking/Smelting to get the XP values of the output instead of the input and as part of this I need to update configs to transition the input XP values to the outputted item. As part of this I am reviewing which mods are using proper forge tagging for things like Ingots and Gems.
This ticket is for the purpose of being able to link issues/PR's to other repos back to this one for tracking when the PR's are accepted or the work complete and reintegrate them into the config file.

An example of proper the input conversion to proper forge tagging of the output item below:
Before: `"biggerreactors:cyanite_dust"`
After: `"#forge:ingots/cyanite"`

**Comment by XxInvictus** [comment]
Mods Requiring Updates to Forge Tagging:
Astral Sorcery - https://github.com/HellFirePvP/AstralSorcery/pull/1983
Mystical Agriculture - https://github.com/BlakeBr0/MysticalAgriculture/issues/585
The Abyss II - https://github.com/Y3Z0N/theabyss/issues/89

**Comment by Caltinor** [comment]
@XxInvictus is this completed or should this issue stay open?

**Comment by XxInvictus** [comment]
Honestly I had pretty low hopes of these Mods updating to begin with as their issues/PR's looked largely untouched for quite a while so I will close this out and if people want to add items from these mods they can add them as items instead of nice tags :(
