### ISSUE TITLE
Missing config options

### ISSUE THREAD

**Issue by border999** [Caltinor/Project-MMO-2.0#218]
**Describe the bug**
Missing the "Mob scaling" and "Disable level requirements" config options

**Expected behavior**
I expected the option to turn off mob scaling and the level requirement for tools to be in the config. Regenerated the project MMO config files just in case and no dice. In case anyone asks if I've tried the pmmo-server config, NO that one did not generate. All I have is client, common, and common-legacy.

**To Reproduce**
???

**Screenshots**

**Versions:**
 - Minecraft: (1.18.2)
 - Loader: (Forge-40.2.0)
 - PMMO: 1.18.2-6.0.2

**Additional context**
(pmmo-client) https://gist.github.com/border999/e7e95e13a5b5603e71fb56ecbdeb4780
(pmmo-common) https://gist.github.com/border999/b5c9b52d5ebbc48d27a34bfb9cc848b1
Both common and common legacy are the same.

**Comment by TheTaterLord** [comment]
Are you on a server or singleplayer?

**Comment by border999** [comment]
singleplayer

**Comment by TheTaterLord** [comment]
The server config should be located in your world folder and I've never seen a case of it not generating
