### ISSUE TITLE
Question - Don't understand charge ... how do I default to let players break 64 blocks?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Caltinor/Project-MMO-2.0#219]
Question - Don't understand charge ... how do I default to let players break 64 blocks?

**Comment by P3rf3ctXZer0** [comment]
In vein mining!

**Comment by TheTaterLord** [comment]
In 1.18/1.19 charge is and charge rate is determined from the items equipped
In 1.16 it's determined by your mining/woodcutting skills and the blocks hardness

**Comment by Caltinor** [comment]
Expanding on what TheTaterLord said, charge is something players get from items they hold/wear.  Each item can add to the players charge rate and/or their max charge capacity.   Players themselves decide how many blocks they want to break at once. 

Now, if you wanted to make it so players had 64 vein charge at all times but no more, here is what you would do.
1. Remove vein from all but one type of armor (let's say leggings)
2. Put vein settings on every legging piece with a charge cap and charge rate of 64. This will cap the amount at 64 and also instantly regenerate.
3. Make sure all the block consume amounts are set to 1 so you get a 1:1 charge:block ratio. 

If you want more help with any of these steps pop over to our discord.

**Comment by P3rf3ctXZer0** [comment]
Okay thank you very much :D
