### ISSUE TITLE
1.19.2 - Player Used Silent Gear Saw While Vein mining which caused a massive crash. 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Caltinor/Project-MMO-2.0#227]
**Describe the bug**
GamerGirl attempted to chop down a tree using saw by silent gear while vein mining was active and the server completely crashed.

**Expected behavior**
A safe guard when silent gear calls on a tree chopping.

**To Reproduce**
Enable Vein mine while trying to use Silent Gear saw (She was using diamond.)

**Screenshots**

**Versions:**
 - Minecraft: 1.19.2
 - Loader: Forge-43.2.6
 - PMMO: pmmo-1.19-3.0.2
 - Silent Gear: silent-gear-1.19.2-3.2.5
 - Silent Lib: silent-lib-1.19.2-7.0.3
 - Dedicated Sever: https://www.curseforge.com/minecraft/modpacks/fiction-friction-pixelmon/files/4416109

**Additional context**
Crash Log - https://gist.github.com/P3rf3ctXZer0/fc17f1264125e6570ab859125d020c17
Debug Log - https://gist.github.com/P3rf3ctXZer0/0f55caa8a3cd0c46d42afd056a1b55cf
Latest Log (Its too large.) https://www.dropbox.com/s/8nm4o2uh6vq4o0u/latest.log?dl=0

**Comment by Caltinor** [comment]
Carrying over details from the SG sister-issue.  Add a vein mining blacklist for items.
