### ISSUE TITLE
Vein miner multiplayer

### ISSUE THREAD

**Issue by Orangejewce92** [Caltinor/Project-MMO-2.0#235]
**Describe the bug**
Once 5 people join a server vein miner turns off

**Expected behavior**
For vein mine to still work regardless of player count

**To Reproduce**
Join a server with 5 or more players.

**Screenshots**
N/A.

**Versions:**
 - Minecraft: 1.18.2
 - Loader: Forge-40.2.1
 - PMMO: 1.18.2-6.0.2

**Additional context**
N/A

**Comment by Caltinor** [comment]
Is there anything in latest.log about the vein miner?

**Comment by Caltinor** [comment]
Closing for now.  This can be reopened if we have more information.
