### ISSUE TITLE
[1.19.2] Curio slots do not apply bonuses but apply debuffs.

### ISSUE THREAD

**Issue by S0ndz** [Caltinor/Project-MMO-2.0#236]
**Describe the bug**
Using datapacks to configure XP bonuses for Artifacts curio items does not apply the specified bonus. However, applying a level requirement does give debuffs as expected. Even holding the desired item gives a debuff penalty despite not being specified.

**Expected behavior**
Equipping the artifacts item should apply the XP bonus to the specified ability, but does not. Equipping the artifacts in the curio slots does give debuff when the required level is not met. Holding the item also gives a debuff despite it not being configured in the .json document.

**To Reproduce**
1. Go to '\datapacks\generated_pack\data\artifacts\pmmo\items'
2. Edit desired item
3. Apply changes and do /reload in game
4. Equip item
5. XP earned remains the same.

**Screenshots**
![image](https://user-images.githubusercontent.com/127669200/224547189-26427a2a-6065-43a1-96f5-2b9bf7ac7846.png)
![image](https://user-images.githubusercontent.com/127669200/224547874-48508cfa-5a7c-4aad-9846-70d86df69ba9.png)

**Versions:**
 - Minecraft: 1.19.2
 - Loader: Forge-43.2.6
 - PMMO: 1.19-3.0.2
 - Curios API 1.19.2-5.1.3.0
 - Artifacts 1.19.2-5.0.2

**Additional context**
Hoping this is something dumb like me screwing up the datapack file but I've checked it twice and still got no dice.

**Comment by Caltinor** [comment]
this is actually because I am not getting the curio items when calculating bonuses.  I seem to have overlooked that detail.  Thank you for bringing this to my attention.  it is nothing you did wrong, and I will get this fixed for the next update.
