### ISSUE TITLE
Server crashes when leveling up "Combat" while blocking

### ISSUE THREAD

**Issue by wipeoutsix** [Caltinor/Project-MMO-2.0#238]
**Describe the bug**
Every time a rank up of the "COMBAT" skill occurs whilst the player is actively blocking with a shield it will crash the server and create a server crash log. Issue was reproduce 100% with Skeletons, spiders and Zombies.

**Expected behavior**
Game doesn't crash when blocking upon ranking Combat skill.

**To Reproduce**
1. Create a game and give you a shield.
2. Spawn or locate a zombie.
3. Keep blocking and let the zombie attack you until you rank up combat.
4. Notice that the game crashes.

**Versions:**
 - Minecraft: 1.19.4
 - Loader: Forge 45.0.22
 - PMMO: 1.19.4-0.0.1

**Additional context**
I do use several other mods but it never crashed before installing this one when using the shield. In addition i can reproduce it 100% of the time.

[crash-2023-03-24_18.49.58-server.txt](https://github.com/Caltinor/Project-MMO-2.0/files/11067116/crash-2023-03-24_18.49.58-server.txt)

**Comment by Caltinor** [comment]
an updated version is being built right now and should be on CF/Modrinth in about 20min

**Comment by wipeoutsix** [comment]
Just downloaded the new file from CF and tried again, i was able to rank up at least 5 level without any issues. So far this bug is fixed on my end.
Thank you,
