### ISSUE TITLE
Minecraft 1.19.4 forge 45.0.27 wont load

### ISSUE THREAD

**Issue by krjencik** [Caltinor/Project-MMO-2.0#241]
**Describe the bug**
Describe exactly what you observed
Newer versions of forge than 45.0.23 causing this: (viz screenshot)

**Expected behavior**

**To Reproduce**

**Screenshots**
![pmmo crash](https://user-images.githubusercontent.com/92643141/228195927-24c9f2a9-acb8-418b-8c7c-f67589314989.png)

**Versions:**
 - Minecraft: (eg 1.18.2) 1.19.4
 - Loader: (eg. Forge-40.1.20) forge 45.0.27
 - PMMO: 1.18.2-0.0.1 1.19.4 0.0.2

**Additional context**
[latest.log](https://github.com/Caltinor/Project-MMO-2.0/files/11087857/latest.log)

**Comment by Caltinor** [comment]
Correct. 45.0.23 was a breaking change. Roll back to 45.0.22 until I can get an update released.

**Comment by krjencik** [comment]
ok..................

**Comment by Caltinor** [comment]
fixed via 8a8476590f2f0b9c1ad5b87edd99b132dbc84196
