### ISSUE TITLE
mapping error

### ISSUE THREAD

**Issue by Joyful25** [Caltinor/Project-MMO-2.0#244]
skill names are not displayed correctly in the mod, how to fix it
**Versions:**
 - Minecraft: ( 1.19.3)
 - Loader: (eg. Forge-44.1.23)
 - PMMO: 1.19.3-0.0.1

![2023-03-28_18-52-01](https://user-images.githubusercontent.com/47493635/228304271-5454f07d-129a-482a-8609-a483b954df26.png)
![2023-03-28_19-30-10](https://user-images.githubusercontent.com/47493635/228307245-e6cd7ffb-1846-4d92-a9a0-9b6802a320da.png)

**Comment by Caltinor** [comment]
it's an encoding error.  1.19.3 isn't supported though, so either update to 1.19.4 or downgrade to the latest 1.19.2.
