### ISSUE TITLE
1.18.2 - Woodcutting not working with Dynamic Trees

### ISSUE THREAD

**Issue by CoDroStyle** [Caltinor/Project-MMO-2.0#245]
**Describe the bug**
Woodcutting not working with dynamic trees. 
Complete cutting a tree, no woodcutting exp received.
Only seem to receive a small amount of woodcutting exp when placing wood blocks like chests and crafting table.

**Expected behavior**
Cutting a tree should receive exp

**Versions:**
forge-1.18.2-40.2.1
preview_OptiFine_1.18.2_HD_U_H9_pre2
pmmo-1.18.2-6.0.1
DynamicTrees-1.18.2-0.11.0-Beta8
physics-mod-2.11.11-mc-1.18.2-forge
Serene+Seasons-1.18.2-7.0.0.13

**Comment by Caltinor** [comment]
Dynamic trees requires manual settiings to give XP.  you can use `/pmmo genData` to create a datapack for you that has all the datapack files for the DT tree variants.  once you give them XP values, you should see XP when breaking DT trees.

**Comment by CoDroStyle** [comment]
> Dynamic trees requires manual settings to give XP. you can use `/pmmo genData` to create a datapack for you that has all the datapack files for the DT tree variants. once you give them XP values, you should see XP when breaking DT trees.

Thank you for your time responding. 

I have attempted to follow you instructions, the command does not appear to be working in 1.18.2
![gendata-error](https://user-images.githubusercontent.com/129404200/229269468-31590051-204d-40d8-8d46-c83da8a22410.png)

**Comment by SomewhatDamaged** [comment]
You will need to have OP privilege on a multiplayer server or have cheats enabled on singleplayer.
