### ISSUE TITLE
(1.16.5) Smelting Ores doesn't give Smithing XP

### ISSUE THREAD

**Issue by TheEffortFighter** [Caltinor/Project-MMO-2.0#250]
**Describe the bug**
When trying to smelt ores it doesn't give any smithing xp on output nor input.

**Expected behavior**
When it outputs ingots it gives the appropriate smithing xp.

**To Reproduce**
1. Put ore in a furnace
2. Smelt the ore
3. Wait for the output
4. See the error

**Versions:**
 - Minecraft: (1.16.5)
 - Loader: (Forge-36.2.39)
 - PMMO: 1.16.5-3.69.0

**Comment by TheEffortFighter** [comment]
I accidentally submitted it without finishing it, that's what all the editing and closing is for.

**Comment by XxInvictus** [comment]
Did you update from a previous version? Are they standard MC ores or a modpacks ores?

Particularly if you updated from a previous version you will need to update the configuration as per my post in the discord here - https://discord.com/channels/687007281539579927/806523935726108703/1081535499266699274

**Comment by TheEffortFighter** [comment]
At first I did, and then I did a fresh install on a vanilla pack. They were just regular vanilla ores, I'm checking your post right now.

**Comment by TheEffortFighter** [comment]
Alright, I did it, and it worked, may I ask that you post the discord info on curseforge or have new config types be placed alongside the old ones that no longer work to prevent this issue? I ask because this seems to have confused many others and they also weren't aware of the solution. Sorry if this does come off a bit rude.

**Comment by XxInvictus** [comment]
It was mentioned in the changelog that it changed to granting xp based on the output item I also have no control over the curseforge page. 

I would love to know where the heaps of people are getting confused by this? I regularly check in on the 1-16 support discord channel, there are no comments turned on in curseforge or modrinth, and the only other place is these github issues. In total, it MAY have come up twice, but realistically I think this is the only report I have seen of it.

**Comment by TheEffortFighter** [comment]
https://www.reddit.com/r/feedthebeast/comments/zfkyfm/rad2_how_do_i_level_up_smithing_been_trying_to/

Post is a few months old, but people thought you could only level up smithing from salvaging, and this is the only post I could find regarding smithing (there was a more relevant comment saying it required salvaging from 27 days ago). That's where I got the idea that people had no clue about the smithing and smelting part.
