### ISSUE TITLE
(1.16.5) Smithing incompatible with Redstone Furnace from Thermal Series mods

### ISSUE THREAD

**Issue by TheEffortFighter** [Caltinor/Project-MMO-2.0#251]
**Describe the bug**
Smelting ores in a Redstone furnace doesn't yield any smithing XP.

**Expected behavior**
Getting Smithing XP from smelting ores in a Redstone Furnace

**To Reproduce**
1. Put ores in a Redstone Furnace
2. Smelt ores
3. Get output
4. See the error

Minecraft: (1.16.5)
Loader: (Forge-36.2.39)
PMMO: 1.16.5-3.69.0

**Additional context**
I already reset the proper configs those being xp smelting and xp cooking, nothing works

**Comment by TheTaterLord** [comment]
Pretty sure the Redstone furnace doesn't firing off the correct events for smelting it's something on the mods end not pmmo, pmmo just listens for events being fired off and then acts based on that so if a block doesn't fire the event pmmo doesn't know that block is doing anything

**Comment by TheEffortFighter** [comment]
Ah, so this is a bug for redstone furnace, alright ill send one to them, if there's nothing you can do you can close this.

**Comment by TheEffortFighter** [comment]
They wanted me to ask what specific event you may be referring to

**Comment by TheTaterLord** [comment]
The same events a vanilla furnace fires off when it smells stuff

**Comment by Random832** [comment]
The FurnaceBurnEvent that you apparently use for this is not a vanilla or forge event, it's an event specific to this mod that you fire from your mixin at https://github.com/Caltinor/Project-MMO-2.0/blob/764585dce2431dc290fc4b1528518f4a49d883c1/src/main/java/harmonised/pmmo/mixin/AbstractFurnaceTileEntityShrinkMixin.java

While I agree that it would be nice to have an event here (and for non-interactive item processing in general), I don't think it's reasonable to suggest that other mods are at fault for not integrating with *your* API.

I also don't see why ItemCraftedEvent can't be used for this use case - as far as I can tell it is fired by the vanilla furnace when the user pulls an item from the result slot in the gui, but it doesn't look like you use this for smithing XP. It's hard to tell what exactly it is used for though.

**Comment by TheTaterLord** [comment]
Was that is the 1.19 or 1.16 branch because the mod got a full rewrite for 1.18 and 1.19 the 1.16 branch is housed on Harmonies GitHub if I remember correctly

**Comment by Caltinor** [comment]
> The FurnaceBurnEvent that you apparently use for this is not a vanilla or forge event, it's an event specific to this mod that you fire from your mixin at https://github.com/Caltinor/Project-MMO-2.0/blob/764585dce2431dc290fc4b1528518f4a49d883c1/src/main/java/harmonised/pmmo/mixin/AbstractFurnaceTileEntityShrinkMixin.java
> 
> While I agree that it would be nice to have an event here (and for non-interactive item processing in general), I don't think it's reasonable to suggest that other mods are at fault for not integrating with _your_ API.
> 
> I also don't see why ItemCraftedEvent can't be used for this use case - as far as I can tell it is fired by the vanilla furnace when the user pulls an item from the result slot in the gui, but it doesn't look like you use this for smithing XP. It's hard to tell what exactly it is used for though. EDIT: Actually for furnaces the event would be ItemSmeltedEvent, which you are definitely not using.

I am sorry that you were bothered about this. Pmmo tracks the player that placed a furnace so that when something is smelted and extracted by hoppers, the player still gets credit for the action. We do not use either event because of this hopper-extraction aspect. This is what the custom event in later versions is for. That said, 1.16 does not have this event and compat relies exclusively whether a furnace BE extends and calls the AbstractFurnace BE's burn method.   

Since that I know extending that class isn't practical in most situations it's not wise for us to ask for compat, so again. Sorry your team was bothered about this. 

@TheEffortFighter if you want smelting XP from pmmo, use the vanilla furnace or one that has chosen to explicitly add compat in their mod description.
