### ISSUE TITLE
Tailoring PMMO to a custom modpack for personal use

### ISSUE THREAD

**Issue by Z3bzonic** [Caltinor/Project-MMO-2.0#252]
**Describe what documentation needs updated or added:**
I tried the wiki entry for "items" and unpacked PMMO and added the following namespace or map.
pmmo-1.19-2.1.1\data\mekanismtools\pmmo\items
I have added most mekanism tools here based on a copy from minecraft items like iron_sword and started tweaking. Then I repacked and renamed it to jar but the client wont boot with customized PMMO mod. Exitcode 1

**Why is this documentation needed:**
It is well explained but something must be missing or assumed knowledge, can't get it to work.

**What medium is best for this documentation:**
Just the current wiki would do.

Just to be sure, here is an example json for the refined obsidian sword to make sure its not just me:

{
    "xp_values":{
        "ANVIL_REPAIR" :{
            "smithing": 4500
        },
        "CRAFT": {
            "crafting": 9000,
            "smithing": 900
        },
        "ENCHANT": {
            "magic": 1100
        }
    },
    "requirements":{
        "WEAR": {
            "combat": 95
        },
        "TOOL": {
            "farming": 20
        },
        "WEAPON": {
            "combat": 95
        }
    },
    "negative_effect":{
        "minecraft:weakness":3
    },
    "salvage":{
        "mekanism:ingot_refined_obsidian": {
            "salvageMax": 2,
            "baseChance": 0.0,
            "maxChance": 0.9,
            "chancePerLevel": {
                "smithing": 0.005
            },
            "levelReq": {
                "smithing": 5
            },
            "xpPerItem": {
                "smithing": 30
            }
        },
        "minecraft:stick": {
            "salvageMax": 1,
            "baseChance": 0.15,
            "maxChance": 1,
            "chancePerLevel": {
                "smithing": 0.05
            },
            "levelReq": {},
            "xpPerItem": {
                "smithing": 10
            }
        }
    }
}

Also sorry if this is the wrong place to ask/suggest.

**Comment by TheTaterLord** [comment]
Okay first things first don't edit the mod directly use the /pmmo gendata command and do it with a datapack editing the mod makes it hard for us to track the root cause of things

**Comment by Z3bzonic** [comment]
Oh ok thanks for that hint, I am unfamiliar with datapack but I will look
into both!


Op ma 3 apr 2023 om 22:47 schreef TheTaterLord ***@***.***>:

**Comment by Caltinor** [comment]
You issue is caused by your clients and server having different jars because of the editing.  Jars are compiled so unless you know what you are doing, opening a jar like a zip to edit will more often than not cause crashes.  

As for configuring the mod, do as TheTaterLord said and use the `/pmmo genData` command.  That will generate a datapack for you in `minecraft/saves/<yoursavename>/datapacks/` with all of the configuration files you will need.  The settings you used above can then be copied into these generated files.

**Comment by Caltinor** [comment]
Also, please update to a later version of pmmo.  2.1.1 is quite old and buggy.

**Comment by Z3bzonic** [comment]
thanks for bringing the obvious to my attention, makes sense it need
compilation.
I did the genData and after reloading the save all values are auto-filled
and pretty well done already.
It will reduce my tweaking time significantly!
Thank you :)

Op di 4 apr 2023 om 01:49 schreef Caltinor ***@***.***>:
