### ISSUE TITLE
(1.16.5) Iron Furnaces crashes the game when used with PMMO

### ISSUE THREAD

**Issue by TheEffortFighter** [Caltinor/Project-MMO-2.0#253]
**Describe the bug**
When any furnace from iron furnaces outputs ore after smelting it the game instantly crashes. This same bug also occurs with Better Furnaces Reforged.

**Expected behavior**
Iron furnaces successfully smelting ore without crashing the game

**To Reproduce**
1. Smelt ore in an iron furnace
2. Wait for the output
3. Game crashes

**Versions:**
Minecraft: (1.16.5)
Loader: (Forge-36.2.39)
PMMO: 1.16.5-3.69.0

**Additional context**
This is after I already fixed the smelt xp configs and the only mods in the pack are iron furnace and pmmo.

**Comment by SomewhatDamaged** [comment]
Tested and verified this crashed with clean build.

Crashlog: https://pastebin.com/4dWTMNbG

**Comment by YassaaaTU** [comment]
Well same thing happened to me, and I am on 1.18.2. I was cooking some meat in an iron furnace and all of a sudden server crash.

**Comment by Caltinor** [comment]
There is no reference to PMMO in this crash log.  In fact all of the errors point to `ForgeWrapper` and MultiMC.  I would check your launcher for issues.  This is not a PMMO problem.

**Comment by SomewhatDamaged** [comment]
Gah, sorry about that. I am not sure what that crash log was/is from. Updated the paste with the correct one.
