### ISSUE TITLE
1.19.4 incompatibility with mods that spawn you in

### ISSUE THREAD

**Issue by DragonInsight** [Caltinor/Project-MMO-2.0#254]
**Describe the bug**
basically any mod that alters the spawning of the player makes the mod unable to load.
**Expected behavior**
the game is unable to load at all

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/97200352/229910625-3aa12d5b-a814-4271-8efc-d5a111465a97.png)

**Versions:**
 - Minecraft: (eg 1.19.4)
 - Loader: (eg. Forge-40.1.20)
 - PMMO: 1..19.4-0.0.2

**Additional context**

**Comment by Caltinor** [comment]
This is caused by a breaking change Forge made with 45.0.23. Roll forge back to 45.0.22 to resolve the issue until a new version of pmmo is released.
