### ISSUE TITLE
Individual Skill Names are not displayed in the GUI

### ISSUE THREAD

**Issue by klugemonkey** [Caltinor/Project-MMO-2.0#255]
**Describe the bug**
Not able to discern what each skill is in the GUI since only says Knowledge and doesn't show Skill description from json file.

**Expected behavior**
Displaying the localized Skill Name in the GUI from the json file rather than just Knowledge.

**To Reproduce**
Install mod, no config files, defaults.

**Screenshots**
![image](https://user-images.githubusercontent.com/3101426/230547551-d8576266-9a2a-49e3-96f5-71d9cb1e3778.png)
![image](https://user-images.githubusercontent.com/3101426/230547729-16025c16-205a-4387-ad02-42291fd6ade5.png)

**Versions:**
 - Minecraft: 1.18.2
 - Loader: Forge-40.1.20
 - PMMO: 1.18.2-6.0.3

**Additional context**
Surely this is a usability bug and not by design.

**Comment by SomewhatDamaged** [comment]
That is all configured by the specific modpack you are using. You will need to contact them for support.

**Comment by klugemonkey** [comment]
So, you are basically saying the default is to display "Knowledge" and that I have to put base strings into the datapack in order for this mod to display something meaningful because it is not reading the default pmmo.xxx  lang assets in the actual mod jar.

**Comment by klugemonkey** [comment]
or that they might not even exist in the jar language assets for the default skills that are created by the pre-generated configuration files that modpack developers would use to start with.

**Comment by SomewhatDamaged** [comment]
The knowledge skills are not part of the default PMMO skills set. They are added by the [Dawncraft modpack](https://www.curseforge.com/minecraft/modpacks/dawn-craft). They use a version of the mod that is no longer being actively developed as a back-end method of storing quest progress.

**Comment by klugemonkey** [comment]
Ah, thank you so much!  That was the problem, they coded the strings into their resource pack and renamed them all to Knowledge, which was strange since they are not even using the GUI.  If I remove I should at least get the pmmo.agility or whatever the base skill name is.  I thought just removing the configs would reset PMMO back to some baseline.  OK, I got this now.

**Comment by SomewhatDamaged** [comment]
No problems!
