### ISSUE TITLE
Crash with abnormal Equipment Slots (OFFHAND in this case)

### ISSUE THREAD

**Issue by YesVRC** [Caltinor/Project-MMO-2.0#256]
**Describe the bug**
Client Render Crash with Equipment Type OFFHAND

**Expected behavior**
Not a crash?

**To Reproduce**
1. Install both Goblins and Dungeons and PMMO in a fresh 1.18.2 forge
2. Hover over any of goblin's rings
3. Game crashes

**Versions:**
 - Minecraft: (eg 1.18.2)
 - Loader: (eg. Forge-40.2.1)
 - PMMO: 1.18.2-6.0.3

**Additional context**
Crash is related to AutoValueConfig.getWearableAttribute(AutoValueConfig.java:287)
Code for the ring I have crashes on [is here](https://github.com/superlord9362/GoblinsAndDungeons/blob/1.18/src/main/java/superlord/goblinsanddungeons/common/item/StealthRingItem.java)

[Crash Report](https://github.com/Caltinor/Project-MMO-2.0/files/11182831/crash-2023-04-08_04.24.08-client.txt)

**Comment by Caltinor** [comment]
This mod specifically breaks the autovalues.  This pack will keep your game from crashing.  I'll get this into the core mod on the next update.
[GnDxPMMO compat.zip](https://github.com/Caltinor/Project-MMO-2.0/files/11182985/GnDxPMMO.compat.zip)

**Comment by YesVRC** [comment]
Huge thanks for the quick response!
Much appreciated and have a great day.
