### ISSUE TITLE
Mod restrictions.

### ISSUE THREAD

**Issue by jniubyiy** [Caltinor/Project-MMO-2.0#266]
Adding a separate mod setting to disable restrictions on the use of tools.

For more convenience, using the mod and for convenient combination with other mods in modpacks. For example, when installing mods to make the game easier as opposed to the functions of facilitating the game of this mod, which makes it not very convenient to play because the mod itself already has limitations in contrast to its limitations of the game.

Remove the restrictions from the mod that it warns or create a separate addon for the mod in which these restrictions will be.

**Comment by TheTaterLord** [comment]
You can already remove the restrictions by using the disabler pack and turning off auto values the gendata command can make this disabler pack for you

**Comment by Caltinor** [comment]
@jniubyiy you can disable requirements in `pmmo-server.toml` there is a section for each type of restriction so that you can disable what you want.  If you want to only disable specific restrictions on specific items, you can do that with a datapack.

**Comment by jniubyiy** [comment]
Thanks for the answer, I didn't know that it was possible.
