### ISSUE TITLE
oh the biomes you go compatibility

### ISSUE THREAD

**Issue by kaserv** [Caltinor/Project-MMO-2.0#267]
**Describe the solution you'd like**
the mod does not count obyg blocks so you can obtain xp by broking them, i know there are many blocks in this mod, but ithem would be good for it to actually work together

**Why is this feature needed**
in case more people tries to play the mods together

**Describe alternatives you've considered**
adding a list of block(classified in type of blocks(like dirt blocks, stone blocks, ore blocks)) or a list of mods for the mod
 to allow the required blocks

**Additional context**

**Comment by Caltinor** [comment]
versions?  pmmo, forge, and minecraft please

**Comment by kaserv** [comment]
Minecraft 1.19.2
Forge 43.2.0
Pmmo 1.19.2-3.0.5
Oh the biomes you'll go 1.19.2-2.0.0.13

**Comment by Caltinor** [comment]
Okay.  now what exactly is your issue?  What you wrote above doesn't make any sense.

**Comment by TheTaterLord** [comment]
Sounds like they want all the OBYG blocks and items to automatically have values assigned

**Comment by Caltinor** [comment]
Fresh instance with pmmo 3.0.5 forge 43.2.8 and BYG 2.0.0.13.  colored sand gave me excavation and this big stem tree gave me woodcutting.  This is a configuration issue on the user end.  
![image](https://user-images.githubusercontent.com/62700786/236567934-c601e3ad-e368-4187-895d-e2833105b37f.png)
