### ISSUE TITLE
Shearing Sheep XP

### ISSUE THREAD

**Issue by Tyrius1** [Caltinor/Project-MMO-2.0#27]
**Describe the solution you'd like**
The goal would be to give players xp when they shear a sheep but not xp just from holding right click on the sheep

**Why is this feature needed**
Not really needed or all that important. Just a kool feature that could be fun.

**Describe alternatives you've considered**
I tried ENTITY as xp gain but with that route you can just hold right click on sheep and watch xp rise 😄

**Comment by Caltinor** [comment]
:thinking: I do like the idea, but the implementation and configuration prove tricky.  The first obstacle is do you make it an item event or an entity event, or an item-use-on-entity event.  If the latter you still have the configuration challenge of how to specify the item and/or entity in question.  You can have the item have the configuration, but then you need some way to configure what entities get what experience from that interaction, and vice versa for items used on an entity.  

I am willing to implement this idea if someone can provide the following:
1. a comprehensive list of vanilla and modded cases demonstrating this is not a single-case feature
2. a reasonable configuration mechanic that doesn't violate or overly complicate any existing configuration schemas.

**Comment by Caltinor** [comment]
In the absence of a compelling case, and am closing this issue.  It may be reopened if such examples are brought forth.
