### ISSUE TITLE
Some things aren't visible in Glossary

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#270]
**Describe the bug**
When trying to view extra wide data in the Glossary (like mob scaling), it just doesn't fit in. See screenshot.

**Expected behavior**
The glossary is wide enough to show this data.

**To Reproduce**
1. Press P
2. Click on Glossary
3. Select Mob Scaling and by dimension
4. See screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/6394544/234070311-4f707e62-0f9d-4e18-aeb6-e8b19236ed57.png)

**Versions:**
 - Minecraft: 1.19.2
 - Loader: Forge-43.2.4
 - PMMO: 1.19.2-3.0.5

**Additional context**
Even scaling the GUI doesn't help.

**Comment by Caltinor** [comment]
The actual text wrapping feature was implemented as part of a GUI rewrite in the 1.20 alphas.  Since I can't backport that easily, this fix simply includes a translation of the attributes which is significantly smaller than the full IDs.
