### ISSUE TITLE
Can't turn off the armor debuff 

### ISSUE THREAD

**Issue by BadNerdCreating** [Caltinor/Project-MMO-2.0#272]
**Describe the bug**
I changed the setting for weapon req tooltip enabled to false both in the in-game config and the config file in the minecraft appdata file and it doesn't change. 

**Expected behavior**
I expected to no longer have the armor debuff 

**To Reproduce**
1. change config file to false 
2. continue to get debuff

**Versions:**
 - Minecraft: (eg 1.19.2)
 - Loader: (eg. Forge-43.2.0)
 - PMMO: 1.19.2-3.0.5

**Additional context**
i also have tough as  nail mod and i'm trying to wear the leaf armor but it always has the debuff and thats what i'm trying to turn off. 

thank you for your help!

**Comment by Caltinor** [comment]
`pmmo-client.toml` only affects visual things. You need to go into `pmmo-server.toml` and set `WEAR Req Enabled = false`

**Comment by BadNerdCreating** [comment]
> `pmmo-client.toml` only affects visual things. You need to go into `pmmo-server.toml` and set `WEAR Req Enabled = false`

Thank you. That makes sense. How do I get to the server config?

**Comment by SomewhatDamaged** [comment]
Single Player: `minecraft/saves/<save name>/serverconfig/pmmo-server.toml`

Server: `minecraft/<world name>/serverconfig/pmmo-server.toml`

**Comment by BadNerdCreating** [comment]
> Single Player: `minecraft/saves/<save name>/serverconfig/pmmo-server.toml`
> 
> Server: `minecraft/<world name>/serverconfig/pmmo-server.toml`

Thank you! 

And for anyone else that has this issue in the future. I had to stop the server. Edit the file. Start the server. Otherwise it just kept rewriting the file back to true.
