### ISSUE TITLE
"isTagFor" to support wildcards

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#273]
**Describe what this tool does, conceptually:**  (not the how, just the outputs)
The `isTagFor` datapack tag would be great if it supported either wildcards or assumed wildcards. 

Ex:
```JSON
{
  "xp_values": {
    "CRAFT": {"crafting": 0},
    "BLOCK_PLACE": {"building": 0},
    "ENTITY": {"charisma": 0}
  },
  "override": true,
  "isTagFor": ["minecraft:*"]
}
```

**Describe how current configuration methods are insufficient for the task:**
If you want something to affect _all_ items from a mod/set of mods, it can be a lot of work.

**What platform would you like to see this tool on:**
In-game.

**Comment by Caltinor** [comment]
It does though?  Unless it broke.

**Comment by SomewhatDamaged** [comment]
I tried it and wasn't getting it to work. Would it be failing if any of the potential items (enchantments, etc) aren't compatible with those settings?
