### ISSUE TITLE
1.19.4 

### ISSUE THREAD

**Issue by Aetrnl94** [Caltinor/Project-MMO-2.0#275]
**Describe the solution you'd like**
Is there any chance that this mod is compatible with 1.19.4? I want to try it out as it looks amazing, but I'm not sure if it'll crash/corrupt my save.

**Why is this feature needed**
I only play 1.19.4, and I don't want to install this mod if it's not compatible.

**Describe alternatives you've considered**
I guess not installing the mod?

**Additional context**
N/A

**Comment by SomewhatDamaged** [comment]
There is an Alpha version for 1.19.4

It is ***Alpha***, but so far has proven to be reasonably stable. There are no plans for a non-Alpha build for that version of Minecraft, however.

[CurseForge](https://www.curseforge.com/minecraft/mc-mods/project-mmo/files/4481370)

[Modrinth](https://modrinth.com/mod/project-mmo/version/1.19.4-0.0.3)

**Comment by Aetrnl94** [comment]
Great, I'll try it out!
