### ISSUE TITLE
Integration tool for other mods

### ISSUE THREAD

**Issue by Daarkie** [Caltinor/Project-MMO-2.0#282]
When user has too many mods in their modpack (been there, done that) it's great they can generate resources by using the command ingame - but it can be a pain to rewrite them all. Solution would be some type of config based rewriter for PMMO that literally just rewrites all items, blocks, etc.. in correct format with correct information.

It should probably be side project.

It may sound like a hell lot of extra work, but I spent last three days working on simple version of this and am almost done. I will soon update on GitHub and don't really care for using it further than my project... So if you'd like I can link that somewhere or something.
![Capture](https://user-images.githubusercontent.com/51191496/236758638-c7cf89d4-c925-4e6e-a9c0-883b53ed8058.PNG)
![Capture00](https://user-images.githubusercontent.com/51191496/236758641-c6728cb6-9b49-4cde-8d9c-a9fe9268892c.PNG)

Have a nice day :)

**Comment by Caltinor** [comment]
If I understand this correctly, you are looking-for/building a tool that allows users to script configurations in order to automate certain aspects of the datapack creation?
