### ISSUE TITLE
Interaction between PMMO and Ars Magica Legacy causes crash

### ISSUE THREAD

**Issue by ElasticKnife** [Caltinor/Project-MMO-2.0#285]
**Describe the bug**
When filtering items in the glossary with Ars Magica Legacy installed, I encountered a crash.

**Expected behavior**
I have not played around much with PMMO, hence why I was fiddling with it, but I assume it should bring up a list of all the available mining tools with level requirements.

**To Reproduce**
1. Hit P
2. Open Glossary
3. I selected the filters Requirements, Items, Mining, Use as Tool
4. Hit View Info
5. [Crash](https://bytebin.lucko.me/HloygEs5ll)

**Screenshots**
![2023-05-11_10 09 54](https://github.com/Caltinor/Project-MMO-2.0/assets/20340284/a66f375a-9ac4-4c2c-a34d-f0f2dd9d8001)
![2023-05-11_10 10 14](https://github.com/Caltinor/Project-MMO-2.0/assets/20340284/f9c62411-17bb-4ce0-b8d7-d1bbf0aa28e4)

**Versions:**
 - Minecraft: 1.18.2
 - Loader: Forge-40.2.2
 - PMMO: 1.18.2-6.1.0

**Additional context**
arsmagicalegacy-1.18.2-1.2.4
[https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/issues/390#issuecomment-1544175963](https://github.com/MinecraftschurliMods/Ars-Magica-Legacy/issues/390#issuecomment-1544175963)

**Comment by Caltinor** [comment]
So, following [IchHabeHunger54](https://github.com/IchHabeHunger54)'s suggestion, I was able to get the glossary to use the creative tab instances.  This had the added benefit of now displaying all of the potion variants as well as the enchantment variants.    Thank you for reporting this.  I am hoping to have an update tomorrow evening.
