### ISSUE TITLE
Riding Experience Broken 2: Electric Boogaloo

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#286]
**Describe the bug**
Latest build for 1.18.2 1.19.2 and 1.19.4 all have riding experience broken.

Horse riding gives no `Ride` skill experience.
Boat riding gives just over 2 levels of `Sailing` experience, then no more.

**Expected behavior**
`Riding` and `Sailing` experience from those actions should give continual experience.

**To Reproduce**
1. Make new game instance (fresh)
2. Add latest Forge and PMMO
3. Give self boat
or
3. Give self horse egg, 64 apples, and saddle
4. Tame horse, fit saddle
5. See error

**Versions:**
As stated in description.

**Additional context**
My cat's breath smells like cat food.

**Comment by SomewhatDamaged** [comment]
Tested 1.19.4 with Anti-Cheese on Riding set to `0.00` and I once again got experience.

**Comment by Caltinor** [comment]
Note to self, drastically dial back the default anti-cheese thesholds.

**Comment by Caltinor** [comment]
After testing, this is working exactly as intended.  RIDE xp (which boats and horses are both awarding for) has a retention value of 200 ticks.  if you sit in a boat until you stop getting xp, then hop out and wait for 10+ seconds and re-enter the boat, you will see your XP restored to original values.
