### ISSUE TITLE
[1.20] Dig Speed Bonus Too High

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#295]
**Describe the bug**
Digging, with 0-10 levels of skill is approximately 2-3x faster than vanilla.

**Expected behavior**
At such low levels there shouldn't be any noticeable speed increase.

**To Reproduce**
1. Load 1.20 with PMMO and defaults
2. Give self a wooden shovel
3. Ensure skills are cleared
4. Dig!

**Screenshots**

https://github.com/Caltinor/Project-MMO-2.0/assets/6394544/b6ac60ae-aec3-4ea1-9afe-e9399eb3323b

**Versions:**
 - Minecraft: 1.20
 - Loader: Forge-46.0.12
 - PMMO: 1.20-0.0.1

**Additional context**
Not sure about other skills.

**Comment by krjencik** [comment]
this occurs also with pickaxe

**Comment by SomewhatDamaged** [comment]
> this occurs also with pickaxe

Thanks!

-----

Tested PMMO 1.19.2-3.1.1 and it has the correct dig speed.

Hooray for new version bugs!

**Comment by SomewhatDamaged** [comment]
Also affects 1.19.4-0.0.5
