### ISSUE TITLE
[1.18.2] [1.19.2] [1.20] Cooking on a Campfire Gives No XP

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#296]
**Describe the bug**
Cooking food on a campfire gives no cooking XP

**Expected behavior**
Like cooking in a furnace, cooking food on a campfire you yourself placed should give cooking XP.

**To Reproduce**
1. Start new game
2. `/give` yourself a campfire and 4 raw porkchops
3. Place campfire and put porkchops on
4. After a while, get cooked porkchops but no cooking XP

**Versions:**
 - Minecraft: 1.18.2 1.19.2 1.20
 - Loader: Latest for each
 - PMMO: Latest for each

**Comment by Caltinor** [comment]
This was actually never a feature.  Adding it would be an extra mixin.  I'll consider if this is worth implementing
