### ISSUE TITLE
ModernFix and PMMO

### ISSUE THREAD

**Issue by Orangejewce92** [Caltinor/Project-MMO-2.0#302]
**Describe the bug**
i get hung up on loading pmmo data with this mod installed. 
ModernFix https://www.curseforge.com/minecraft/mc-mods/modernfix

Modernfix is an absolute must with the server/modpack makes everything run 1000xbetter.

**Expected behavior**
Unsure if its the "main" issue but the mods do not work together once someone has entered a different dimension "in this instances it
was blue_skies Everdawn dim"
The crash report is stating some pmmo get data storage.dimensionstoragedata. something along those lines.

**To Reproduce**

**Screenshots**

**Versions:**
 - Minecraft:  1.18.2
 - Loader: (eg. Forge-40.2.9
 - PMMO: 1.18.2-6.1.1

**Additional context**
crash report: [https://pastebin.com/C0NCC530](url)

**Comment by Orangejewce92** [comment]
unsure as well, but my pmmo.dat is at 120mbs unsure if this was mentioned or not? but it uses a lot of ram for servers. fresh data 2-4 gbs of ram. currently 11-14gbs of ram

**Comment by Orangejewce92** [comment]
Modernfix does have a config:

#These JEI plugins will be loaded on the main thread
blacklist_async_jei_plugins = ["jepb:jei_plugin"]

i'm curious if i could add pmmo to this line but unsure what i would "put"

**Comment by Orangejewce92** [comment]
as well as this:

# This is the configuration file for ModernFix.
#
# The following options can be enabled or disabled if there is a compatibility issue.
# Add a line mixin.example_name=true/false without the # sign to enable/disable a rule.
#  mixin.bugfix
#  mixin.bugfix.chunk_deadlock
#  mixin.bugfix.concurrency
#  mixin.bugfix.ctm_resourceutil_cme
#  mixin.bugfix.packet_leak
#  mixin.bugfix.paper_chunk_patches
#  mixin.devenv
#  mixin.feature
#  mixin.feature.branding
#  mixin.feature.direct_stack_trace
#  mixin.feature.integrated_server_watchdog
#  mixin.feature.measure_time
#  mixin.feature.snapshot_easter_egg
#  mixin.feature.spam_thread_dump
#  mixin.launch.class_search_cache
#  mixin.perf
#  mixin.perf.blast_search_trees
#  mixin.perf.cache_blockstate_cache_arrays
#  mixin.perf.cache_model_materials
#  mixin.perf.cache_strongholds
#  mixin.perf.cache_upgraded_structures
#  mixin.perf.clear_mixin_classinfo
#  mixin.perf.compact_bit_storage
#  mixin.perf.compress_blockstate
#  mixin.perf.datapack_reload_exceptions
#  mixin.perf.dedicated_reload_executor
#  mixin.perf.deduplicate_location
#  mixin.perf.dynamic_dfu
#  mixin.perf.dynamic_entity_renderers
#  mixin.perf.dynamic_resources
#  mixin.perf.dynamic_resources.ae2
#  mixin.perf.dynamic_resources.ctm
#  mixin.perf.dynamic_resources.rs
#  mixin.perf.dynamic_resources.supermartijncore
#  mixin.perf.dynamic_structure_manager
#  mixin.perf.fast_registry_validation
#  mixin.perf.faster_advancements
#  mixin.perf.faster_font_loading
#  mixin.perf.faster_item_rendering
#  mixin.perf.faster_texture_loading
#  mixin.perf.faster_texture_stitching
#  mixin.perf.kubejs
#  mixin.perf.model_optimizations
#  mixin.perf.nbt_memory_usage
#  mixin.perf.patchouli_deduplicate_books
#  mixin.perf.reduce_blockstate_cache_rebuilds
#  mixin.perf.remove_biome_temperature_cache
#  mixin.perf.remove_spawn_chunks
#  mixin.perf.resourcepacks
#  mixin.perf.rewrite_registry
#  mixin.perf.state_definition_construct
#  mixin.perf.thread_priorities
#  mixin.safety

**Comment by Orangejewce92** [comment]
is there a mixin that needs to be added to this? i appreciate the help and i apologize for all the dump here.

**Comment by Caltinor** [comment]
try `#  mixin.perf.nbt_memory_usage` this one.  disable that and see if you get the same crash.

**Comment by Orangejewce92** [comment]
Trying now

**Comment by Orangejewce92** [comment]
Could be a coincidence, because I did disable the mod so I could get the server running, until you had time to look. But re-enabling the mod with this added mixin server has started ! I did 3 back to back restarts. I will do some further testing. Thanks for the quick response

**Comment by Caltinor** [comment]
My best guess is that the mixin's canonicalization (guessing from the stacktrace method names) is not playing nicely with my custom `PrimitiveCodec` to parse UUIDs to and from strings.

**Comment by Orangejewce92** [comment]
Sent crash report with added mixin. Unfortunately hung up again on pmmo load data.

**Comment by Caltinor** [comment]
This was resolved via DM.
