### ISSUE TITLE
Tetra Tools Don't Vein Mine

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#304]
**Describe the bug**
Using a Tetra tool to break marked vein mining block doesn't trigger vein mining.

**Expected behavior**
Mining a block with a Tetra pickaxe (for example) that has been marked for vein mining should trigger the vein mining.

**To Reproduce**
1. Equip something in offhand that has vein mining stats
2. Equip Tetra pickaxe in right hand
3. Mark a block for vein mining
4. Break block

**Versions:**
 - Minecraft: 1.19.2
 - Loader: Forge-43.2.11
 - PMMO: 1.19.2-3.1.1

**Comment by SomewhatDamaged** [comment]
Still doesn't seem to work.

Contacted the Tetra dev, who replied: https://github.com/mickelus/tetra/issues/727

**Comment by AngellusMortis** [comment]
Can confirm, definitely still broken in 1.19.2.
