### ISSUE TITLE
Vein Mining Whitelist

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#305]
**Describe the solution you'd like**
A way to specify a whitelist (or perhaps a property that can be set in datapack files) that specifically allows veinmining of a block despite not having the correct tool for it.

**Why is this feature needed**
Wool and carpet are the main two I can think of off the top of my head that could really use this, but given there _is_ a blacklist, why not a whitelist too?

**Describe alternatives you've considered**
Punching wool. Punching lots of wool.

**Additional context**
It would allow more flexibility for what can be easily vein mined.

**Comment by Caltinor** [comment]
I think having a failsafe for items that don't require tools to drop is a better approach.  i'll make that an improvement on the next update.
