### ISSUE TITLE
[1.19.2] Salvage Showing "[air]" On Items

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#319]
**Describe the bug**
When crouching and looking at a smithing table with an item in one hand (tested with iron chestplate), it shows `[air]` as one of the salvageable items.

**Expected behavior**
Only show items that are meant to be salvaged.

**To Reproduce**
1. Fresh install
2. Give yourself 30 smithing skill
3. Give yourself `minecraft:iron_chestplate`

**Screenshots**
![image](https://github.com/Caltinor/Project-MMO-2.0/assets/6394544/4ac93fb3-fffc-4d14-89da-901bda03a6ee)

**Versions:**
 - Minecraft: 1.19.2
 - Loader: Forge-43.2.11
 - PMMO: 1.19.2-3.1.2

**Additional context**
My cat's name is Mittens.

**Comment by SomewhatDamaged** [comment]
Note: this is caused by having a generated datapack that includes `[air]` as a salvageable item.

**Comment by Caltinor** [comment]
ah, it's combining the salvage from both items.  I'll add a catch for mis/non-configured salvage outputs.
