### ISSUE TITLE
Perk To Add Enchantment Effects

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#321]
**Describe the solution you'd like**
A perk that lets you apply enchantment effects to the player as if wearing an item that has that enchantment.

**Why is this feature needed**
It would allow things like Resperation enchantments for more fine-tuned Swimming bonuses, or Looting from Combat, etc.

**Describe alternatives you've considered**
Not having them.

**Additional context**
Would be nice if you could set the level of the enchantment effect too.

**Comment by Caltinor** [comment]
After investigating this, it would require a metric ton of mixins.  Alternatively, perks could be created that mimic the behavior, but that would be a lot of work and might require more mixins.  I don't think this makes sense for PMMO at this time.
