### ISSUE TITLE
[1.19.4] Mining Speed Super Slow

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#327]
**Describe the bug**
Despite using a diamond pickaxe and having 100 mining and 60 combat (all skills met), mining is as slow as using a bare fist.

**Expected behavior**
Mining should be faster than normal.

**To Reproduce**
1. Create new world with latest PMMO for 1.19.4
2. Set `mining` to 100 and `combat` to 60
3. Give self a diamond pick
4. _Sloooooooow_ mining

**Screenshots**

https://github.com/Caltinor/Project-MMO-2.0/assets/6394544/71789d97-2255-44f1-9e11-9f956b9c7c7c

**Versions:**
 - Minecraft: 1.19.4
 - Loader: Forge-45.1.14
 - PMMO: 1.19.4-0.0.7

**Additional context**
Addition is one of the four basic operations of arithmetic. The addition of two whole numbers results in the total amount or sum of those values combined.

**Comment by TheTaterLord** [comment]
also happens with Axes as well as Picks
