### ISSUE TITLE
Kelp doesn't give growing XP

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#328]
**Describe the bug**
Player-planted kelp doesn't give any XP as it grows new sections.

**Expected behavior**
Should receive the `Growth XP` value of kelp when new sections grow.

**To Reproduce**
1. Plant kelp
2. Watch it grow
3. Feel the emptiness inside

**Versions:**
 - Minecraft: Seems to affect all versions (tested on 1.19.2 and 1.20.1)
 - PMMO: Latest for each tested.

**Additional context**
My basil plant in my kitchen doesn't give farming XP either, but I can't find a repository to report that to.

**Comment by Caltinor** [comment]
So this is interesting.  Sugar cane grows from the top block.  Meaning if you can visualize the age of the block, you can see when it's going to grow next based on the top block.  Kelp, however, always manages growth from the bottom.  I suspect the issue with kelp not giving XP has to do with how i track growth which expects a bamboo or sugar cane style of growth.

**Comment by Caltinor** [comment]
I'm going to close this as not implemented.  The change to make it work would be too invasive for such a unique use case.
