### ISSUE TITLE
[Data] Breaking Seagrass Gives Mining XP

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#329]
**Describe the bug**
Break seagrass, get 1 mining XP

**Expected behavior**
Should get farming XP.

**To Reproduce**
1. Touch (sea)grass
2. Get 1 `mining` XP

**Versions:**
 - Minecraft: Tested on 1.20.1
 - Loader: Forge-47.1.0
 - PMMO: 1.20.1-0.0.2

**Comment by Caltinor** [comment]
I don't think seagrass was added to default data, so this is just AutoValues doing what they should do.  I'll add a default seagrass XP.
