### ISSUE TITLE
[1.20.1] Curios Slots Not Counting as `WORN`

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#330]
**Describe the bug**
Adding an XP bonus to an item that goes in a curio slot as `WORN` doesn't give bonus.

**Expected behavior**
An item in a curio slot should give an assigned XP bonus under the `WORN` action.

**To Reproduce**
1. Install Sophisticated Backpacks
2. Create datapack, give backpack:
```JSON
  "bonuses": {
    "WORN": {"endurance": 1.50}
  }
```
3. Put backpack on
4. Get no bonus

**Versions:**
 - Minecraft: 1.20.1
 - Loader: Forge-47.1.0
 - PMMO: 1.20.1-0.0.3

**Comment by Caltinor** [comment]
This is due to Curios compat not yet being readded post-port.  I will reintroduce it in the next update.
