### ISSUE TITLE
Server Crashes when configuring pmmo-server.toml 1.19.2

### ISSUE THREAD

**Issue by JustMatteh** [Caltinor/Project-MMO-2.0#333]
**Describe the bug**
Configured the file pmmo-server.toml found inside the world folder and suddenly crashed giving out that log. 
On my server i first put it on the defaultconfig folder, had this issue, tried with a fresh config and it worked.

**Expected behavior**
To start properly (Yes because it started on client with and without configurations)

**To Reproduce**
1. Configure pmmo-server.toml
2. Start Server
3. Error occurs

**Versions:**
 - Minecraft: 1.19.2
 - Loader: Forge-43.2.21
 - pmmo-1.19.2-3.1.3

**Additional context**

[pmmo-server.txt](https://github.com/Caltinor/Project-MMO-2.0/files/12152510/pmmo-server.txt)
[latest.txt](https://github.com/Caltinor/Project-MMO-2.0/files/12152511/latest.txt)

**Comment by Caltinor** [comment]
This crash occurs when you make a syntax error or alter the format of the config. Delete your config, and let a new one regenerate. 

What setting were you trying to change?

**Comment by JustMatteh** [comment]
Unfortunately i did nothing else than change the salvage block to "minecraft:barrier" , make all the options in [Requirements] tab as false and vein mining as false.

**Comment by Caltinor** [comment]
I would still delete the config, and let a new one generate, then change one thing at a time.  The error doesn't give enough information to isolate exactly what is causing the config to fail to load.

**Comment by JustMatteh** [comment]
Understood, will make further investigation.

**Comment by JustMatteh** [comment]
I've just ran some tests by changing the values progressively and it worked. I have no clue what has happened to the previous files I tried but they must have corrupted (which is absurd but can happen i guess...) and after a restart it just worked as if nothing happened... Im sorry that my issue took your time for nothing.

**Comment by SomewhatDamaged** [comment]
I don't suppose you're using CreeperHost to run a server on?

**Comment by JustMatteh** [comment]
No, didnt even know creeperhost before actually, I usually run servers for my friends and I on my machine. All the tests i've done done on a localhost server.
