### ISSUE TITLE
combat level always uses base minecraft unarmed damage when buffing

### ISSUE THREAD

**Issue by Terrablade04** [Caltinor/Project-MMO-2.0#334]
**Describe the bug**
unarmed damage when buffed by another mod ,specifically mine mine no mi in my case, does not get the new value buffed by combat level rather the base minecraft unarmed damage gets the buff making the damage difference almost unnoticeable 

**Expected behavior**
combat level damage buff to multiply the damage after being buffed by another mod for example if base unarmed with the mod is 20 than a 100% buff from combat would make that 40 rather than 21 which is buffing vanilla damage.

**To Reproduce**
download another mod that can buff unarmed damage in this specific case mine mine no mi, get unarmed damage buffed from this mod, buff damage through combat level from pmmo, hit something.

**Screenshots**

**Versions:**
 - Minecraft: 1.16.5
 - Loader: forge 1.16.5 36.2.34
 - PMMO: 1.16.5, 3.69.0

**Additional context**

**Comment by Caltinor** [comment]
You can make it multiply though.  The attribute perk has a property `multiplicative = true` .  it defaults to false, so set that and you should get what you want.
