### ISSUE TITLE
[Farmer's Delight] Consume XP incompatability

### ISSUE THREAD

**Issue by Elaski6573** [Caltinor/Project-MMO-2.0#337]
**Describe the bug**
Some of Items witch is drankable doesn't give experience when they used.

**Expected behavior**
make a new tag to define consumable or not.

**To Reproduce**
1. Add XP Value
![image](https://github.com/Caltinor/Project-MMO-2.0/assets/114150904/6a87c1b0-e5f0-4d69-8a88-833cb9759fdf)
2. Consume This Item
3. Experience doesn't increased

**Screenshots**
![ezgif com-video-to-gif](https://github.com/Caltinor/Project-MMO-2.0/assets/114150904/85aec743-4db9-47f3-98fa-f27a8f60866e)

**Versions:**
 - Minecraft : 1.19.2
 - Loader : 43.2.21
 - PMMO: 1.19.2-3.1.3

**Comment by SomewhatDamaged** [comment]
Just adding some info to make this easier to triage.
I have tested and can confirm this with:
* Minecraft: 1.19.2
* Forge: 43.2.14
* PMMO: 1.19.2-3.1.3
* [Farmers Delight: 1.19.2-1.2.2](https://github.com/vectorwing/FarmersDelight)

Using the following datapack:
[melon_drink_test.zip](https://github.com/Caltinor/Project-MMO-2.0/files/12206617/melon_drink_test.zip)

**Comment by Elaski6573** [comment]
I tried your datapack but it doesn't work.

I think there is different logic when using potions.
Food Items are defined by [EatFoodEvent.java](https://github.com/Caltinor/Project-MMO-2.0/blob/main/src/main/java/harmonised/pmmo/api/events/EatFoodEvent.java#L8) but I cannot find potions.
Am I missing something?

**Comment by SomewhatDamaged** [comment]
I was posting it there for Caltinor (the PMMO dev).

Looking at Farmers Delight, I don't think they're food or potions, but their own usable item. I'll leave it to Caltonor to figure out what exactly is going on.

**Comment by Elaski6573** [comment]
Ah you are right. They are not potions.
I should have marked it as a Interaction/Compat, not a bug.
