### ISSUE TITLE
Fade Gain List Items Out

### ISSUE THREAD

**Issue by MattB70** [Caltinor/Project-MMO-2.0#344]
**Describe the solution you'd like**
An option to have skill list items fade out rather than disappear instantly would dramatically improve the readability of the skill list when it's in your peripheral vision.

**Why is this feature needed**
This one really isn't necessary, but one that I've learned to love in UX experiments. Fading out somehow improves passive readability dramatically.

**Describe alternatives you've considered**
There really isn't any other alternative aside from just leaving it as it is, which is also good. This one isn't important at all.

**Comment by Caltinor** [comment]
finally got around to this.
