### ISSUE TITLE
Skills not showing properly

### ISSUE THREAD

**Issue by Luke987100** [Caltinor/Project-MMO-2.0#345]
**Describe the bug**
When I ever I look through the ui or the skills section all skills are displayed as the word "knowledge" withe the xp next to it and I can't distinguish between the skills. This is on the 1.18.2 version
Forge 40.9.1

**Expected behavior**
It should display all skills withe there respective names.

**Comment by Caltinor** [comment]
You are using the Dawncraft modpack.  This modpack takes advantage of PMMO's high customizability to create special skills like Knowledge and set requirements for items. To learn more about the modpack check out their wiki: https://dawncraft.fandom.com/wiki/DawnCraft_Wiki
or join their discord: https://discord.com/invite/UjPx5jzd3m
