### ISSUE TITLE
[ Enigmatic Legacy ] Negative status effect immunity

### ISSUE THREAD

**Issue by Elaski6573** [Caltinor/Project-MMO-2.0#347]
I'm not sure this problem has a good solution.

Non-Eucliden Cube Item has negative status effect immunity.
It nullify all the negative status, which also include pmmo debuffs.
![image](https://github.com/Caltinor/Project-MMO-2.0/assets/114150904/cd1a3f94-2028-4212-968b-2af02929f451)
![image](https://github.com/Caltinor/Project-MMO-2.0/assets/114150904/8f1f395c-0736-49ec-8ad1-e5daf1bf88ce)

This item allows you to use a number of other tools, even if the requirement level is low.

**Comment by Caltinor** [comment]
> This item allows you to use a number of other tools, even if the requirement level is low.

Does it let you use the tool (like actually break blocks) or is there just no debuff for holding it?

**Comment by Elaski6573** [comment]
Yes. I can use it without any restrictions.

**Comment by Elaski6573** [comment]
I tested again.
There's no problem with just using the tool.
I'm sorry for giving you the wrong information.
I thought the attack wouldn't go in at all because of the weakness debuff.

There is no debuff for holding it.
Mining with tools or attacking with weapons is well prevented.

**Comment by Caltinor** [comment]
okay, then in this case, pmmo is working as intended.  I would say this is a feature of enigmatica that you will need to balance around for your own purposes.
