### ISSUE TITLE
[suggestion] Reward XP when complete the advancements

### ISSUE THREAD

**Issue by Elaski6573** [Caltinor/Project-MMO-2.0#349]
**Describe the solution you'd like**
I'd like to have a system that rewards XP for completing it as a kind of mission and quest.
By using datapack, users can make PMMO like a MMORPG.

Minecraft rewards you when you complete advancements.
It gives Experience or Recipes for reward.
Add a PMMO system to this that player can get PMMO Experience by completing advancements.

Example File 
[return_to_sender_pmmo_example.txt](https://github.com/Caltinor/Project-MMO-2.0/files/12320952/return_to_sender_pmmo_example.txt)

![image](https://github.com/Caltinor/Project-MMO-2.0/assets/114150904/ddd2d773-5540-4ac9-ba6d-a316e2b475f5)

**Why is this feature needed**
Makes PMMO like MMORPG
Allows users to config easily by using datapack.

**Comment by Caltinor** [comment]
You can already award XP from advancements by using mcfunctions.   Use the `@s` entity selector in your commands and it will work. This has been done by other pack devs, so I know this works.
