### ISSUE TITLE
/pmmo admin

### ISSUE THREAD

**Issue by Orangejewce92** [Caltinor/Project-MMO-2.0#350]
i would like to have a feature where you could bypass the requirements for modpack or server management reasoning.

Something as simple as /pmmo admin bypass

toggleable and only used by /OP.
good for item/mod/dimensional travelling troubleshooting.

**Comment by Orangejewce92** [comment]
should mention i'm using 1.19.2 but all versions would be nice to have (:

**Comment by Caltinor** [comment]
use `/pmmo genData players @p` then `/pmmo genData create` to have a file in your datapack for your user.  Then set `"IgnoreReq": true`

**Comment by Orangejewce92** [comment]
Interesting work around. But the server admins would still like to play. Would be nice to have something toggleable

**Comment by Orangejewce92** [comment]
Without having to create and delete datapacks that is

**Comment by SomewhatDamaged** [comment]
A good way to support such testing would be to allow people to store/restore their skill ranks.

**Comment by Caltinor** [comment]
Note to self for implementation.  Use state-based data to set the toggle.  This will clear the setting on reload as it will be overridden by the data loaders and won't be saved on shutdown.
