### ISSUE TITLE
Adding an press check to the vein mine

### ISSUE THREAD

**Issue by Turk645** [Caltinor/Project-MMO-2.0#352]
As it currently is, the vein mining key bind will keep firing when held and keep toggling the mining state of the block you are looking at. Adding some kind of delta check to lengthen the refire time or a bool to check for single presses might make the vein miner a bit less of a hassle to use.

**Comment by Caltinor** [comment]
The key is not meant to be held. You use the key to mark the block and use it again to unmark. You do not hold the key like you do with FTB ultimine.

**Comment by Turk645** [comment]
I know it's not meant to be held but i frequently push the button just long enough that it triggers it twice and thus unchecks the block. Becomes a game of fighting with the button press till it stays nicely

**Comment by Caltinor** [comment]
I am inclined to suggest you learn to hold the button for a shorter duration. While a delay may be ideal for you it may also create frustration for others who want to rapidly unmark a block before breaking it.

**Comment by SomewhatDamaged** [comment]
You can adjust the repeat delay yourself:

Windows:
1. WinKey + R
2. Type `control keyboard` and press enter
3. Adjust settings until they are exactly how you'd prefer

Mac: 
1. Apple menu
2. System Settings
3. Click "Keyboard" in sidebar
4. Adjust settings until they are exactly how you'd prefer

And I am sure, if you're using some Linux flavor, that they have a config somewhere for this.

**Comment by Turk645** [comment]
i tend to rebind to mouse5 which triggers a lot faster than the keyboard. If on keyboard it seems fine

**Comment by SomewhatDamaged** [comment]
I know Logitech support delays between a button refiring. You'd have to check with your mouse's vendor.

![image](https://github.com/Caltinor/Project-MMO-2.0/assets/6394544/f0dd93f1-dc3b-42d4-bc8e-80666a103aec)

Also, make sure it's only bound on button down and not on held-down.

**Comment by Orangejewce92** [comment]
i know there is that little symbol that appears once you've selected the delta key. is it just possible to add a visible "on/off" so if you know you pressed to hard or too long you can just press it again?

**Comment by TheTaterLord** [comment]
> i know there is that little symbol that appears once you've selected the delta key. is it just possible to add a visible "on/off" so if you know you pressed to hard or too long you can just press it again?

The great big white box around a block isn't enough of a notification you have vein mining enabled?

**Comment by Orangejewce92** [comment]
I don't know what you are talking about. In 1.19.2 there's a big box?

**Comment by Caltinor** [comment]
once a block is marked, an icon appears next to your crosshair showing that you are looking at a marked block and which vein type you are using.  Additionally, all blocks that are to be veined are outlined in purple to show the player what is being broken.  Certain rendering mods like OptiFine can obscure the outlining though.

**Comment by Orangejewce92** [comment]
alright.
