### ISSUE TITLE
Add Perk Event for CROUCHED and UNDERWATER

### ISSUE THREAD

**Issue by Silvertide7** [Caltinor/Project-MMO-2.0#359]
**Describe the solution you'd like**
An event is fired when a player is crouched allowing perks to be created for a crouching player. (This would pair well with my other feature request for delay: https://github.com/Caltinor/Project-MMO-2.0/issues/358).

I'm also tacking on adding an UNDERWATER event when underwater instead of having to create a perk for SUBMERGED, DIVING, and SURFACING to get something of the same effect. This could be something of a group, so if a perk is created with `[[Perks.For_Event.UNDERWATER]]` then it would be triggered by SUBMERGED, DIVING, and SURFACING events, saving the need to create 3 identical perks.

**Why is this feature needed**
It would be nice to add perks for a crouching player, like add temporary increased movement speed for a sneaky player, or give the invisibility effect. The UNDERWATER event is more just for clarity and reduction in perk creation.

**Describe alternatives you've considered**
For CROUCHED, none. For IN_WATER you can create the same effect by creating three of the same perks for SUBMERGED, DIVING, and SURFACING, and possibly SWIMMING as well

**Comment by Caltinor** [comment]
[CROUCH](https://github.com/Caltinor/Project-MMO-2.0/blob/6f2fc05cf4893c24c3588c1b420f88aa759fe2a7/src/main/java/harmonised/pmmo/api/enums/EventType.java#L23) covers your crouch case.
 [SUBMERGED](https://github.com/Caltinor/Project-MMO-2.0/blob/6f2fc05cf4893c24c3588c1b420f88aa759fe2a7/src/main/java/harmonised/pmmo/api/enums/EventType.java#L62) needs to be updated though.  right now it only triggers if all other cases are false when really it should trigger always and the others are just ways to specify. 

links are to the reference with all the events.

**Comment by Silvertide7** [comment]
Ooo thanks, I'm bookmarking that. Okay cool, yeah that would work perfect too.
