### ISSUE TITLE
Vein Mining Crash

### ISSUE THREAD

**Issue by Tyrius1** [Caltinor/Project-MMO-2.0#36]
Was vein mining coal and it crashed right after I mined it

Crash Report:
https://pastebin.com/JvsXKCPC

**Versions:**
 - Minecraft: 1.19
 - PMMO: 1.19-0.1.1

**Comment by Caltinor** [comment]
@Tyrius1 Could you see if the issue is resolved with 1.19-0.2.0?  There were some internal changes to how veinmining works that may resolve this issue unintentionally.
