### ISSUE TITLE
mob_multipliers aren't working for biomes or dimensions.

### ISSUE THREAD

**Issue by Silvertide7** [Caltinor/Project-MMO-2.0#360]
**Describe the bug**
`mob_multiplier` does not appear to be doing anything in biomes or dimension jsons.

**Expected behavior**
`mob_multiplier` to scale the mobs in question accordingly.

**To Reproduce**
When creating a `plains.json` config add:
```
{
    "mob_multiplier": {
        "minecraft:skeleton": {
            "minecraft:generic.movement_speed": 0.2,
            "minecraft:generic.max_health": 0.2,
            "minecraft:generic.attack_damage": 0.2
        }
    },
    "override": true
}
```

Go to a plains and the skeletons behave the same as any other skeleton.

**Versions:**
 - Minecraft: 1.20.1
 - Loader: Forge-47.1.44
 - PMMO: 1.20.1-1.1.3

**Additional context**
It appears that mob scaling from levels is still being applied when I view the entity data of the skeletons. Is it possible they are overwriting the mob multipliers?

**Comment by Caltinor** [comment]
Please include the section with versions in your bug reports.  I know this applies to all of them, but for future reports, please include.

**Comment by Silvertide7** [comment]
Oops, it is in there, i just accidentally included it inside the code section. I must not have closed it correctly.

**Comment by Silvertide7** [comment]
Ah, the three back ticks need to be on their own line..
