### ISSUE TITLE
NBT Rules Being Overridden By Empty Datapack

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#362]
**Describe the bug**
A freshly created datapack with empty NBT entries for items like Tinkers' Construct tools and Minecraft dyed leather armor overwrites the built-in rules.

**Expected behavior**
I'd expect empty lists in `nbt_requirements`, `nbt_xp_values` and `nbt_bonuses` not to overwrite the built-in files. Maybe have them only do so when `"override": true`?

**To Reproduce**
1. Fresh game with PMMO
2. Make dyed leather chestplate
3. Create empty datapack
4. Do `/reload`
5. No more xp_bonuses.

**Versions:**
All current PMMO versions.

**Additional context**
This emotive cat:

https://github.com/Caltinor/Project-MMO-2.0/assets/6394544/3d89335a-042b-4bcc-bd75-a30d1566983a

**Comment by SomewhatDamaged** [comment]
Another option could be to just make users block the specific files if they want to override the built-in ones, though that doesn't help 1.18 users.

**Comment by Caltinor** [comment]
🤔 I've always held the perspective that NBT config entries consist of a comprehensive idea of configurations.  However, if datapacks that weren't overriding were simply added to the end of the logic sequence, then we could have them combine.   It would just have to be a consideration of the implementation, which is perfectly fine.
