### ISSUE TITLE
Replace RANGED_TO_X and MELEE_TO_X with the actual damage type.

### ISSUE THREAD

**Issue by Silvertide7** [Caltinor/Project-MMO-2.0#363]
**Describe the solution you'd like**
I'm going to use your own verbiage for this one: Replace the RANGED_TO_X and MELEE_TO_X with the actual damage type, so that you can instead use MC's damageType registry to set up XP based on the type of damage dealt using the vanilla system

**Why is this feature needed**
This would also allow you to register custom damage types via datapack and use those in your configs to specify damage.  for example if you set up a custom CT perk that dealt damage in an AOE to mobs around the player you could have a damage type you made in your datapack "silvertide:aoe" used when the aoe deals its damage.  then PMMO will look at the damage type and try and find a config setting for that damage type to award XP to.  In this way you could have an exclusive skill for that perk that only levels up when that perk is used.

**Describe alternatives you've considered**
None

**Comment by Caltinor** [comment]
This would be a breaking change to current configs and only apply to 1.19.4+.  I will have to consider if there is a way to preserve the current configs before implementing.

**Comment by Silvertide7** [comment]
No problem, I'm using 1.20.1 anyway. It would be really cool to have something like this if you can make it work! I'd like to make a skill that is only leveled when you do damage of that type. Then higher levels will enhance those effects. No worries if not though
