### ISSUE TITLE
Add XP event for CROUCH_WALK

### ISSUE THREAD

**Issue by Silvertide7** [Caltinor/Project-MMO-2.0#364]
**Describe the solution you'd like**
Add XP event for CROUCH_WALK.

**Why is this feature needed**
Allow xp to be given for when a player is sneaking. Could be for a new sneak skill?

**Describe alternatives you've considered**
None come to mind.

**Comment by Caltinor** [comment]
This is ideal for a rework of the event context system i'm working on.  I'm going to close this for now and we can revisit when i have that system in place.
