### ISSUE TITLE
[1.16.5] BYG Forge Tags Not Applying Restrictions

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#369]
**Describe the bug**
Adding `#forge:ores/amaterine` to `req_break.json` doesn't end up applying the specific requirements to the blocks.

**Expected behavior**
Both kinds of amaterine ore should have the appropriate requirement set.

**To Reproduce**
1. Install Oh The Biomes You'll Go
2. Add `"#forge:ores/ameterine": {"mining":100}` to `req_break.json`
3. Join game and verify it hasn't got `Mining 100` as a requirement.

**Versions:**
 - Minecraft: 1.16.5
 - Loader: Forge-36.2.39
 - PMMO: 1.16.5-3.69.0

**Additional context**
Setting the two blocks directly works.

**Comment by Caltinor** [comment]
Upon review, the method `Xp.getElementsFromTags` specifically only queries the forge tags classes and does not query the actual registries for all tags.  As such, only tags explicitly defined by forge work for tags.  A fix would involve redirecting the tag getters to the registries in which they are stored, which may or may not require adding world access to the methods and and the entire call heirarchy.
