### ISSUE TITLE
[1.20.1] Crash On Start

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#371]
**Describe the bug**
Crash on start

**Expected behavior**
Starts up

**To Reproduce**
1. Install latest version of PMMO
2. Try to start game

**Versions:**
 - Minecraft: 1.20.1
 - Loader: Forge-47.1.43
 - PMMO: 1.20.1-1.2.4

**Additional context**
Logs:

[latest.log](https://github.com/Caltinor/Project-MMO-2.0/files/12475490/latest.log)

[debug.log](https://github.com/Caltinor/Project-MMO-2.0/files/12475481/debug.log)

**Comment by Caltinor** [comment]
Fixed with Hotfix https://github.com/Caltinor/Project-MMO-2.0/commit/18b138da106de15ac1a98f21d702d4541b79e039
