### ISSUE TITLE
Perk Event Idea: BOW_DRAWN

### ISSUE THREAD

**Issue by Silvertide7** [Caltinor/Project-MMO-2.0#374]
**Describe the solution you'd like**
I'd like to be able to give a player a damage increase when the bow is drawn for a set amount of time. This would also require the delay perk feature implementation to make real use of.

**Why is this feature needed**
I'd like to give a damage boost if the player takes their time while the bow is drawn. Give them the choice of higher single damage shots vs lower damage but faster shots. This might be kind of hard without temporary stat boosts though since strength effect only effects melee damage. I would also like to give players an effect that outlines nearby mobs when the damage boost triggers, similar to a hunter potion in Terraria, once I can remember what that mods name is.

**Describe alternatives you've considered**
None

**Comment by Caltinor** [comment]
Leaving this as a note for myself.  The logic for this is captured via the `CONSUME` event which uses the Forge `LivingEntityUseItemEvent.Finish` event.  The bow fires the same event.  However, the CONSUME event is currently limited to food items.  Updating this to capture `ProjectileWeaponItem`s will allow for other items.  I want to explore more use cases before implementing so this feature can be well rounded.

**Comment by natephillips801** [comment]
Yeah I see what you mean, I'm definitely okay with not implementing this if it's just kind of funky. My original thought was to use this with that delay perk attribute so that they get a bonus increase after holding the bow at full charge for like 3 seconds. Since that delay attribute isn't going to work out I'm not sure if I would use this personally anyway.

**Comment by Caltinor** [comment]
Alright,  i'll close this then.  We can reopen if there's renewed interest.
