### ISSUE TITLE
Crash When Using Colon in Paths

### ISSUE THREAD

**Issue by Reveter** [Caltinor/Project-MMO-2.0#376]
**Describe the bug**
Setting up a datapack, and when I try to use a path containing a colon in nbt_requirements the game crashes.

**To Reproduce**
1. Add a paths value containing a colon
2. Reload game
3. Hover over item
4. Crash

**Versions:**
 - Minecraft: 1 .20.1
 - Loader: Forge-47.1.27
 - PMMO: 1.20.1-1.2.5.jar

**Additional context**
Crash Report: https://gist.github.com/Reveter/95fa8eb0329d754642501ebc7792673d
JSON causing issue: https://gist.github.com/Reveter/2a5e9931511d61428770fcaac6e4c1a6

**Comment by Caltinor** [comment]
Thank you for the report.  This is a fairly easy fix.  leave it to SG to give zero shits about NBT formatting standards... again.
