### ISSUE TITLE
Vein Miner stops working

### ISSUE THREAD

**Issue by ODevil97** [Caltinor/Project-MMO-2.0#380]
**Describe the bug**
Vein Miner suddenly stops working after playing for a while. The Symbol on the cursor still shows up, but it no longer highlights blocks for vein mining (even though it worked previously). The related UI text at the bottom left also disappears and no longer shows regardless of the corresponding hotkey being pressed.

**Expected behavior**
Vein Miner works as usual.

**To Reproduce**
1. Play for a while using Vein Miner as usual
2. It suddenly stops working

**Screenshots**
![2023-09-14_19 33 37](https://github.com/Caltinor/Project-MMO-2.0/assets/136800786/1a14d2f8-89b5-492d-afb6-46eb3802fa33)

**Versions:**
 - Minecraft: 1.20.1
 - Loader: Forge-47.1.3
 - PMMO: pmmo-1.20.1-1.1.3

**Additional context**
Playing on a public server with the Modpack: MineColonies: Dimensional Adventure 1.9 - Redux Hotfix

**Comment by Caltinor** [comment]
The absence of the vein gauge on the bottom left would signal to me that you are not wearing any items that give vein capacity or charge and that you have depleted your existing charge.  Can you confirm that you are wearing/holding items that have at least some charge cap and rate?

**Comment by TheTaterLord** [comment]
What modpack is it?

**Comment by Caltinor** [comment]
I suspect that might be the case.  I would check with the modpack dev.  It might be something they configured to control the vein rates.

**Comment by ODevil97** [comment]
I wrote a report on the modpack's discord still waiting for a reply.

I can confirm though that vein miner randomly goes away without a level up triggering it. The UI just disappears all of a sudden and vein miner no longer works.

(Also why can I only close the issue as completed or as not planned, instead of just keeping it open?)

**Comment by Caltinor** [comment]
You should have an option just to comment without selecting an option.
![image](https://github.com/Caltinor/Project-MMO-2.0/assets/62700786/88151736-f396-481e-babd-879e8b97873a)
