### ISSUE TITLE
Command to Remove Mod

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#381]
**Describe the solution you'd like**
A command that would, ideally, reset all skills of all players to 0, disable all perks, and remove all adjustments to player attributes. This would be a feature for removing the mod safely and leaving no trace of itself behind.

Ideally, restarting the mod after this would enable it fresh and regenerate all config files.

**Why is this feature needed**
Either when removing the mod itself or wanting it to reset to have default settings.

**Describe alternatives you've considered**
Lots of typing commands to remove attribute modifiers and screaming at the mod.

**Additional context**
Would also be useful for refreshing test environments.

**Comment by Caltinor** [comment]
The only persistent aspect of PMMO would be attributes granted by the attribute perk.  After reviewing what it would take to implement this command within PMMO, I realized it would be far simpler to use the `/attribute` command to clear all modifiers than it would be to implement this on the PMMO side.

An alternative solution to removing the mod would to be to set all attribute perks to have zero scaling so the next time they activate, they are replaced with a useless value.  You could then use a command perk with something like jumping to run an xp reset command and set the global modifier to 0.0 to prevent any additional XP gain.  Then when you are confident the attributes of all players have been removed, remove the mod.
