### ISSUE TITLE
`nbt_bonuses` In `entities` JSON to Allow For Per-Player XP Bonuses

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#385]
**Describe the solution you'd like**
`nbt_bonuses` entry in `entities` datapack files (specifically for players) to allow for per-player bonuses to XP.

**Why is this feature needed**
Someone was making some scripted stuff for a modpack, and wanted a way to add bonuses to players when they have done specific things in the pack's progression.

**Describe alternatives you've considered**
Alternatives include making a curios slot and a custom item for it that cannot be removed and putting the NBT data/WORN on that.

**Additional context**

https://github.com/Caltinor/Project-MMO-2.0/assets/6394544/60fcf299-aad9-43eb-9674-184c315b2bcb

**Comment by Caltinor** [comment]
The folder `pmmo/players/` let's you set configurations per player and includes bonuses. The issue with their implementation is they want those bonuses applied dynamically which isn't how datapacks work.

**Comment by SomewhatDamaged** [comment]
I guess the better option, for dynamic bonuses, would just be to have a dict of them in the NBT on the player and be done with it.

**Comment by SomewhatDamaged** [comment]
Ah, fair then.
