### ISSUE TITLE
Command to add permanent `nbt_bonuses` amounts to a player

### ISSUE THREAD

**Issue by Bees-Please** [Caltinor/Project-MMO-2.0#386]
**Describe the solution you'd like**
A command mirroring the functionality of /pmmo admin @s set agility_bonus 2.5 that would apply a permanent bonus to that player that persists after death and between login sessions.

**Why is this feature needed**
This would give admins/ developers tools to reward players, design datapacks more easily, and debug more easily.

**Describe alternatives you've considered**
Giving players a permanent Curse of Binding item that gives specific bonuses when the use case calls for it (Consumes an armor slot),
Giving a player a scoreboard objective that runs a command that places a bound item in the slot if the slot is empty (allowed for item spamming on server, deprecated this quick.),
Binding curio with bonuses (Curio does not return to slot unless placed by player, this allows them to drop it)

**Comment by SomewhatDamaged** [comment]
Perhaps, if such a feature is added, an option to make it "until death" or "until removed"?


Suggested formatting:
`/pmmo admin @s set agility bonus 2.5`
`/pmmo admin @s set agility bonus 2.5 permanent`

**Comment by Caltinor** [comment]
A `setBonus` command is a good suggestion.  As for the persistence, the command would persist as long as the server was loaded, regardless of logins or deaths.  The only way to persist the setting outside of that would be to commit it to data via `begin`,`withDefaults`,`withPlayers @s`, and `create`.  This however would require alterations be made at the datapack level.
