### ISSUE TITLE
max level bug 

### ISSUE THREAD

**Issue by NABS2ER** [Caltinor/Project-MMO-2.0#387]
**Describe the bug**
Describe exactly what you observed

The maximum level I can get is 329, the level of combat to use the tool is much greater > 400

**Expected behavior**

How to level up if it's a ceiling?

**Screenshots**

![2023-09-28_16 00 24](https://github.com/Caltinor/Project-MMO-2.0/assets/141981213/09d1db05-b1df-41f7-a267-de6f86580990)
![2023-09-28_16 00 24](https://github.com/Caltinor/Project-M
![2023-09-28_16 00 32](https://github.com/Caltinor/Project-MMO-2.0/assets/141981213/5c1fd421-84ce-4e60-b032-00cce5f3f628)

![2023-09-28_16 00 28](https://github.com/Caltinor/Project-MMO-2.0/assets/141981213/3f2af107-8416-4d39-b5b2-bdeee36b10ed)
MO-2.0/assets/141981213/21612a0a-d95d-4a2b-ba0f-0570082955b9)

![2023-09-28_16 00 17](https://github.com/Caltinor/Project-MMO-2.0/assets/141981213/4da02250-e496-4786-905c-2822462e101c)

**Versions:**
 - Minecraft: (eg 1.20.1)
 - Loader: (eg. Forge-47.1.3)
 - PMMO: 1.20.1-1.2.6 and all previous versions have this bug

**Additional context**

**Comment by Caltinor** [comment]
Your limiting factor is your XP formula.  If you want higher max level, you need to adjust the formula to allow it. The max level is based on the highest value once a skill reaches 9,223,372,036,854,775,807 XP. Make the curve slower and you'll get more levels.

**Comment by NABS2ER** [comment]
I'm not talking about the experience that is given and increases the level, but about the level itself!
The maximum level I can get is 329
Firstly, you can hardly crawl to it without cheats, and secondly, if you crawl, it’s still not enough to use some items! Why can’t I even use them in creative work? Isn't that weird? 
Your leveling is not real!

**Comment by NABS2ER** [comment]
> Your limiting factor is your XP formula. If you want higher max level, you need to adjust the formula to allow it. The max level is based on the highest value once a skill reaches 9,223,372,036,854,775,807 XP. Make the curve slower and you'll get more levels.

I tried to increase XP little by little, but nothing worked, the level did not increase.
I'm not talking about the experience that is given and increases the level, but about the level itself!
The maximum level I can get is 329
Firstly, you can hardly crawl to it without cheats, and secondly, if you crawl, it’s still not enough to use some items! Why can’t I even use them in creative work? Isn't that weird?
Your leveling is not real!

**Comment by NABS2ER** [comment]
> you have to change the formula in `pmmo-server.toml` to make the exponential gain slower. by default it is very steep. That's why the mod is designed to be customizable for people like yourself who don't enjoy the grind as much as others.

What should I do to set it up?

**Comment by Caltinor** [comment]
you edit the values.  make the power smaller for a slower curve.

**Comment by NABS2ER** [comment]
> you edit the values. make the power smaller for a slower curve.

where and how to do this?

**Comment by Caltinor** [comment]
in `pmmo-server.toml`, as said before. you want to edit, these values
![image](https://github.com/Caltinor/Project-MMO-2.0/assets/62700786/581b4fcc-ed1e-4dd7-93e5-e6528f0bce39)
make the power base smaller to get a shorter curve and higher possible max level

**Comment by NABS2ER** [comment]
> in `pmmo-server.toml`, as said before. you want to edit, these values ![image](https://user-images.githubusercontent.com/62700786/271447624-581b4fcc-ed1e-4dd7-93e5-e6528f0bce39.png) make the power base smaller to get a shorter curve and higher possible max level

I'm a little wooden on this issue
Сan you just tell me what to change to what?

**Comment by NABS2ER** [comment]
> you edit the values. make the power smaller for a slower curve.

I changed the values, but nothing happens, why don’t you just solve this problem yourself, it’s your mod that’s causing problems! Or just tell me what exactly I should write, I couldn’t do it!

**Comment by TheTaterLord** [comment]
Caltinor explained exactly which values to change lower the power base value gives you a higher max level for the same amount of xp depending on how much you changed that value you get significantly higher max levels so rather than being 1.104088404342588 you can change it 1.0 for example and you will gain max levels

**Comment by NABS2ER** [comment]
> Caltinor explained exactly which values to change lower the power base value gives you a higher max level for the same amount of xp depending on how much you changed that value you get significantly higher max levels so rather than being 1.104088404342588 you can change it 1.0 for example and you will gain max levels


I did as you said. Does not work 
I changed the values, but my level is still 329, you are cool programmers here, and you can’t make a normal mod without bugs?
Сorrect your mistakes and make a normal mod so you can play! Please!!!

**Comment by SomewhatDamaged** [comment]
Use the settings in this file. You will need to shut down the game before you copy it over the top, but it will give you a MUCH higher max level.
[pmmo-server.zip](https://github.com/Caltinor/Project-MMO-2.0/files/12774963/pmmo-server.zip)

**Comment by NABS2ER** [comment]
> Use the settings in this file. You will need to shut down the game before you copy it over the top, but it will give you a MUCH higher max level. [pmmo-server.zip](https://github.com/Caltinor/Project-MMO-2.0/files/12774963/pmmo-server.zip)

Thanks, your file works
But why can't the mod determine the power of a weapon according to its limits of 329 levels and sets it to 435?
Now my maximum level is 9001, this is strange! Why don't you fix the problem in this mod?
Your mod is not working correctly, and you throw me a file that supposedly will improve the situation, you have a wonderful mod and I want to use it normally, please fix this problem and thank you!

**Comment by SomewhatDamaged** [comment]
Because it's expected that, for modded items, whomever is building the modpack would configure the mod to their liking.

The mod works on a "best effort" when it comes to supporting other mods. If the mod is making items significantly more powerful than the base Minecraft ones, it can only work off the values given (weapon swing speed, weapon damage, mining level, mining speed, etc).

**Comment by Caltinor** [comment]
The mod is working exactly as intended. All features are customizable to your liking, and you are encouraged to do so. For whatever reason you were unable to edit the files and that on you.  Make sure the server is shut down and you edit the files with an editor that does not cache values, like Notepad++.  Notepad, VSCode, etc are good options.

As for values above the max level, those are dynamically generated by AutoValues, which you can edit in `pmmo-AutoValues.toml`.  

I also encourage you to read the wiki for all other customization options.

**Comment by NABS2ER** [comment]
> The mod is working exactly as intended. All features are customizable to your liking, and you are encouraged to do so. For whatever reason you were unable to edit the files and that on you. Make sure the server is shut down and you edit the files with an editor that does not cache values, like Notepad++. Notepad, VSCode, etc are good options.
> 
> As for values above the max level, those are dynamically generated by AutoValues, which you can edit in `pmmo-AutoValues.toml`.
> 
> I also encourage you to read the wiki for all other customization options.

For people who know how, the config file is just right, but if you are making a mod with customization, you need to do it in the game menu, simply and tastefully so that I press a button and turn something on or off, and so on, and not edit the document in notepad

**Comment by NABS2ER** [comment]
> Because it's expected that, for modded items, whomever is building the modpack would configure the mod to their liking.
> 
> The mod works on a "best effort" when it comes to supporting other mods. If the mod is making items significantly more powerful than the base Minecraft ones, it can only work off the values given (weapon swing speed, weapon damage, mining level, mining speed, etc).

I think it's your fault if the weapons of other mods are not displayed correctly.
It doesn't matter what value a weapon has, if the max level is 329, let them adjust, right?

**Comment by NABS2ER** [comment]
And in general, why 329 levels, this is some kind of joke, why not 228 or 345 or at least 331? Why not turn on the perfectionist and make 100? It's all strange!

**Comment by SomewhatDamaged** [comment]
> And in general, why 329 levels, this is some kind of joke, why not 228 or 345 or at least 331? Why not turn on the perfectionist and make 100? It's all strange!

That's just what the standard equation gives. You are welcome to change it to whatever you like.

**Comment by NABS2ER** [comment]
> > And in general, why 329 levels, this is some kind of joke, why not 228 or 345 or at least 331? Why not turn on the perfectionist and make 100? It's all strange!
> 
> That's just what the standard equation gives. You are welcome to change it to whatever you like.

By edit, do you mean close the game, find some file, open it through notepad and edit it, looking at the letters and numbers that ordinary people do not understand? Do you mean this?

**Comment by NABS2ER** [comment]
You are all great, it’s a pleasure to communicate with you, please do everything right, bring the mod to perfection, I don’t want to mess around every time when something doesn’t suit me in the notepad when closing the game, there are 400 mods + my game takes 3 minutes to turn on and the same amount is turned off, do your job efficiently, special thanks to you for your efforts!
I would like to see a further update of the mod without these problems.

**Comment by NABS2ER** [comment]
> Use the settings in this file. You will need to shut down the game before you copy it over the top, but it will give you a MUCH higher max level. [pmmo-server.zip](https://github.com/Caltinor/Project-MMO-2.0/files/12774963/pmmo-server.zip)

No, well, it has become impossible to play, this is a problem that is clearly not solved by your method, literally at all, I thought that it seemed possible to play like this, but no!
Maybe there are some other ways to influence the situation, for example, to make sure that the weapon does not exceed the maximum level? Can I manually change it?

**Comment by Caltinor** [comment]
In addition to the server configs, the mod is designed to be configured via Minecraft's Datapack system.  This is how Minecraft itself allows for customization and requires the editing of JSON files.  If you do not like this method of configuring, you are going to be sorely disappointed.  

As mentioned before, the [wiki](https://github.com/Caltinor/Project-MMO-2.0/wiki/Configuring-PMMO) has instructions on how to set values for the items in your world.  In summary, you will need to generate a datapack (commands provided and detailed in the wiki) and set the values you desire in that item's file.  

Lastly, I am growing quite tired of your repeated insinuation that the mod is broken when it is your user error that is at fault, the suggestion that the mod be modified to your specific needs, and that the design is either poor or distasteful.

**Comment by NABS2ER** [comment]
> In addition to the server configs, the mod is designed to be configured via Minecraft's Datapack system. This is how Minecraft itself allows for customization and requires the editing of JSON files. If you do not like this method of configuring, you are going to be sorely disappointed.
> 
> As mentioned before, the [wiki](https://github.com/Caltinor/Project-MMO-2.0/wiki/Configuring-PMMO) has instructions on how to set values for the items in your world. In summary, you will need to generate a datapack (commands provided and detailed in the wiki) and set the values you desire in that item's file.
> 
> Lastly, I am growing quite tired of your repeated insinuation that the mod is broken when it is your user error that is at fault, the suggestion that the mod be modified to your specific needs, and that the design is either poor or distasteful.

You sit in the fresh air with a mug of beer in your hand, you smile, there is even a person who took a photo of you, aren’t you relaxing? Nonsense! Look, people don't like a lot of things, I agree, but still there is a problem in your fashion, I showed you, it really needs to be fixed! Why? Yes, since no one but you will make your mod, then a document changing the value does not remove the problem, but only adds a new one, in case you didn’t know! Now you know it and can understand it! 

In the wiki there is a lot of bullshit that I can’t figure out, unfortunately for me it’s not clear!

Let's put things in order again, the problem is that the weapon level cannot be reached! You need to make sure that any weapon or other tool adapts to your level! If it's for god level, let it be 250 or the last one. I don't understand, is it really that difficult to do?
Maybe you didn't know, but the file in which the values ​​were changed is not suitable for the game, because there at level 4000, which was changed to 150, for example, the mobs had at least 1000 health and moved so fast that Flash was jealous such speed. it's not playable! Even with the items that I had, they would not die for a long time. 
In your language, this is a clear bug in the code, in your code, and it needs to be rewritten or expanded. But despite all the design and everything else that they usually write to you, this is a specific problem and it definitely needs to be solved! No amount of settings or Wiki articles will help you configure the mod the way you need, it must initially adapt to the environment! You can just cap everything to 329 if that's your max level! It's definitely not difficult for you. 

Please do it! Thank you for your attention

**Comment by Caltinor** [comment]
You have some serious issues. Best of luck in life. I'm done with this conversation.

**Comment by NABS2ER** [comment]
> You have some serious issues. Best of luck in life. I'm done with this conversation.

If you don't want to do it or can't do it, just say so
Your mod is not working correctly and you probably think that this is how it should be, if so then you have serious issues
Cheburashka

**Comment by TheTaterLord** [comment]
Okay last chance, once you have set max level where you would like it you can then edit the values of the swords themselves via datapack it's explained really well in the wiki, there are built in commands that you can run to generate the datapack structure for you so all you have to do is edit the files, once you've done that you should higher max levels AND the ability to use these weapons at the desired level.

Also please refrain from using offensive Slang here
