### ISSUE TITLE
[1.20.1] Potions Have Extra NBT Data Added

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#394]
**Describe the bug**
When making potions, they sometimes have extra NBT data (brewXpAwarded) added to the potion that makes it problematic for other mods to interact with them.

```JSON
{
	Items: [{
			Slot: 0b,
			id: "minecraft:potion",
			Count: 1b,
			tag: {
				Potion: "minecraft:awkward"
			}
		}, {
			Slot: 1b,
			id: "minecraft:potion",
			Count: 1b,
			tag: {
				brewXpAwarded: 1b,
				Potion: "minecraft:awkward"
			}
		}, {
			Slot: 2b,
			id: "minecraft:potion",
			Count: 1b,
			tag: {
				Potion: "minecraft:awkward"
			}
		}
	],
}
```

**Expected behavior**
Potions not to have extra data.

**To Reproduce**
1. Brew an awkward potion
2. Remove potion by single-clicking
3. See error

**Versions:**
 - Minecraft: 1.20.1
 - Loader: Forge-47.1.47
 - PMMO: 1.20.1-1.2.5

**Comment by Caltinor** [comment]
Unfortunately, that extra NBT is necessary to prevent players from pick-drop-picking the potion from the brewing stand and getting infinite XP.  The same thing happens with the Tetra toolbelt.  So the options are:
1. no NBT to be compatible with other mods, but you can infini-farm xp
2. NBT (as is), but you're not compatible
3. No brewing event at all (aka remove it from the mod)

**Comment by SomewhatDamaged** [comment]
Maybe have an option to set those in pmmo-server.toml?

**Comment by Caltinor** [comment]
So leave it up to the author whether they want compat with abuse, or no-abuse but compat.  That's reasonable.

**Comment by SomewhatDamaged** [comment]
Or even just disable brewing handling completely (ignore event and let it continue).
