### ISSUE TITLE
Separate pmmo:damageboost perk into 2 perks, additive (as it is now) and multiplicative.

### ISSUE THREAD

**Issue by Silvertide7** [Caltinor/Project-MMO-2.0#399]
**Describe the solution you'd like**
Create 2 perks for boosting damage, one increasing damage by a flat amount (current implementation) and the other increasing damage by a multiplicative amount.

**Why is this feature needed**
Right now the damage boost increases damage by a flat amount. This greatly increases the damage per second on weapons that attack fast but is a negligible dps increase on ones that attack slow. With a multiplicative option slow attacking weapons that hit harder would still be viable over weapons that attack 2 or 3 times as fast. When most games do  this currently they add up all of the additive increases then multiply by the multiplicative increases.

**Describe alternatives you've considered**
Make multiple perks each with different damage boost value increases, giving slower weapons more damage per level. This gets extremely hard to separate every weapon and balance them correctly without basically creating a perk for every weapon with different attack speeds and then going through and grouping them together.

**Comment by Silvertide7** [comment]
It could also just be that the damage boost is divided by the attacks speed before being applied, that would do the trick.

**Comment by Caltinor** [comment]
adding the property `multiplicative = false` will change the damage to be a flat damage increase.  by default this property is true.

**Comment by natephillips801** [comment]
Oh awesome, thanks for the info! That's perfect
