### ISSUE TITLE
XP Milestone Messages Unconfigurable

### ISSUE THREAD

**Issue by Caltinor** [Caltinor/Project-MMO-2.0#40]
**Describe the bug**
Alterations to the config seem to have no effect on whether or not a milestone message displays.  disabling the broadcasting does not disable the messages.  Additionally, increasing the milestone level does not actually update the frequency of their occurrence. 

**Expected behavior**
disabling broadcasting fully disables the feature, and/or setting the milestones actually changes when milestones apply

**To Reproduce**
1. create a new instance
2. set the milestone higher than the default of 10
3. earn XP to surpass 10 level milestone
4. observe config setting not applied
5. set broadcast setting to false
6. repeat steps 3 & 4

**Versions:**
 - Minecraft: 1.18.2
 - Loader: Forge-40.1.55
 - PMMO: 1.18.2-3.69.11

**Comment by Proxwian** [comment]
Same problem here

**Comment by Proxwian** [comment]
Not planned??? That's an actual bug, that you can't use already implemented config parameters

**Comment by Caltinor** [comment]
@Proxwian yes.  The reworked version of PMMO for 1.18 is now extremely stable and moved out of alpha.  I built a migrator tool into the mod to convert configurations from 3.69.11 to 4.0.0.  All issues related to "Legacy" pmmo were closed as there is no reason to support an obsolete version of pmmo for 1.18.
