### ISSUE TITLE
Incorrect mods.toml data.

### ISSUE THREAD

**Issue by dragoneyeeon** [Caltinor/Project-MMO-2.0#400]
**Describe the bug**
Data inside the mods.toml is that from "pmmo_compat", this can be observed inside the  most recent versions mods.toml data and causes a conflict with PMMO Compat For Strictly Medieval.  Due to the registered mod ID conflict neither mod is loaded and the game continues loading without any of the intended additional function.

**Expected behavior**
Correct mods.toml documentation preventing the conflict above.

**Screenshots**

**Versions:**
 - Minecraft: (1.20.1)
 - Loader: (eg. Forge-47.2.0)
 - PMMO: 1.20.1-1.2.8

**Additional context**

**Comment by Caltinor** [comment]
I am not sure what aspect of the mods.toml you are referring to.  Can you reference the line in the mods.toml that you are referring to? https://github.com/Caltinor/Project-MMO-2.0/blob/main/src/main/resources/META-INF/mods.toml

**Comment by dragoneyeeon** [comment]
I'll be honest I can't reproduce the error after downgrading the files and re-updating them.  It appears that curseforge somehow downloaded the PMMO file name with the contents of compat addon.  A fresh download of the 1.2.8 file from curseforge as well as from browser both resulted in clean usable files.
