### ISSUE TITLE
Feature Request: Grant XP for trading with villager

### ISSUE THREAD

**Issue by Silvertide7** [Caltinor/Project-MMO-2.0#410]
**Describe the solution you'd like**
A way to gain XP in a skill when you make a trade with a villager. Can configure what skill xp is gained in, as well as how much xp is granted for each item or emerald that is used in the transaction, either sellling or buying.

**Why is this feature needed**
It would be a cool way to gain charisma (or a new skill like bartering) rather than just interacting with an entity, which can be spam clicked to oblivion and doesn't actually mean anything. This gates it behind the number of trades the villager can make a day, as well as off of the number of emeralds or items used in the transaction, either gained or lost. Maybe at a certain level of charisma you have hero of the village permanently or something. Would be a cool milestone.

**Describe alternatives you've considered**
None come to mind.

**Comment by Caltinor** [comment]
I like it. There is a villager trade event and I could easily nest the trade values in the item configs.  I could add `GIVEN_AS_TRADE` and `RECEIVED_AS_TRADE` to item configs.

**Comment by Silvertide7** [comment]
Awesome that sounds perfect! Thanks!!

**Comment by Caltinor** [comment]
This is added.  I still don't have defaults though.  I would appreciate any input on that front.
