### ISSUE TITLE
Crash with PMMO in modded MC

### ISSUE THREAD

**Issue by DJGunn** [Caltinor/Project-MMO-2.0#413]
**Describe the bug**
When creating or loading into a modded world with today's 3.3.7 update, the game hangs and becomes unresponsive until I am forced to forcibly close the application with task manager.

**Expected behavior**
Previous to 3.3.7 update, the world is able to load properly, and new worlds are able to be generated.

**To Reproduce**
1. Install the modpack! https://legacy.curseforge.com/minecraft/modpacks/bnuuycraft/files/4846001
2. Launch the game!
3. Create a new world!
4. Explode

**Screenshots**
N/A

**Versions:**
 - Minecraft: 1.19.2
 - Loader: 43.3.2
 - PMMO: 1.19.2-3.3.7

**Additional context**
Crash logs from 3 attempts:
https://mclo.gs/wuCfK5Z
https://mclo.gs/mleAhPJ
https://mclo.gs/lPnDmL2

Thank you for your hard work and dedication! You guys are champs! <3

**Comment by Caltinor** [comment]
hotfix build tested and pending release [Build Process](https://github.com/Caltinor/Project-MMO-2.0/actions/runs/6784716760)

**Comment by DJGunn** [comment]
I was able to create new worlds with the new fix, thank you! <3 Will make another post if we have any issues. Have a great day! <3

**Comment by DJGunn** [comment]
Alright so  I installed the hotfix, and now the worlds generate sometimes, but now it seems as though the game logic stops ticking after a short period of time and doesn't return. And sometimes it happens before the world generation finishes. The game stays responsive, there's just no game logic happening. So like I can walk around, break blocks, jump off cliffs, but the blocks don't drop, I don't take damage, and there's no NPCs (that I've found yet).

Currently sititng on a world that's stuck at 44% loading. The game isn't frozen however, it's just not 'processing'. When I force a crash through alt-f4 or closing the process, there's no crash log generated. It just says game closed with error code 1.

I'm not sure how to get you a log for this.

**Comment by Caltinor** [comment]
latest.log should have anything if it's hung

**Comment by DJGunn** [comment]
Hi Caltinor!

I've tried with each version 3.3.7, 3.3.8, and 3.3.9 and the issue persists. After I was forced to use task manager to close the game, this is the latest.log that it just created in my most recent test (with version 3.3.9)

https://mclo.gs/Luh0yqv

Version 3.3.6 still works when I roll back to it.

Thanks tremendously for your insight and love you put into this project. Is this log helpful at all? Is there anything else I can do to help figure it out?

**Comment by SomewhatDamaged** [comment]
Tested it myself and can confirm it crashes as described.

Seems to be a problem with Mob Scaling in 3.3.7+.

As a work-around (and to test), try putting the following file in the `minecraft/defaultconfigs/` folder, then make the world.

[pmmo-server.zip](https://github.com/Caltinor/Project-MMO-2.0/files/13307559/pmmo-server.zip)

**Comment by Caltinor** [comment]
I have reverted the changes to Boss scaling which started this whole problem.  3.3.10 is currently being built and uploaded and as far as my testing could tell does not result in hung worlds.
