### ISSUE TITLE
Enemies can't be killed

### ISSUE THREAD

**Issue by festro** [Caltinor/Project-MMO-2.0#414]
**Describe the bug**
enemy health resetting after being attacked (only tested zombies)

**Expected behavior**
Enemies to stay damaged after being attacked.

**To Reproduce**
1. Attack enemies
2. watch health reset

**Screenshots**

**Versions:**
 - Minecraft: (eg 1.19.2)
 - Loader: (eg. Forge-43.3.2)
 - PMMO: 1.19.2-3.3.7+

**Additional context**
[2023-11-07-2.log](https://github.com/Caltinor/Project-MMO-2.0/files/13289628/2023-11-07-2.log)

**Comment by Caltinor** [comment]
Fixed via https://github.com/Caltinor/Project-MMO-2.0/commit/cef4e07191b62b75bb9710f717406e7b89ec5404  Issue confirmed and resolved.  [Build and Upload in progress](https://github.com/Caltinor/Project-MMO-2.0/actions/runs/6791367110)

**Comment by festro** [comment]
Thanks!
