### ISSUE TITLE
Agility Not Modifed By Global Modifier

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#415]
**Describe the bug**
Agility XP gains are not modified by the `"Global Modifier"` setting in `pmmo-server.toml`

**Expected behavior**
All XP to be multiplied by `"Global Modifier"`.

**To Reproduce**
1. Set `"Global Modifier" = 100000.0` in `pmmo-server.toml`
2. Enter game
3. Run around and only get sub-thirty agility XP

**Versions:**
 - Minecraft: 1.20.1
 - Loader: Forge-47.2.4
 - PMMO: 1.20.1-1.2.9

**Additional context**

https://github.com/Caltinor/Project-MMO-2.0/assets/6394544/ef83091a-27df-4a52-b283-8251f3bde48f

**Comment by Caltinor** [comment]
This is due to Global Modifier and Skill Modifiers being mutually exclusive.  If you do not remove/replace the agility skill modifier, it will always default to that value.  I will add a tooltip in the config for this, though.

**Comment by SomewhatDamaged** [comment]
Perhaps change the name of the example skill from `agility` to `example` then? That way everything would act as it should out of the box, and the tooltip will aid in people figuring out why things aren't acting as they should—and we can point to it and tell them "You didn't read this bit, did you?" 😃
