### ISSUE TITLE
Minecolonies

### ISSUE THREAD

**Issue by s4sutler100** [Caltinor/Project-MMO-2.0#416]
**Describe the bug**
Can not interact with  pedistals  form minecolonies  says my skill set is not ready 

**Expected behavior**
Interaction with the menu system

**To Reproduce**
1. Go to  townhall 
2. right Click on town hall book
3. See 

**Screenshots**

**Versions:**
 - Minecraft: 1.19.2
 - Loader:  Forge 43.3.5

**Additional context**
![image](https://github.com/Caltinor/Project-MMO-2.0/assets/16606451/a68a5b9d-0022-4ecc-ad92-3b7633ce0961)

**Comment by TheTaterLord** [comment]
this isnt a bug you just dont have the necessary levels to use the block

**Comment by s4sutler100** [comment]
> this isn't a bug you just dont have the necessary levels to use the block

What do I need to use the block? It doesn't tell me.

**Comment by TheTaterLord** [comment]
If you have a mod like Jedi or Rei installed you can hover over it in that menu and it should tell you the requirements to use it

**Comment by s4sutler100** [comment]
thank you

**Comment by s4sutler100** [comment]
![20231111_163709](https://github.com/Caltinor/Project-MMO-2.0/assets/16606451/732a411f-46ca-4800-a65d-028c9e495ad8)
![20231111_163651](https://github.com/Caltinor/Project-MMO-2.0/assets/16606451/2fa50508-c7ad-4161-af3c-5eec912c7518)

**Comment by s4sutler100** [comment]
puts a whole new spin on Minecolonies

**Comment by s4sutler100** [comment]
I should beable to open it by now but still wont let me.
