### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by s4sutler100** [Caltinor/Project-MMO-2.0#418]
**Describe what documentation needs updated or added:**
your text here
Info where the config is for  interacting with blocks.
**Why is this documentation needed:**
your justification here
Im well over the limit needed to interact with town hall in the minecolonies mod
**What medium is best for this documentation:**
eg wiki, website, in-game, discord, etc.
discord.
![20231111_200647](https://github.com/Caltinor/Project-MMO-2.0/assets/16606451/7633e654-e19c-4525-ba67-18595b4819ef)
![20231111_163709](https://github.com/Caltinor/Project-MMO-2.0/assets/16606451/699414be-27a5-4773-a69b-fb33257ef7fc)
![20231111_163651](https://github.com/Caltinor/Project-MMO-2.0/assets/16606451/01dcfb28-a43b-4111-bb66-6fce52e78c70)

**Comment by TheTaterLord** [comment]
From what I can see you're missing a few of the levels required to interact with the townhall block for example fishing and smithing they all need to be at minimum LVL 15. As for where to configure things it's all explained in the wiki for the mod here on GitHub which the link is on the curseforge page as well as in the discord for the mod. All the item and block config is done via datapack
