### ISSUE TITLE
Standardize Settings

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#424]
Right now, `pmmo-server.toml` is a hodgepodge of explicitly defined keys that have spaces (ex: `"Creative Reach"`) and raw keys that have spaces replaced with underscores (ex: `boss_scaling` `combat`).

Would it be possible, when a new major version comes out, to standardize to one or the other?

**Comment by Caltinor** [comment]
🤔 The only issue with this is that changing it would break everyone's configs.  i'm all for standardizing them, but it might not be wise to do on existing versions.

**Comment by SomewhatDamaged** [comment]
Hence why I said only on a major version (from Minecraft).
