### ISSUE TITLE
Speed 3 when sprinting upon starting a new world

### ISSUE THREAD

**Issue by wolf-cubb** [Caltinor/Project-MMO-2.0#428]
I had just recently added PMMO to my private modpack and realized that upon creating a new world, every time I sprint, I am given speed 3, and when I dive underwater, I gain night vision. And I can't change anything in the config from both files (common and client don't seem to have anything) and inside the game itself.

**Comment by TheTaterLord** [comment]
the setting for these are in the pmmo-perks.toml file located at "minecraft/saves/<yoursave>/serverconfig/pmmo-perks.toml"
you can just either delete the entire block for the relevant perk OR comment it out with # for that Perk for example  to remove fireworks you'd comment out or delete an entire block that looks like this
[[Perks.For_Event.SKILL_UP.fishing]]
    skill = "fishing"
    perk = "pmmo:fireworks"

Look for the relevant parts for sprinting and swimming and you should be good, I'd reccomend editing the file with notepad and doing with the game off
