### ISSUE TITLE
Command to Show Data Sources

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#430]
**Describe the solution you'd like**
A command that will show you the data sources for a single item/modpack.

`/pmmo findData minecraft:netherite_helmet`

It would then list the datapacks/mods that PMMO is grepping data for that item.

**Why is this feature needed**
It can be hard to track down, in a huge modpack, what compat mod might be giving values.

**Describe alternatives you've considered**
Allowing a specific data point to be searched, like:
`/pmmo findData minecraft:netherite_helmet bonuses:WORN:combat`

**Additional context**

https://github.com/Caltinor/Project-MMO-2.0/assets/6394544/9ae6323b-48de-4b38-a397-cadbad87e1e7

**Comment by Caltinor** [comment]
After attempting to implement this, the sheer magnitude of the implementation makes it not quite worth the effort.  I'd be essentially creating a ride-along clone of the code that does all the main logic but outputs at various stages.  it's just far too much to add for a single command.

**Comment by SomewhatDamaged** [comment]
Sadness, but fair enough.
