### ISSUE TITLE
Why does the player get random effects by default? How is this leveling-related?

### ISSUE THREAD

**Issue by Seff27** [Caltinor/Project-MMO-2.0#434]
**Describe the solution you'd like**
I want the player not to have random effects (speed III while sprinting, night vision while swimming), at least not by default.

**Why is this feature needed**
These massive default boosts just feels entirely unlinked to the mod's core idea of leveling, and serves only to give the player default powerups, such as a 60% speed boost while sprinting and being able to entirely ignore the limited vision in water- it's just far too much.

**Describe alternatives you've considered**

Alternatively, these could at least be level-locked to a higher level, so that they didn't add a bunch of random effects to the player that players inexperienced with the mod frequently think are bugs.

Or perhaps, these effects would be better done through the attribute system than through effects- implementing Speed through the Speed effect, for instance, and not the internal Speed attribute, serves only to make vanilla's potions, as well as many other mods, completely redundant.

Or, they could at least start at a lower level. I mean, Speed THREE, higher than anything achievable in vanilla, just at level 0? It's too much, balance-wise.

Or, it could be off by default and just be something you could toggle on, so it doesn't confuse people.

**Comment by lst15** [comment]
In a quick search I discovered that these random effects could be disabled in JSON files, for example, if you would like to disable move_speed this would be accessible at [https://github.com/Caltinor/Project-MMO-2.0/blob/main/src/main /resources/data/minecraft/pmmo/biomes/meadow.json](url)

` "positive_effect":{
        "minecraft:speed":0
    },`
    
 That way you could remove it so it stays like this
 
 ` "positive_effect":{},`
    
However on my server I don't find these JSON files.

**Comment by Caltinor** [comment]
Those are modified via datapack. The wiki has instructions on what to change. There is also an in-game command to generate the datapack for you.

**Comment by Caltinor** [comment]
This will be fixed when I fixe #428

**Comment by Caltinor** [comment]
closing this to clean up the issues list, since it's resolved via #428
