### ISSUE TITLE
Tooltips Not Showing Correctly

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#435]
**Describe the bug**
Not sure what is going on here, but here we go. When a datapack is the only source of data, some tooltips are not shown.

**Expected behavior**
All data should be in a tooltip.

**To Reproduce**
1. Disable autovalues
2. Make a datapack with `withDefaults` `withOverrides` `disabler`
3. Reload to ensure datapack is only source of data
4. Disable PMMO source using `/datapack` command
5. See error

**Screenshots**
![image](https://github.com/Caltinor/Project-MMO-2.0/assets/6394544/dac0ea26-4782-4d40-9576-744b1996a6ca)

```JSON
{
  "xp_values": {
    "BLOCK_PLACE": {
      "farming": 1
    },
    "ENCHANT": {
      "magic": 10
    },
    "CONSUME": {
      "endurance": 30,
      "cooking": 10
    },
    "SMELT": {
      "cooking": 25
    },
    "CRAFT": {
      "crafting": 10
    },
    "FISH": {
      "fishing": 100
    }
  },
  "override": true
}
```

**Versions:**
 - Minecraft: 1.20.1
 - Loader: Forge-47.1.3
 - PMMO: 1.20.1-1.2.10

**Additional context**

![birb petting](https://github.com/Caltinor/Project-MMO-2.0/assets/6394544/9b78dace-5eda-411f-8c21-ad132f2ee959)

**Comment by Silvertide7** [comment]
I'm not sure if this is another bug or in the same vein. I'm in the same environment and I gave `minecraft:cake` crafting xp, and it shows on the tooltip correctly:
<img width="415" alt="Screenshot 2023-12-03 at 12 45 58 PM" src="https://github.com/Caltinor/Project-MMO-2.0/assets/45479211/c26c2d93-e857-4318-bffe-6ea7022bb80e">

I then craft the cake and it gives me:
<img width="340" alt="Screenshot 2023-12-03 at 12 52 30 PM" src="https://github.com/Caltinor/Project-MMO-2.0/assets/45479211/3c3788f0-afe3-4663-9fb5-c3d0cd090546">
e:
and then I go:
![what](https://github.com/Caltinor/Project-MMO-2.0/assets/45479211/e8ab3cea-b123-47b4-bc36-22e1a31f46e6)

**Comment by Silvertide7** [comment]
Something else that might be helpful. When I generate the datapack, blocks do not automatically have a "CRAFT": {} put into the json file in the "xp_values" object. I add it in manually and it shows it on hover, but it doesn't give me the xp for it. I wonder if that's connected to the issue, I would think a block would automatically get a "CRAFT" field under "xp_values"?

**Comment by Caltinor** [comment]
Blocks cannot be crafted or held. They only exist in the world. Items on the other hand...  Block items pose a unique intersection that makes the distinction between them murky

**Comment by Silvertide7** [comment]
Ahh okay, that makes more sense then on maybe why some of these aren't working. I'll do some more testing!

**Comment by SomewhatDamaged** [comment]
You craft *items*, not blocks. When it is in your inventory, it is an `item`. When it is in the world, it is a `block`.

Put the `CRAFT` xp on the item version of it.

**Comment by Caltinor** [comment]
I'm pretty sure that's what they did and it wasn't working. Something about block items isn't awarding crafting XP.

**Comment by Silvertide7** [comment]
It is working for cake now, it looks like you're right, the tooltip defers to the block so you have to add the craft xp there to get it to show up on hover. The item itself is what gives the xp, which is working for cake. This isn't working for my farmers delight compat, so I'll have to figure out what's going on and modify some stuff there. Awesome thank you for the help!

**Comment by Silvertide7** [comment]
Hmm, not sure if this matters since it's another mod, but it seems like you can't add xp to cake equivalent items in farmers delight. The `farmersdelight:roast_chicken_block` is crafted in a crafting table and placed on the ground the same as cake is. There is a `farmersdelight:roast_chicken` that is an item, but that is the `Plate of Roast Chicken` you get from scooping the roast chicken with a bowl, not the item created from the crafting table. When I give it the same treatment as cake, which works perfectly for cake, it doesn't work for that block 🤷 . Just a bummer because all of the best / most expensive meals in all of the cooking mods are block based like cake, but they aren't giving XP for some reason.

**Comment by Silvertide7** [comment]
Nevermind, I just had it configured wrong. I am now getting xp from crafting these blocks. I think I've figured out the issues and I'm not sure that there's anything actionable here, sorry to waste your time!!

**Comment by Caltinor** [comment]
no worries.  glad we figured it out.  this will be a good reference for future users with similar experience.
