### ISSUE TITLE
Make `VILLAGER_TRADING` Perk Use A Tag

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#436]
**Describe the solution you'd like**
Making a `#pmmo:trader` tag that the perk `VILLAGER_TRADING` uses, so that other types of traders can be added via entity tags.

**Why is this feature needed**
There are more than just villagers that trade.

**Describe alternatives you've considered**
Maybe have some logic to detect what traders are in the pack and auto-add those?

**Additional context**
![image](https://github.com/Caltinor/Project-MMO-2.0/assets/6394544/91281b39-e33f-40c9-9869-e97831f32f7c)

**Comment by Caltinor** [comment]
Here's the thing.  the trading perk works by improving the reputation value with the villager.  This is tied to the feature that modifies prices based on reputation.  This means that by adding other mods' traders (that are not extensions of the vanilla villager) I **have** to assume they also have the reputation attribute and that it affects prices.  

It might help to have a mod example i could look at to see if this is even worth implementing.  More Villagers, for example uses the vanilla villager but adds new professions.

**Comment by SomewhatDamaged** [comment]
NPCs like the Wandering trader (vanilla minecraft).

**Comment by Caltinor** [comment]
Wandering traders don't have reputation.  There's no way to reduce their prices using the same perk.  I would have to make a whole separate perk for wandering traders to modify their trades explicitly instead of giving them the temporary reputation buff.
