### ISSUE TITLE
random potion effects 

### ISSUE THREAD

**Issue by SRGGhostFish** [Caltinor/Project-MMO-2.0#440]
**Describe the bug**
Random potion effects around landmarks like dungeons and villages

**Expected behavior**
no random effects?

**To Reproduce**
unsure? just play with the mod i suppose

**Screenshots**

**Versions:**
 - Minecraft: 1.18.2

**Additional context**
i am using this mod in a big modpack and its this mod that is causing it

**Comment by SomewhatDamaged** [comment]
Certain biomes grant a Speed 1 effect

To remove all biome modifiers you need to put the following file in your `minecraft/saves/<save name>/datapacks` folder:

[rem_dimension_bonuses.zip](https://github.com/Caltinor/Project-MMO-2.0/files/13662033/rem_dimension_bonuses.zip)

There is no need to extract it.
