### ISSUE TITLE
[1.19.2] Critical Injection Failure  CampfireBlockEntity on launch with 3.3.11 update

### ISSUE THREAD

**Issue by DJGunn** [Caltinor/Project-MMO-2.0#444]
**Describe the bug**
CampfireBlockEntity experiences a critical injection failure on launch of PMMO with the new 3.3.11 update

**Expected behavior**
The game launches and pmmo functions normally

**To Reproduce**
1. Install PMMO 3.3.11
2. Launch game
3. See error

**Screenshots**
Not Applicable

**Versions:**
 - Minecraft: 1.19.2
 - Loader: Forge - 43.3.5
 - PMMO: 1.19.2-3.3.11

**Additional context**
Line items from the latest.log:

> [23:23:09] [pool-3-thread-1/ERROR]: Critical injection failure: LVT in net/minecraft/world/level/block/entity/CampfireBlockEntity::m_155306_(Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/world/level/block/entity/CampfireBlockEntity;)V has incompatible changes at opcode 96 in callback pmmo.mixins.json:CampfireMixin->@Inject::projectmmo$handleCampfireCook(Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/world/level/block/entity/CampfireBlockEntity;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;ZILnet/minecraft/world/item/ItemStack;ILnet/minecraft/world/Container;Lnet/minecraft/world/item/ItemStack;)V.
 Expected: [Z, I, Lnet/minecraft/world/item/ItemStack;, I, Lnet/minecraft/world/Container;, Lnet/minecraft/world/item/ItemStack;]
    Found: [Z, I, Lnet/minecraft/world/item/ItemStack;, Lnet/minecraft/world/Container;, Lnet/minecraft/world/item/ItemStack;]
Available: [Z, I, Lnet/minecraft/world/item/ItemStack;, Lnet/minecraft/world/Container;, Lnet/minecraft/world/item/ItemStack;]

**Comment by SomewhatDamaged** [comment]
This is a known bug for 1.20.1, but thanks for letting us know it exists in 1.19.2 as well.

I'd suggest rolling back a version until this is fixed.

**Comment by Caltinor** [comment]
This has been fixed via hotfix 3.3.12.
