### ISSUE TITLE
The speed effect still occurs sometimes 

### ISSUE THREAD

**Issue by FilipKompaniets** [Caltinor/Project-MMO-2.0#445]
I know that you removed this error, but now it only appears occasionally.

**Comment by SomewhatDamaged** [comment]
That's a biome bonus (Speed 1) in particular biomes. You can use the following datapack to disable it:

[remove_biome_effects.zip](https://github.com/Caltinor/Project-MMO-2.0/files/13764996/remove_biome_effects.zip)

**Comment by FilipKompaniets** [comment]
> Це бонус біома (швидкість 1), зокрема біома. Ви можете використати такий пакет даних, щоб вимкнути його:
> 
> [remove_biome_effects.zip](https://github.com/Caltinor/Project-MMO-2.0/files/13764996/remove_biome_effects.zip)

ok

**Comment by optionboom** [comment]
> That's a biome bonus (Speed 1) in particular biomes. You can use the following datapack to disable it:
> 
> [remove_biome_effects.zip](https://github.com/Caltinor/Project-MMO-2.0/files/13764996/remove_biome_effects.zip)

For future reference, that zip doesn't work, it's for removing loot modifiers. I think you meant to link the one from #440. That one removes the effect from plains and meadow biomes.

**Comment by SomewhatDamaged** [comment]
Terribly sorry for that. 

[remove_biome_effects.zip](https://github.com/Caltinor/Project-MMO-2.0/files/14217773/remove_biome_effects.zip)

This one will obliterate all biome effects (including negatives).
