### ISSUE TITLE
EMI compatibility error (no recipes) 1.20.1-1.2.12

### ISSUE THREAD

**Issue by diemons-1** [Caltinor/Project-MMO-2.0#448]
**Describe the bug**
PMMO, together with [EMI](https://www.curseforge.com/minecraft/mc-mods/emi), limits the visibility of crafting items.
The difference is in the attached photos. 

**Expected behavior**
I need to see all the available recipes.

**To Reproduce**
I downgraded the versions from 1.2.12 to 1.2.9 but it did not work. I added the CraftTweaker mod but it didn't help either. I found on Chinese forums that this is a problem with the “craftReqEnabled = true” parameter, which needs to be changed to “false”. I didn’t find this parameter, I installed the [Forge Config Screens](https://www.curseforge.com/minecraft/mc-mods/config-menus-forge) mod as recommended, it didn’t have this parameter, I turned off all the parameters that were available for a certain world, but it also didn’t help. Creating new worlds with different versions of the mod does not work, as does downgrading the [EMI](https://www.curseforge.com/minecraft/mc-mods/emi) version of the mod.

**Screenshots**
Photos were taken without any changes, only the mod was turned on or off.
<details><summary>Without mod</summary>

 ![None use mod](https://github.com/Caltinor/Project-MMO-2.0/assets/155705980/dc5528d6-45be-4396-9696-05db341d75d2)

</details>
 
<details><summary>With mod</summary>

![Use Mod](https://github.com/Caltinor/Project-MMO-2.0/assets/155705980/eafba835-7da1-4d9d-8169-8b93edeb8d57)

</details>

**Versions:**
 - Minecraft: 1.20.1
 - Loader: Forge-47.2.0
 - PMMO: 1.20.1-1.2.12 (tested also 1.2.11/1.2.10/1.2.9)

**Additional context**
Is it possible to add the ability to disable or change parameters through the graphical interface (many users will be very grateful). I love this mod, but it is very inconvenient to use it because of this error. If there is a way to fix this, please indicate the method. It works fine with [jei](https://www.curseforge.com/minecraft/mc-mods/jei) Thank you!

**Comment by Caltinor** [comment]
This is an interaction.  Since the GUI is created by EMI, I recommend you ask them for suggestions.  If they can explain how/why pmmo would cause this behavior and pmmo is to blame, I just need to know from them what is needed to correct it.  Feel free to reopen this issue if they have anything on my side that I can change.
