### ISSUE TITLE
Please let me remove the fireworks.

### ISSUE THREAD

**Issue by JustAskinByMe** [Caltinor/Project-MMO-2.0#451]
From my scouring of the config I cannot find a way to do so. I've got rid of the on screen text, the only thing that is stopping me from using this now is the fireworks that constantly go off.

**Comment by Caltinor** [comment]
Could you please provide the following versions:
Minecraft:
ModLoader: 
PMMO:

**Comment by Bear6776** [comment]
did you figure out how to turn them off?

**Comment by TheTaterLord** [comment]
Depending on the version you're playing depends how you turn them off if you join the discord and ask in the appropriate channel we can help
