### ISSUE TITLE
Death by level up

### ISSUE THREAD

**Issue by WinterWisteria** [Caltinor/Project-MMO-2.0#461]
**Describe the bug**
The fireworks that shoot off when I level up have killed me more often than the enemies in game, not sure if this is working as intended.

**Expected behavior**
Not to be blown up by a level up.

**To Reproduce**
Level up with a block too close to your head where the fireworks explode and hit you in it's AOE.

**Screenshots**
N/A

**Versions:**
 - Minecraft: 1.12.2
 - Loader: Forge - 14.23.5.2859

**Additional context**
N/A

**Comment by TheTaterLord** [comment]
This is a known issue and I believe the fireworks can be disabled in the config but due to how restrictive 1.12 is and the fact it's no longer being supported development wise the fireworks can not be changed

**Comment by WinterWisteria** [comment]
> to disable the fireworks this should do the trick, "open minecraft/config/pmmo.cfg and change B:levelUpFirework=true to B:levelUpFirework=false"

That's super helpful thank you, also totally understandable on the no longer supported 1.12. sadly, all the good dino mods are on it TwT
