### ISSUE TITLE
Bug: Disabling treasure in the server config also disabled SKILL_UP triggers from triggering advancements.

### ISSUE THREAD

**Issue by Silvertide7** [Caltinor/Project-MMO-2.0#466]
**Describe the bug**
I turned off treasure in the server configs and my advancements with a trigger of pmmo skill up stopped triggering. 

**Expected behavior**
Skill up triggers should still trigger regardless of if treasure is on or off.

**To Reproduce**
1. Create a new world.
2. Create a new advancement with a skill up trigger, say swimming level 2
3. Turn off treasure in the pmmo-server.toml file.
4. Set yourself to level 2 swimming
5. The advancement does not trigger.
6. Do the same setup while leaving treasure enabled.
7. The advancement will now trigger.

**Versions:**
- Minecraft: 1.20,1
- Loader: 47.2.6
- PMMO: 1.20.1-1.2.17

**Comment by Caltinor** [comment]
Can you share one of your advancement JSONs that use this skill up trigger?

**Comment by Silvertide7** [comment]
Sure! You'll probably want to remove the parent part, I forget if something else needs to be in it's place
```
{
    "parent": "synapticraft:pmmo/root",
    "display": {
        "icon": {
            "item": "minecraft:turtle_helmet"
        },
        "title": {
            "text": "Crawl"
        },
        "description": {
            "text": "You can now crawl like a turtle. Hold 'c' to crawl around."
        },
        "frame": "task",
        "show_toast": true,
        "hidden": true
    },
    "criteria": {
        "acrobatics_level_1": {
            "trigger": "pmmo:skill_up",
            "conditions": {
                "player": [
                    {
                        "condition":"pmmo:skill_level", 
                        "skill":"acrobatics", 
                        "level_min": 1, 
                        "level_max": 20
                    }
                ]
            }
        }
    },
    "requirements": [
        ["acrobatics_level_1"]
    ],
    "rewards": {
        "function": "synapticraft:parcool/enable_crawl"
    }
}
```
