### ISSUE TITLE
Firework Config setting to turn it off

### ISSUE THREAD

**Issue by Itzfennecitc** [Caltinor/Project-MMO-2.0#470]
**Describe the bug**
I can't turn off the fireworks on my server as soon as i do as other tickets on github said (remove the 	perk = "pmmo:fireworks" Line) it just apears back after i also tried with doing perk = ""

**Expected behavior**
It would be nice to have some help with this or atleast some sort of answer why it doesn't work as the fireworks are anoying

**To Reproduce**
1. Go to 'World'
2. Click on 'Serverconfig'
3. Scroll down to 'pmmo-perks'

**Screenshots**
i can't make video's and screenshots aren't helpfull in this case
**Versions:**
 - Minecraft: 1.20.1
 - Loader: 47.2.20
 - PMMO: pmmo-1.20.1-1.2.17

**Additional context**
I have tried all kinds of ways and it keeps going back to the default configs i am running a home server so i can't share the ip or anything related.

**Comment by TheTaterLord** [comment]
Its not just the line that needs to be removed you remove the entire perk block also make sure the server is turned off when doing so if you need a better example if you join the discord we can help much quicker there
