### ISSUE TITLE
Entity riding XP not being granted / entity taming level requirement not being enforced.

### ISSUE THREAD

**Issue by Silvertide7** [Caltinor/Project-MMO-2.0#472]
**Describe the bug**

When I first sit on the camel to tame it sometimes I am being given XP while it walks around aimlessly. After the taming is complete I do not receive any xp for taming the camel. I have set a config for a minecraft camel for XP granted for riding and I am not getting any of that XP when riding it. Further more when I have the camel sprint I am actually getting XP for acrobatics like I do if I'm sprinting around on foot.
I am also allowed to tame the camel even though I do not meet the XP requirements to do so.

**Expected behavior**
Taming the camel should only be allowed if I have the level requirements. I should gain xp when taming the camel and riding it. I should not gain the xp set for sprinting around on foot while sprinting the camel.

**To Reproduce**
1) Create a new world.
2) Generate a datapack with default values
3) Replace the `minecraft/pmmo/entities/camel.json` with this:
```
{
  "isTagFor": [
    "minecraft:camel",
    "untamedwilds:camel"
  ],
  "xp_values": {
    "BREED": {
      "husbandry_group": 400
    },
    "RIDING": {
      "husbandry_group": 15
    },
    "TAMING": {
      "husbandry_group": 6000
    }
  },
  "override": true,
  "requirements": {
    "BREED": {
      "charisma": 5
    },
    "TAME": {
      "charisma": 5
    }
  }
}
```

5) Spawn in a camel and tame it and ride it around. You are not granted the xp for taming or riding, the requirement to tame them isn't being enforced, and while sprinting on the camels back you gain the xp set for sprinting on foot.

**Versions:**
 - Minecraft: 1.20.1
 - Loader: 47.2.6
 - PMMO: 1.20.1-1.2.17

**Comment by Caltinor** [comment]
Was this confirmed to be caused by AntiCheese or was there more to it?
