### ISSUE TITLE
Mob Modifiers in dimension.json files doesn't work

### ISSUE THREAD

**Issue by Silvertide7** [Caltinor/Project-MMO-2.0#481]
**Describe the bug**
When trying to modify an entities attributes in the dimensions json files it doesn't seem to do anything.

**Expected behavior**
Modifying an entities attributes in the dimension files changes the entities attributes in game.

**To Reproduce**
1. Create a new world using the default datapack from pmmo, which multiplies all of the entities in the end dimensions life by 10.
2. Teleport to the end, all of the enderman will have their standard life.

**Versions:**
- Minecraft: 1.20.1
- Loader: 47.2.6
- PMMO: 1.20.1-1.2.17

**Comment by Caltinor** [comment]
This was caused by the `pmmo:mobs` tag being removed from the datagen unintentionally.  You can immediately restore functionality by recreating this tag in your datapack and adding the mobs you want to have scaling.  I will be pushing an update with the restored default tag in the next release
