### ISSUE TITLE
Comptability with FirstAid mod

### ISSUE THREAD

**Issue by TymDOJO** [Caltinor/Project-MMO-2.0#482]
**Describe the bug**
How to imrpove endurance skills if I want to use FirstAid mod that separates total body HP into different bodyparts. 
When i get some damage the skills doesn't appear and could not be improved. 

**Expected behavior**
Is it possible to fix?

**To Reproduce**

**Screenshots**

**Versions:**
Minecraft 1.16.5
 - Loader: Forge
 - PMMO: version 1.16.5-3.69.0

**Comment by SomewhatDamaged** [comment]
FirstAid cancels the damage events that PMMO needs to award `endurance` skill. 

Everything else should work fine, but you will be unable to have PMMO's `endurance` skill work so long as FirstAid is installed.

**Comment by TymDOJO** [comment]
Ok thank you.
