### ISSUE TITLE
Total Level Ideas

### ISSUE THREAD

**Issue by DoofusGamer** [Caltinor/Project-MMO-2.0#487]
**Describe what this tool does, conceptually:**  (not the how, just the outputs)
Something that shows your total level from adding up all of your skills
Add the ability to put restrictions based off of the total level.
Example: Rather than the nether requiring 30 combat to enter, it would require total level 100

**Describe how current configuration methods are insufficient for the task:**
There is nothing that detects total level that I'm aware of and even asking about this in discord have been told it's not possible.

**What platform would you like to see this tool on:**
in-game (1.20.1)

**Comment by Caltinor** [comment]
https://github.com/Caltinor/Project-MMO-2.0/blob/main/wiki/core/skills.md#usetotallevels-and-displaygroupname
