### ISSUE TITLE
Attribute Perks reset

### ISSUE THREAD

**Issue by DetailedZetoprime** [Caltinor/Project-MMO-2.0#490]
Entering the End Portal from the End Resets PMMO Attribute Perks

1. Use any command to increase a skill that uses pmmo's attribute perks
2. Enter the End
3. Use the portal after when the Dragon is dead
4. Attribute Perks reset to default values

**Screenshots**

**Versions:**
 - Minecraft: 1.20.1
 - Loader: 47.2.20
 - PMMO: 1.20.1-1.3.20

**Comment by Caltinor** [comment]
This is not a bug with pmmo, but with Minecraft itself.  It tested this in vanilla to be sure.  If you create a new vanilla world then execute the following commands 
```
/attribute @s minecraft:generic.max_health modifer add 00000000-0000-0000-0000-000000000000 test 20 add
/exectute in minecraft:the_end run teleport @s 0 ~ 0
/kill @e[type="minecraft:ender_dragon"]
```

then jump into the portal, you will see the extra 10 hearts you had after the first command have vanished.
