### ISSUE TITLE
Skill Level In `pmmo:command` Strings

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#491]
**Describe the solution you'd like**
The level of the current skill be added into commands to expand their features.

`%level%`: `command = "say @s just gained level %level% in Agility!"`

**Why is this feature needed**
Would allow for completely converting fireworks over to chat commands.

**Describe alternatives you've considered**
Wallowing in a pit of despair.

**Additional context**
Perhaps have a way for the commands to be run without being bound to a player, then such messages could be server broadcasts rather than from a specific player. Would probably want to add `%player_name%` as well with this, though, so they can still be named (and shamed).

https://github.com/Caltinor/Project-MMO-2.0/assets/6394544/3a4ecd6b-a9cf-48e3-8a2d-f2333e0debaa

**Comment by Caltinor** [comment]
pmmo already lets you store player skills as a scoreboard value.  via `/pmmo store`  you can use that inconjunction with [this](https://www.minecraftforum.net/forums/minecraft-java-edition/redstone-discussion-and/2566601-how-to-display-certain-scoreboard-objectives-in) to create a function that achieves this behavior.
