### ISSUE TITLE
Skill hex colors sometimes dont work

### ISSUE THREAD

**Issue by Silvertide7** [Caltinor/Project-MMO-2.0#492]
**Describe the bug**
I am trying to set the color of my skills to make it easier for players to recognize the skill, and have it fit thematically. Using the wiki I get a hex code, like a yellow `#E7EE48` or an orange `#EAB181`, convert these to little endian UINT's using the linked website in the wiki and get the numbers `4779751` and `8499690` respectively. These numbers come out a blue hue instead. It seems to mostly effect the red values of the numbers, those have the most trouble showing up correctly.

**Expected behavior**
The color code for the numbers I put in should match in game.

**To Reproduce**
Change the colors on the pmmo-skill.toml file of a fresh world to the numbers above. In game it won't match the colors you put.

**Screenshots**
Constitution here is set to the orange color I put above.
![2024-03-09_16 14 25](https://github.com/Caltinor/Project-MMO-2.0/assets/45479211/f20e9739-817f-401f-85ff-1800e4e33960)

**Versions:**
 - Minecraft: 1.20.1
 - Loader: 47.2.6
 - PMMO: 1.20.1-1.2.20

**Additional context**

**Comment by Caltinor** [comment]
Okay, so looks like that website isn't good.  [Here's an alternative (i'll update the wiki accordingly)](https://www.programiz.com/javascript/online-compiler/)
![image](https://github.com/Caltinor/Project-MMO-2.0/assets/62700786/ba2439ac-e0d1-455e-815a-f964c5305a90)
![image](https://github.com/Caltinor/Project-MMO-2.0/assets/62700786/adc82048-b772-4235-8f5d-7fd3788e6586)

**Comment by Silvertide7** [comment]
Awesome thank you!
