### ISSUE TITLE
CTD with Iron's Spells 'n Spellbooks when trading with Priests

### ISSUE THREAD

**Issue by malice936** [Caltinor/Project-MMO-2.0#498]
**Describe the bug**
On first attempt at speaking with a Priest Villager from Iron's Spells 'n Spellbooks, the trade menu will open and the player can trade as normal, any subsequent attempt to interact in any way, including attacking causes the game to CTD. 

**Expected behavior**
The ability to open a trade dialogue with the Priest more than once.

**To Reproduce**
1. Open a trade dialogue with a Priest Villager.
2. Close the dialogue.
3. Attempt to open it again, or attempt to attack the villager.

**Screenshots**

**Versions:**
 - Minecraft: 1.20.1
 - Loader: Forge-47.2.0)
 - PMMO: 1.20.1-1.2.18

**Additional context**
Crash report attached, and report being made on the Iron's Spells 'n Spellbooks github as well.
[crash-2024-03-16_12.06.54-client.txt](https://github.com/Caltinor/Project-MMO-2.0/files/14624854/crash-2024-03-16_12.06.54-client.txt)

**Comment by Caltinor** [comment]
This looks like an issue with one of Iron Spellbook's mixins.  Have you asked them about this bug?

**Comment by malice936** [comment]
I did say that I filed a bug report on their github as well, under "additional context"

**Comment by malice936** [comment]
Also, as per usual with mod interaction problems, here is Iron's response to this, as well as a link to the report there.
![image](https://github.com/Caltinor/Project-MMO-2.0/assets/7574750/e299a43a-15f9-47ec-a3e8-062b3243f483)
 https://github.com/iron431/irons-spells-n-spellbooks/issues/353

**Comment by Silvertide7** [comment]
This happens in more ways than just trying to trade too. I get client crashes with Priests if they take damage as well.

**Comment by Caltinor** [comment]
As discussed [here](https://github.com/Caltinor/Project-MMO-2.0/issues/493), the mod developers have wrongly assumed that serializing the NBT on the client is unsafe and have built-in server-only logic into their serialization methods.  This needs to be reported to the mod author for correction.
