### ISSUE TITLE
[Datapack] Dimension JSON Not Working With `isTagFor`

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#499]
**Describe the bug**
Trying to set values for all dimensions with `isTagFor` isn't applying them.

**Expected behavior**
Setting `"isTagFor": ["minecraft:overworld", "minecraft:the_end", "minecraft:the_nether"]` in a JSON file should make it apply the file settings to all three dimensions.

**To Reproduce**
1. Use the following:
[remove_dimension_skill_bonuses.zip](https://github.com/Caltinor/Project-MMO-2.0/files/14651766/remove_dimension_skill_bonuses.zip)
2. Start game
3. There is no 3
5. See error

**Versions:**
 - Minecraft: 1.20.1
 - Loader: Forge-47.1.3
 - PMMO: 1.20.1-1.2.19

**Additional context**

https://github.com/Caltinor/Project-MMO-2.0/assets/6394544/2812122f-02c1-4366-9bd3-fcf61aa49fc3

**Comment by Caltinor** [comment]
I removed the references to `isTagFor` regarding dimensions from the wiki.  It was not implemented as a feature because dimensions aren't stored in a registry.  therefore there is no lookup which the data loader can use to identify dimensions and copy the settings to.

**Comment by SomewhatDamaged** [comment]
I couldn't see it in the commit, but did you tell the `genData` command to not create an `isTagFor` in those files?

**Comment by Caltinor** [comment]
Done
