### ISSUE TITLE
Charisma bug report

### ISSUE THREAD

**Issue by 1Sherman1** [Caltinor/Project-MMO-2.0#500]
Charisma farming
By right clicking iron gollem charisma goes insanely high

I think that's shouldn't work that way

1. Go to any village
2. Click on golem
3. See error

**Screenshots**

 - Minecraft:  1.20.1
 - Loader: Forge-47.2.20
 - PMMO: 1.20.1-1.2.20

Video prove of bug https://youtu.be/5aDd9wGV3zI

**Comment by Caltinor** [comment]
This behavior is pmmo working as intended.  Charisma XP is awarded for interaction with any entity based on the AutoValues configuration.  If you would like the iron golem to give no XP, you can either remove charisma xp entirely from the AutoValues config, or give the iron golem an explicit xp amount of zero to negate the automatic values.
