### ISSUE TITLE
not getting Alchemy XP (1.18.2)

### ISSUE THREAD

**Issue by MoonMoonShark** [Caltinor/Project-MMO-2.0#51]
**Describe the bug**
i don't seem to be getting any Alchemy XP from making potions.

**Expected behavior**
thought making potions would give Alchemy XP.

**To Reproduce**
1. Open new world with PMMO
2. Make potion in brewing stand
3. Take potions out of brewing stand
4. Nothing happens

**Versions:**
 - Minecraft: 1.18.2
 - Loader: Forge-40.1.68
 - PMMO: Project_MMO-1.18.2-3.69.11.jar

**Additional context**
You're awesome! This mod is so much fun! I know it's a lot of work and you probably only hear about the broken parts, but you're doing great work, and a lot of people appreciate you. Thank you for everything, and please let me know if there's anything I can do to help. I have a community server, and I'd be happy to let you join us for R&D if you ever need it.

**Comment by Caltinor** [comment]
The brewing stand xp was disabled at some point during the port to 1.18 from 1.16.  I see no reason why I couldn't reimplement it.  Added to LTS tracker.

**Comment by MoonMoonShark** [comment]
huzzah! that would be excellent! i just realized that some of the potions have Alchemy requirements in order to use them (like Fire Protection), but there's no way to actually level up Alchemy, which makes those potions locked and inaccessible. unless there's some other way to level up Alchemy that i don't know about.

**Comment by Caltinor** [comment]
You can give alchemy xp any way you want by using it in any of the `xp_value_xxx.json` files.  One way people often do it is by giving crafting xp for making the brewing ingredients.

**Comment by MoonMoonShark** [comment]
ahhhh... i would never have thought to try that. i'll see if i can figure that out too. it's going in the modpack for my community's server.
