### ISSUE TITLE
A Key To Disable `pmmo:break_speed` Perks.

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#510]
**Describe the solution you'd like**
Either a toggle or a while-held-down key that disables the `pmmo:break_speed` perk. Could even have it be a "while crouched" thing.

**Why is this feature needed**
Quality of life addition. Sometimes you want to DIG LIKE THE WIND. Other times you want to break just one block.

**Describe alternatives you've considered**
Breaking five blocks by accident (including the edge of a multi-block structure).

**Additional context**

https://github.com/Caltinor/Project-MMO-2.0/assets/6394544/79808ca6-2b50-45d2-ab17-02b461f2f155

**Comment by Caltinor** [comment]
I think I want to make this issue into a bigger feature.  I've thought that having keybind-enabled/activated perks is a common-sense thing for a while but it's never been super high priority.  The hesitation comes with having to build a system to relay key presses from the client to the server and the associated configurations required.  I want to give this adequate thought and consideration before implementing.  With that, i'm going to bump this to 1.21 so I can implement it properly.
