### ISSUE TITLE
Lag Spike on Skillup - pmmo-1.20.1-1.3.21

### ISSUE THREAD

**Issue by HalestormXV** [Caltinor/Project-MMO-2.0#511]
**Describe the bug**
Describe exactly what you observed

Within my mod pack the moment a player levels up a lag spike occurs. This is in Singleplayer. The Modpack is large however the issue was isolated to PMMO after some in-depth testing. It seems specifically related to the pushing of the level up to chat. Disabling the whole mod obviously resolves the issue. No mor lag spikes. However i took it a step further since i realized it was specifically occurring on level up of a skill. 

Once i disabled the client notify setting i believe it is called where it says it will push the effect to chat. I’m not at my PC atm but i believe it is in the client confit file. Upon disabling the notify setting obviously when in game and say agility levels up, the firework goes off but no chat message is displayed and there is no lag spike. 

Therefore Concluding that these “level up spikes” occur specifically when the mod is attempting to push the data to chat. Perhaps other mods within the pack cause this to happen. But as mentioned the issue resolves simply by turning that notify off and everything works smoothly from then on out. 

**Expected behavior**
It is expected the effect goes off on level up and the chat notification is shown but no lag spike. 

**To Reproduce**
go in game
level up
get spike on chat notify

**Screenshots**

**Versions:**
 - Minecraft: (eg 1.18.2)
 - Loader: (eg. Forge-40.1.20)
 - PMMO: 1.18.2-0.0.1

**Additional context**

**Comment by SomewhatDamaged** [comment]
In `minecraft/config/pmmo-client.toml` is an option `skillup_unlocks = true`, for those folks experiencing lag, they can turn it off (this is a client-side setting).

**Comment by SomewhatDamaged** [comment]
@Caltinor Perhaps the in-file setting info could be expanded a little to reflect that overly large modpacks can cause this?

**Comment by HalestormXV** [comment]
What i can do when i get home later is send a link to the Modpack. I expect it too be approved by CurseForge later today and then the contents of it can be seen to maybe identify what is/could be clashing and causing the issue. As mentioned it is a large pack. I don’t think at the level of ATM but I’d say around 270 Mods (that does include libraries and optimization mods). Only if it helpful of course.

**Comment by Caltinor** [comment]
The content of your pack isn't the issue, it's the number of mods.  The more content that needs to be scanned, the slower the skillup lag.
