### ISSUE TITLE
New configs when you die and loses xp

### ISSUE THREAD

**Issue by Shadowyjp** [Caltinor/Project-MMO-2.0#513]
In server config, theres configs for what happen with xp when you die. 

```
    #How much experience should players lose when they die?
    #zero is no loss, one is lose everything
    #Range: 0.0 ~ 1.0
    "Loss on death" = 0.5
    #should loss of experience cross levels?
    #for example, if true, a player with 1 xp above their current level would lose the
    #[Loss on death] percentage of xp and fall below their current level.  However,
    #if false, the player would lose only 1 xp as that would put them at the base xp of their current level
    "Lose Levels On Death" = true
    #This setting only matters if [Lose Level On Death] is set to false.
    #If this is true the [Loss On Death] applies only to the experience above the current level
    #for example if level 3 is 1000k xp and the player has 1020 and dies.  the player will only lose
    #the [Loss On Death] of the 20 xp above the level's base.
    "Lose Only Excess" = true
```

 **Could be added one new config**
 1 -> when the xp reachs X% of the level the next time you die, you gonna lose level
 Example: if you are 41 and has only 5% of the level already reached, if you die you lose level
 
**And one change**
   ` "Lose Only Excess" = true`  Could work even if  `"Lose Levels On Death" = true`
   
 So with that two, when you lose level (41 -> 40) you gonna  lose the same % as said in "Loos on death"
 
 Example with that all
 41 with 10% xp, you die -> 41 with 5% xp, you die -> 40 with 95% xp, you die -> 40 with 90% xp

Only with the config thats already exist, its too op losing xp, since is % of all xp
So there 2 options, or you dont lose level or you lose too much

**Comment by Caltinor** [comment]
Given how xp changed between 1.20 and 1.21, i'm not writing this twice.  I will make this a feature for the 1.21 release.

**Comment by Shadowyjp** [comment]
I was able to resolve my issue related to this. So for me, this is no longer necessary, if you want you can remove it

**Comment by Shadowyjp** [comment]
I was able to resolve my issue related to this. So for me, this is no longer necessary, if you want you can remove it
