### ISSUE TITLE
turn off fireworks

### ISSUE THREAD

**Issue by RazyelGh** [Caltinor/Project-MMO-2.0#515]
**Describe the solution you'd like**
a command that disables fireworks like /pmmo @a fireworks (true,false) and if you are in multiplayer or a button in settings

**Why is this feature needed**
In multiplayer, when we are all new, it is annoying and when you create new worlds

**Describe alternatives you've considered**
maybe for a medal I don't know with the stone symbol with a shield "combat" or tool (level10) like the effects of positions and adding the totem of importance of blocks new tools or combat and maybe they are not visible

**Additional context**
I was playing with friends on a "hardcore" server and 15 people all on generated fireworks etc. I mean, okay, but a lot of people at the same time and we talked about these achievements, like Vanilla's message in the chat, knowing that the level had gone up. to
- The player now has level 10 "stone age" in combat.
in all the fireworks they eat, sleep etc.

**Comment by SomewhatDamaged** [comment]
Fireworks are (by Minecraft itself) handled server side. The server owner can already modify/remove the fireworks settings from the `minecraft/<world name>/serverconfig/pmmo-Perks.toml` file.

An example of what needs to be removed/modified:
```TOML
[[Perks.For_Event.SKILL_UP]]
    skill = "fishing"
    perk = "pmmo:fireworks"
```

You can just remove all these perks from the file (make sure the server is shut down at the time) or you could add an extra option to them like `per_x_level = 10` to make fireworks only spawn every ten levels.
