### ISSUE TITLE
Config files seem to not affect anything

### ISSUE THREAD

**Issue by ConfusedPacifist** [Caltinor/Project-MMO-2.0#52]
I am running the mod with the First Aid mod, it stops the endurance xp from going up. in order to bypass this, i went through all 414 lines of code in the "req_wear_ config and changed "endurance" to "combat". however in game it still requires endurance and nothing about combat. 

Is there something i am missing? or is there a known work around for this mod? i have temporarily turned off wear requirements entirely but would like to enable them based on combat or find a way to get endurance working again

**Comment by SomewhatDamaged** [comment]
Could you please include:

**Versions:**
 - Minecraft: (eg 1.18.2)
 - Loader: (eg. Forge-40.1.20)
 - PMMO: (eg. 1.18.2-0.0.1)
 
 As well as the contents of the actual file you modified?

**Comment by Caltinor** [comment]
> I am running the mod with the First Aid mod, it stops the endurance xp from going up. in order to bypass this, i went through all 414 lines of code in the "req_wear_ config and changed "endurance" to "combat". however in game it still requires endurance and nothing about combat.
> 
> Is there something i am missing? or is there a known work around for this mod? i have temporarily turned off wear requirements entirely but would like to enable them based on combat or find a way to get endurance working again

The First Aid mod is a known incompatibility.  It completely rewrites how damage is dealt and handled in MC in such a way that pmmo cannot interpret automatically.   Pmmo relies on mods posting Forge events for appropriate actions in order to capture their occurrence.  First Aid either does not do that, or has a system that is more complex than events offer making them impractical.

**Comment by Caltinor** [comment]
as for the config changing to "combat".  run your `req_wear.json` through [JsonLint.com](www.jsonlint.com) to check for syntax errors.
