### ISSUE TITLE
0 stats after moving world save

### ISSUE THREAD

**Issue by SilestEngi** [Caltinor/Project-MMO-2.0#523]
**Describe the bug**
Moved world save in another launcher - stats removed entirely.

**Expected behavior**
Stats saved for all players

**To Reproduce**
1. Move world save to another launcher (for me was TLauncher -> PrismLauncher)

**Screenshots**
N/A

**Versions:**
 - Minecraft: 1.18.2
 - Loader: Forge-40.2.14 (in previous launcher was Forge-40.2.0)
 - PMMO: 1.18.2-6.2.6

**Additional context**
Where can I find xp data stats for world - maybe I can move them too and that fix the problem

**Comment by SomewhatDamaged** [comment]
TLauncher is a cracked launcher, and as such we cannot give support for it. 

It is known to have problems with PMMO skill saving. That's on their end, though.

**Comment by SilestEngi** [comment]
> TLauncher is a cracked launcher
That's why I change it.
Does stats saved in some "filename" so I can try to find it, or is it spreaded and more easily will be use some commands.
And if its commands - where can I find them

If you misunderstand something let me know - I don't speak English that well

**Comment by SomewhatDamaged** [comment]
Ah, no probs.

The stats for PMMO are saved in `pmmo.dat` in the `minecraft/saves/<save name>/data/` folder.

The problem is that TLauncher will have messed those files up and they won't work when you try to load them in normal Minecraft.

To work around this, on your fresh copy on Prism, you can use the: `/pmmo admin` command to set your skills to what they were before.

**Comment by SilestEngi** [comment]
Thanks!

**Comment by Caltinor** [comment]
@SilestEngi your data is still there but your player is authentic now and therefore different. If you want your data back, here's what you can do
1. Get your UUID for your account. (Make a singleplayer world then go into the player data folder of that world and grab the filename)
2. Open `pmmo.dat` with NBTEditor and find the cracked UUID from TLauncher with your stats.  
3. Replace this UUID with your legitimate one
4. Save the file and test 

That should restore your skills.

**Comment by Caltinor** [comment]
@SilestEngi your data is still there but your player is authentic now and therefore different. If you want your data back, here's what you can do
1. Get your UUID for your account. (Make a singleplayer world then go into the player data folder of that world and grab the filename)
2. Open `pmmo.dat` with NBTEditor and find the cracked UUID from TLauncher with your stats.  
3. Replace this UUID with your legitimate one
4. Save the file and test 

That should restore your skills.
