### ISSUE TITLE
1.18.2 - Command Perk Not Honoring It's Parent Event

### ISSUE THREAD

**Issue by MattB70** [Caltinor/Project-MMO-2.0#529]
**Describe the bug**
This is related to #525 , but I don't think it's exactly the same issue.
When assigning a command perk to Event.SKILL_UP, the command fires on respawn as per #525 .
When assigning a command perk to Event.RESPAWN, the command does not fire on respawn.

This happens on a clean or an unclean pack, dedicated server or not.

**Expected behavior**
Respawn events should fire commands on respawn, and Skill_up events should not.

**To Reproduce**
1. See example pmmo-Perks.toml screenshot below.
2. respawn
3. See example chat log.

**Screenshots**
![image](https://github.com/Caltinor/Project-MMO-2.0/assets/43189368/b646a94d-ac27-48fc-bdbd-e9ada599ab08)

![image](https://github.com/Caltinor/Project-MMO-2.0/assets/43189368/fc114a80-1638-4ad1-acd3-7aed3463909a)

**Versions:**
 - Minecraft: 1.18.2
 - Loader: Forge-40.2.21
 - PMMO: 1.18.2-6.2.7

**Additional context**
I've now read the event handling, and still have no idea why this happens. Loggy logs nothing insightful. The most I can assume is that it's related to the command perk itself, and not any events, as other perks no longer fire incorrectly on respawn as per 93d6964e70091698f108fd7eedef36d6cc64539c

**Comment by Caltinor** [comment]
RESPAWN was never actually used.  It doesn't ever actually fire and was removed in 1.19.2
