### ISSUE TITLE
annoying fireworks

### ISSUE THREAD

**Issue by FilipKompaniets3** [Caltinor/Project-MMO-2.0#530]
how to turn off fireworks?  They make it very difficult to play.  I recommend turning this feature off by default.

**Comment by SomewhatDamaged** [comment]
What version of minecraft are you playing?

**Comment by SomewhatDamaged** [comment]
> Fireworks are Perks, which can be configured in `minecraft/saves/<yoursave>/serverconfig/pmmo-perks.toml`
> 
> an example of what to add/remove for a firework looks like
> ```TOML
> [[Perks.For_Event.SKILL_UP]]
>     skill = "fishing"
>     perk = "pmmo:fireworks"
> ```
> 
> Each skill that should have fireworks should have a section like this in the config.
> 
> To remove a firework from a particular skill, delete/comment-out the firework perk section from the config.

Make sure to only edit this file while the game is closed, and avoid using Notepad++

**Comment by FilipKompaniets3** [comment]
Thank you

**Comment by FilipKompaniets3** [comment]
Can I do this not for a specific world? Because I often create new worlds.

**Comment by SomewhatDamaged** [comment]
Once you edit the `pmmo-Perks.toml` file, put it in the `minecraft/defaultconfigs/` folder. Whenever you make a new world from now on, it will use that version of the file.

**Comment by FilipKompaniets3** [comment]
Ok
