### ISSUE TITLE
PRs To Add Command Page

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#540]
Opened two draft PRs to add a command info page to the versioned wikis. 

One hitch is, I have no clue how the `/pmmo store` command works. If you let me know, I will update the documentation and mark them ready to PR.

Draft PRs:
https://github.com/Caltinor/Project-MMO-2.0/pull/538
https://github.com/Caltinor/Project-MMO-2.0/pull/539

**Comment by Caltinor** [comment]
The command takes a player and skillname arg and stores the player's level in that skill on the scoreboard.  This can be used by server ops to display skills or to use them in command blocks for various features.  it's basically a bridge between pmmo and the scoreboard.

**Comment by SomewhatDamaged** [comment]
Okay, added that details. They should be good for review.
