### ISSUE TITLE
Crashes with NeoForge .13-.16 (1.21)

### ISSUE THREAD

**Issue by aAndrew3030** [Caltinor/Project-MMO-2.0#550]
Looking at the neoforge changelog, my guess would be the change in .13

 - `21.0.13` Adds an extension method to items (adjustAttributeModifiers) to allow modifying the exposed attributes (#1116)

**Comment by Caltinor** [comment]
yeah.  I have that fixed in Dev but haven't rolled out a release yet.  NeoForge is still in that initial release phase where things are still permitted to be breaking.  once that settles out and we have a non-beta build we should be stable
