### ISSUE TITLE
Iron's spellbooks compatibility

### ISSUE THREAD

**Issue by PestArzt1936** [Caltinor/Project-MMO-2.0#552]
**Describe the solution you'd like**
Could you make compatibility for Iron's spellbooks. So, when you use magic, you would gain magic xp. Also, ability to lock some of spells until you got some level.

**Why is this feature needed**
Iron's spellbooks is very popular mod nowadays, consequently, I think, you would gain more popularity and get support from people.

**Describe alternatives you've considered**
Ah...I don't know. I think you should check events or something like that of that mod.

**Comment by SomewhatDamaged** [comment]
For version 1.20.2 there's already a compat mod for PMMO + Iron Spellbooks: https://www.curseforge.com/minecraft/mc-mods/project-mmo-irons-spellbooks-compat

**Comment by PestArzt1936** [comment]
But, there is none for version 1.19.2

**Comment by Caltinor** [comment]
This is something that should be handled in an addon.
