### ISSUE TITLE
Crash with Dynamic Trees

### ISSUE THREAD

**Issue by Groupix05** [Caltinor/Project-MMO-2.0#554]
**Describe the bug**
Crashing when cutting trees with Addons for Dynamic Trees.
PMMO return a null level to Dynamic Trees so everything crash
On Forge 1.20.1 47.1.3 and 47.3.1

**Paste your crash log here**
https://github.com/InvictusSlayer/DynamicTrees-Slayers-Beasts/issues/1

**Comment by Groupix05** [comment]
Nyfaria ( a Dynamic Trees Dev) Said "basically theyre passing null into the getDestroySpeed when they shouldn't https://github.com/Caltinor/Project-MMO-2.0/blob/cdb8961349b8a1997f10662b4f05dc0185be2d12/src/main/java/harmonised/pmmo/features/autovalues/AutoBlock.java#L42 "

**Comment by Groupix05** [comment]
Changing the "null" by "EmptyBlockGetter.INSTANCE" seems to fix the crash.
`float breakSpeed = block.defaultBlockState().getDestroySpeed(EmptyBlockGetter.INSTANCE, null); `
Instead of adding every addon in the WORLD_SENSITIVE_MOD_IDS, changing the null by something else could be more interesting. Just hovering a branch in the inventory, the game crash.
I don't know if something has changed, I would like to know. I'm learning JAVA. 

Thanks !

**Comment by Groupix05** [comment]
With the latest ver

**Comment by Groupix05** [comment]
With the latest version you Can maybe remove Dynamic Trees and DTBOP from the WORLD_SENSITIVE_MOD_IDS so we Can get XP from Dynamic Trees and Dynamic Trees BOP

**Comment by Caltinor** [comment]
you still not going to get dynamic values even if i remove them.  `EmtpyBlockGetter.INSTANCE` returns a null block entity always, which will cause them to be skipped.  all this fix does is prevent the crash.  you will always have to manually configure dynamic blocks and items like this.
