### ISSUE TITLE
Disable higher jump by default

### ISSUE THREAD

**Issue by Proxwian** [Caltinor/Project-MMO-2.0#56]
For some reason, by default mod has higher default jump, even if jumping level is at 1. Player can jump 1.5blocks by default, which is odd for me. How can i disable it?

P.S. It's very strange that no one asks that earlier...

**Comment by Caltinor** [comment]
It has been asked a lot actually.  go to perks.json and remove all the jump sections. 
![image](https://user-images.githubusercontent.com/62700786/182260940-6ad401ee-707f-40cb-b8f8-45939892bb50.png)

I will be removing them from the default settings in the near future.

**Comment by Proxwian** [comment]
Actually, in alpha for 1.8.2 higher jump disabled

**Comment by Caltinor** [comment]
disabling it should be removing it from the pmmo-perks.toml.  You would still just delete this whole section
![image](https://user-images.githubusercontent.com/62700786/182261324-cdacacfd-893e-42ce-91f1-65142d100ddf.png)

The alternative would be to specifically add a `max_boost = 0.15` to each of them.

**Comment by Proxwian** [comment]
Many thanks. It helps
