### ISSUE TITLE
Odd Leaf and Reach Distance FPS Drop

### ISSUE THREAD

**Issue by josephgilbert** [Caltinor/Project-MMO-2.0#57]
**Describe the bug**
Describe exactly what you observed

Not certain what could possibly cause this, but whenever I have PMMO installed, when I look at leaf blocks (especially when looking at the ground through leaf blocks) the FPS takes an insane hit.  Before looking at the leaves my FPS is around 130.  When looking at the ground through leaves, the FPS can drop to as low as 20.  This is only if you have your reach distance being increased via PMMO.  When you disable increasing reach distance via PMMO, the framerate acts normally.  This only happens in Survival mode and only happens when looking at some leaf blocks (most commonly dark oak leaves).  This also only happens when the player is within a certain range of the leaves (I cannot determine what the values for this range are, but it seems to be within 10 blocks or so when using PMMO's default settings).

**Expected behavior**

Quite frankly, I didn't think having enhanced reach distance would affect the performance of the game when looking at leaves. 

**To Reproduce**

Have it so that you gain some amount of reach distance for building.  
Go to a dark forest or giant taiga forest.
Jump onto the roof of the dark forest.
Go into Survival mode.
Wander around on the canopy until you notice a dramatic FPS drop.

**Screenshots**

**Versions:**
 - Minecraft: (eg 1.18.2)
 - Loader: (eg. Forge-40.1.20)
 - PMMO: 1.18.2-0.0.1

Minecraft 1.18.2
Forge 40.1.54
PMMO 1.18.2-3.69.11

**Additional context**

The problem completely disappears when in any mode other than Survival, and also goes away when having no reach distance increase.
Also, I do have Optifine and LazyDFU for forge installed.

**Comment by Caltinor** [comment]
This has been a long standing issue, however, that detail about it disappearing when reach distance is disabled is new.  Thank you for the report. This will help a ton!

**Comment by josephgilbert** [comment]
A tiny update, I was doing some testing on this version of PMMO, and I'm not certain if it actually is just leaves that causes the issue.  It seems like blocks such as glass can cause these lag spikes as well.

**Comment by josephgilbert** [comment]
When I found this out, I was playing the 1.18 release and not the alpha.  Specifically, I was playing PMMO 1.18.2-3.69.11.

**Comment by Caltinor** [comment]
Oh, I see. I was reading the versions from the template, instead of what you entered.

**Comment by Caltinor** [comment]
This has been explored endlessly and we still don't know how the rework fixed it.  I'm dropping this.
