### ISSUE TITLE
Flying in creative increases Agility Stat

### ISSUE THREAD

**Issue by Ashley123477** [Caltinor/Project-MMO-2.0#572]
**Describe the bug**
Flying in creative increases Agility Stat

**Expected behavior**
While in creative you would expect the stat not to increase

**To Reproduce**
1. Go into creative
2. Fly in a straight line
3. Watch stat increase

**Versions:**
 - Minecraft: 1.21
 - Loader: Neoforge 21.0.61
 - PMMO: 1.21-2.3.9

**Comment by Caltinor** [comment]
Creative mode does not alter your ability to gain stats. This is intended behavior.

**Comment by Ashley123477** [comment]
Should it not, surely this would hinder anybody who plays with cheats enabled but want to keep their stats "legit"
maybe a config?

**Comment by Caltinor** [comment]
Creative exemption was removed by user request.  If you have cheats enabled, then you have access to two commands that give you control to get around this.

Option 1: use `/pmmo admin @s set` to set your experience back to what it was before you went into creative if you remember what your levels were.

Option 2: use `/pmmo admin @s adminBonus agility -1` to prevent XP gain for that skill and repeat for all the skills you want to put in statis.  you can then either reload the game or call the commands again to restore the bonuses back to normal.
