### ISSUE TITLE
Vein miner

### ISSUE THREAD

**Issue by 10Fish01** [Caltinor/Project-MMO-2.0#575]
**Describe the bug**
Describe exactly what you observed
Vein miner ui would disappear for a while and not come back again from time to time
**Expected behavior**
Fix so the ui just stay their and not disappear anymore
**To Reproduce**

note this was in 1.20.1 forge

1. new world and get yourself a stone pick
2.  now use the stone pick with vein miner 
3. now just waiting and see when it will disappear

**Screenshots**
![image](https://github.com/Caltinor/Project-MMO-2.0/assets/175183874/d04d1b7c-0ca9-4e86-9840-2403181c4beb)

**Versions:**
 - Minecraft: (eg 1.18.2)
 - Loader: (eg. Forge-40.1.20)
 - PMMO: 1.18.2-0.0.1

**Additional context**

**Comment by Caltinor** [comment]
Please update your issue with the correct pmmo, forge, and Minecraft versions.
