### ISSUE TITLE
Crash during combat

### ISSUE THREAD

**Issue by laneyfamily** [Caltinor/Project-MMO-2.0#576]
**Describe the bug**
When in melee combat, occasionally I get a crash to desktop.  Does not happen during ranged combat.  Does not appear to be tied to enemy death, just the act of fighting with a weapon.

**Expected behavior**
That the combat will continue till enemy dies, and game proceeds.

**To Reproduce**
1. Load Game
2. Obtain weapon, So far my test has been with Tetra weapons.
3. Find something to kill
4. Attack
5. Crash to desktop, not every time, no discernable pattern.

**Versions:**
 - Minecraft: (1.20.1)
 - Loader: (Forge-47.3.5)
 - PMMO: 1.20.1-1.3.23

**Additional context**
Somewhat heavy mod list, the crash report also calls out Better Combat.  
*Note that the crash report below calls out MNA as its the mob in question that died, this also happens with mobs from vanilla.  I have other crash reports that do not call out MNA, but stack trace is the same.

[crash-2024-02-22_21.40.45-client.txt](https://github.com/user-attachments/files/16201997/crash-2024-02-22_21.40.45-client.txt)
[debug.log](https://github.com/user-attachments/files/16202001/debug.log)
[latest.log](https://github.com/user-attachments/files/16202002/latest.log)

**Comment by SomewhatDamaged** [comment]
That crashlog is from February and doesn't show PMMO as being installed. Any chance you could link the one for this particular crash?

**Comment by Caltinor** [comment]
Where did you download this version of pmmo?  Also, the first crash log shows that there's an issue with Majrusz's Accessories and Tetra, not with pmmo.  The latter two have a pmmo error that shouldn't be possible though.

**Comment by laneyfamily** [comment]
Ha, thats what happens when you have your view sorted by date in the explorer window, and the view in the upload is by name.... lol Here is the right log file, sorry about that

[crash-2024-07-13_07.40.55-client.txt](https://github.com/user-attachments/files/16202261/crash-2024-07-13_07.40.55-client.txt)

**Comment by laneyfamily** [comment]
Setting Java to jdk-17.0.10.7 has no impact, same conditions as prior and crashed:

[crash-2024-07-13_09.23.09-client.txt](https://github.com/user-attachments/files/16202291/crash-2024-07-13_09.23.09-client.txt)

**Comment by laneyfamily** [comment]
![image](https://github.com/user-attachments/assets/ac2b1ae9-2d12-44e3-aa7d-ba6deebbc233)

I can downgrade to Forge 47.1.3, but it will impact troubleshooting consistency as one of the primary contributors (BetterCombat) will need to be downgraded also. 

Will downgrading/disabling for testing yield viable results or will this be too inconsistent to be a valid test? 
I'll hold to get your insight before doing further testing.

**Comment by laneyfamily** [comment]
Same results running forge 47.2.0 on Java 17.0.10.7

[crash-2024-07-13_18.56.54-client.txt](https://github.com/user-attachments/files/16203842/crash-2024-07-13_18.56.54-client.txt)

**Comment by laneyfamily** [comment]
As an update, trying to see a pattern here, I believe this happens most often during a critical strike where in you jump and slash and get the particle effects, I've noticed the crash corresponds most often with that (I think.... )

I can state that it happens with vanilla weapons as well (sword specifically)

**Comment by festro** [comment]
Having this issue too, CTDs randomly during melee combat
[crash-2024-09-19_16.19.14-client.txt](https://github.com/user-attachments/files/17067781/crash-2024-09-19_16.19.14-client.txt)
[latest.log](https://github.com/user-attachments/files/17067782/latest.log)
