### ISSUE TITLE
Crash upon death and die from nothing after respawning

### ISSUE THREAD

**Issue by Dragom626** [Caltinor/Project-MMO-2.0#578]
**Describe the bug**
I spawn into the world, die by a mob and crash. After rejoining I cannot mine any blocks and shortly after my health adjusts to 0. I also cannot pick up items or XP but XP does gravitate towards me.

**Expected behavior**
I die and respawn without crashing or loop death.

**To Reproduce**
1. Install Project MMO
2. Make a new world
3. Die somehow
4. Crash if the death was caused by a mob.
5. Relaunch the game
6. Load world
7. Experience problems above.

**Screenshots**
https://pastebin.com/zzwD4Y9F
Crash log, can provide more info if needed.

**Versions:**
 - Minecraft: 1.20.1
 - Loader:  Forge-47.3.0
 - PMMO: 1.20.1 - 1.4.23

**Additional context**
Also, after rejoining the game, I will move away from hostile mobs, but they seem to gravitate toward a previous player position and attack an invisible me, and I am still consistently damaged even though I'm no longer at that position. The crash does not occur if the first death was caused by fall damage but any death still results in a death loop.

Tested with only vanilla + PMMO.

**Comment by SomewhatDamaged** [comment]
Repeatable with Forge 47.1.3

Crashlog: https://pastebin.com/XtifWuQn

1. Start game with cheats enabled
2. Give self pile of zombie spawn eggs
3. Race to create as many as you can
4. Die (in game)
5. Above crash
