### ISSUE TITLE
Unable to create map

### ISSUE THREAD

**Issue by al-wei** [Caltinor/Project-MMO-2.0#580]
**Describe the bug**
Describe exactly what you observed
Unable to create map. Loading progress 0%. Even if there's only one PMMO.
**Expected behavior**

**To Reproduce**

**Screenshots**

**Versions:**
 - Minecraft: (eg 1.12.2)
 - Loader: (eg. Forge-14.23.5.2860)
 - PMMO: Project_MMO-1.12-3.45.1523

**Additional context**

https://gist.github.com/al-wei/1fce85e8b0c2a75ecde94743614d4414

**Comment by SomewhatDamaged** [comment]
I managed to replicate this, but only when using a config setup from an older version of PMMO.

Could you try either making a new instance or deleting the contents (backing it up if necessary) of `minecraft/config/` (including `minecraft/config/pmmo/`)?

**Comment by al-wei** [comment]
> I managed to replicate this, but only when using a config setup from an older version of PMMO.
> 
> Could you try either making a new instance or deleting the contents (backing it up if necessary) of (including )?`minecraft/config/``minecraft/config/pmmo/`

Oh, I didn't even change config.
I even just load the PMMO.

**Comment by al-wei** [comment]
I successfully entered the game because I added ftbq.
I never thought about it.
![QQ_1722191216180](https://github.com/user-attachments/assets/644a525e-9443-4938-8dc5-828d2be1d999)
If ftbq is required, mod doesn't seem to list it.
![QQ_1722191284967](https://github.com/user-attachments/assets/2e409621-f765-4b42-bcb2-610c6c143c95)

**Comment by al-wei** [comment]
Your thinking should be that ftbq is not necessary, but in fact the game will still get errors without it.

**Comment by al-wei** [comment]
A new issue, this is what the error.
It doesn't seem to affect the game, but it's over 50 lines.
![QQ_1722191803857](https://github.com/user-attachments/assets/bed6a1ab-4329-42d9-bf4c-c08729fef8df)

**Comment by Caltinor** [comment]
yeah... that's 1.12 for ya.   since 1.12 is no longer supported and your issue is resolved, I am closing this issue.

**Comment by al-wei** [comment]
> yeah... that's 1.12 for ya. since 1.12 is no longer supported and your issue is resolved, I am closing this issue.

I hope you can add project dependencies to cf to solve the problem.

**Comment by al-wei** [comment]
It helps others.

**Comment by Caltinor** [comment]
You can't add file-specific dependencies.  It has to be project-based.  And since 1.12 was the only version with that dependency, it will confuse everyone using the other versions.

**Comment by al-wei** [comment]
It's listed on the main page.

**Comment by Caltinor** [comment]
what is listed on the main page?

**Comment by al-wei** [comment]
1.12.2 Dependent Items.

**Comment by al-wei** [comment]
Separate tips on the home page.

**Comment by Caltinor** [comment]
I will not be doing that.  1.12 is an extremely old version and we don't even encourage people to play it.  the majority of people playing or finding PMMO are on modern versions where I want the information to be accurate for them, not cluttered with information from a dead version.

**Comment by al-wei** [comment]
Ok, if modpack author, should also find suspicious.

**Comment by al-wei** [comment]
They should be able to figure out what caused the crash.
