### ISSUE TITLE
Can't get xp from Dynamic trees 

### ISSUE THREAD

**Issue by MrLordCat** [Caltinor/Project-MMO-2.0#587]
When cutting any parts of a tree by axe it won't give any XPs

**Expected behavior**
Cutting any part of wood on a growing tree should give XP and the amount of XP depends on the tree size you cut. It works fine if use the Falling Tree mod.

**To Reproduce**
1. Use any Axe that meets level requirements to use it.
2. Cut any wooden part from the growing tree.
3. Didn't get XP.

**Screenshots**
![image](https://github.com/user-attachments/assets/8dc27185-23a4-4e71-8c2a-513c7285d4c8)

**Versions:**
 - Minecraft: (eg 1.20.1)
 - Loader: (eg. Forge-47.3.0)
 - PMMO: 1.4.24
- Dynamic Trees 1.3.0-BETA13
- Dynamic Trees for Biomes 'o' Plenty 3.2.3
- Dynamic Trees Plus 1.2.0-BETA3

**Full list of mods:**
- AmbientSounds_FORGE_v6.0.3_mc1.20.1.jar
- animal_feeding_trough-1.1.0+1.20.1-forge.jar
- another_furniture-forge-1.20.1-3.0.1.jar
- appliedenergistics2-forge-15.2.11.jar
- architectury-9.2.14-forge.jar
- AttributeFix-Forge-1.20.1-21.0.4.jar
- balm-forge-1.20.1-7.3.7-all.jar
- BetterF3-7.0.2-Forge-1.20.1.jar
- BiomesOPlenty-1.20.1-18.0.0.598.jar
- carryon-forge-1.20.1-2.1.2.7.jar
- clienttweaks-forge-1.20-11.1.0.jar
- cloth-config-11.1.118-forge.jar
- Clumps-forge-1.20.1-12.0.0.4.jar
- cofh_core-1.20.1-11.0.2.56.jar
- collective-1.20.1-7.84.jar
- CreativeCore_FORGE_v2.11.34_mc1.20.1.jar
- creeperoverhaul-3.0.2-forge.jar
- cristellib-1.1.5-forge.jar
- DiagonalFences-v8.1.4-1.20.1-Forge.jar
- doubledoors-1.20.1-5.9.jar
- DungeonsArise-1.20.1-2.1.57-release.jar
- dynamic-fps-3.6.3+minecraft-1.20.0-forge.jar
- DynamicTrees-1.20.1-1.3.0-BETA13.jar
- DynamicTreesBOP-1.20.1-3.2.3.jar
- DynamicTreesPlus-1.20.1-1.2.0-BETA3.jar
- embeddium-0.3.30+mc1.20.1.jar
- entityculling-forge-1.6.6-mc1.20.1.jar
- ferritecore-6.0.1-forge.jar
- From-The-Fog-1.20-v1.9.2-Forge-Fabric.jar
- fusion-1.1.1-forge-mc1.20.1.jar
- geckolib-forge-1.20.1-4.4.7.jar
- gpumemleakfix-1.20.1-1.8.jar
- home-1.0.0.jar
- immersive_aircraft-1.0.1+1.20.1-forge.jar
- Incendium_1.20.x_v5.3.5.jar
- Jade-1.20.1-forge-11.9.4.jar
- jei-1.20.1-forge-15.12.3.54.jar
- Mekanism-1.20.1-10.4.8.43.jar
- MekanismAdditions-1.20.1-10.4.8.43.jar
- MekanismGenerators-1.20.1-10.4.8.43.jar
- MekanismTools-1.20.1-10.4.8.43.jar
- memoryleakfix-forge-1.17+-1.1.5.jar
- modernfix-forge-5.19.1+mc1.20.1.jar
- MouseTweaks-forge-mc1.20.1-2.25.1.jar
- Neat-1.20-35-FORGE.jar
- notenoughanimations-forge-1.7.4-mc1.20.1.jar
- oculus-mc1.20.1-1.7.0.jar
- OverflowingBars-v8.0.0-1.20.1-Forge.jar
- pmmo-1.20.1-1.4.24.jar
- PuzzlesLib-v8.1.21-1.20.1-Forge.jar
- rechiseled-1.1.6-forge-mc1.20.jar
- resourcefulconfig-forge-1.20.1-2.1.2.jar
- resourcefullib-forge-1.20.1-2.1.28.jar
- right-click-harvest-3.2.3+1.20.1-forge.jar
- sound-physics-remastered-forge-1.20.1-1.4.5.jar
- supermartijn642configlib-1.1.8-forge-mc1.20.jar
- supermartijn642corelib-1.1.17-forge-mc1.20.1.jar
- TerraBlender-forge-1.20.1-3.0.1.7.jar
- Terralith_1.20.x_v2.5.4.jar
- thermal_expansion-1.20.1-11.0.1.29.jar
- thermal_foundation-1.20.1-11.0.6.70.jar
- Towns-and-Towers-1.12-Fabric+Forge.jar
- VillagersPlus_3.1_(FORGE)_for_1.20.1.jar
- VisualWorkbench-v8.0.0-1.20.1-Forge.jar
- Xaeros_Minimap_24.2.0_Forge_1.20.jar

**Comment by SomewhatDamaged** [comment]
[dynamic_trees_for_pmmo.zip](https://github.com/user-attachments/files/16634858/dynamic_trees_for_pmmo.zip)

This datapack gives basic compat for Dynamic trees. Feel free to edit any settings within it.

**Comment by MrLordCat** [comment]
> [dynamic_trees_for_pmmo.zip](https://github.com/user-attachments/files/16634858/dynamic_trees_for_pmmo.zip)
> 
> This datapack gives basic compat for Dynamic trees. Feel free to edit any settings within it.

Thanks, it fixed the issue
