### ISSUE TITLE
Salvage block UI bugs and config issues

### ISSUE THREAD

**Issue by schindlershadow** [Caltinor/Project-MMO-2.0#590]
**Describe the bug**
1: opening the salvage block stops player inventory from being rendered. I suspect this is caused by the salvage block "helpful tips" as if you open it in a way that the player stops looking at the block when the ui is opened, the inventory is rendered correctly
2: The salvage block "helpful tips" config is ignore and is always shown despite `"Enable Salvage Tips" = false` 

**Expected behavior**
1: player inventory is rendered
2: tips are not shown

**To Reproduce**
1. right click salvage block

**Screenshots**
![2024-08-30_13 48 09](https://github.com/user-attachments/assets/590dcaa8-13c7-4c0d-8883-3524e765d4b9)
![2024-08-30_13 48 00](https://github.com/user-attachments/assets/65dbcc6a-8948-43be-98ac-53acd69aac80)

**Versions:**
 - Minecraft: 1.21.1
 - Loader: neoforge 21.1.26
 - PMMO: 2.4.12

**Comment by Caltinor** [comment]
#1 likely has nothing to do with that renderer.  The tooltip is an overlay that hooks into the HUD and just renders text.   The only interaction with the inventory is to get the item held in the players hand and still only does that if the player is crouching.  I will still look into it though just in case there is something else happening here.
#2 is definitely a bug, so i'll work on that.

**Comment by schindlershadow** [comment]
if your op'ed #1 does not happen for some reason

**Comment by TheTaterLord** [comment]
Can you reproduce this issue with just pmmo installed? This sounds like a conflict with some sort of performance boosting mod in my opinion

**Comment by Caltinor** [comment]
I agree.  there's something conflicting.  this is pmmo with a couple dozen mods from my own singleplayer playthrough.  cheats are not enabled.
![image](https://github.com/user-attachments/assets/484b31d0-3720-47f3-9c46-2e8fc2843165)
