### ISSUE TITLE
My game tick is frozen

### ISSUE THREAD

**Issue by NeoStarWonV** [Caltinor/Project-MMO-2.0#593]
When I travel in the game, my game tick freezes and all creatures cannot move, but I can move. There was no feedback from the attacking creatures. When I uninstalled pmmo and re entered the save, everything returned to normal. I don't know if it's due to mod conflicts or other reasons. Can you help me take a look? thank you
[minecraft-exported-jstack-dump-2024-09-05T17-24-53.log](https://github.com/user-attachments/files/16895488/minecraft-exported-jstack-dump-2024-09-05T17-24-53.log)
[minecraft-exported-logs-2024-09-05T17-24-50.log](https://github.com/user-attachments/files/16895490/minecraft-exported-logs-2024-09-05T17-24-50.log)

**Comment by Caltinor** [comment]
is this a Forge or NeoForge server?  if so, what version?

**Comment by NeoStarWonV** [comment]
it is forge.version is 47.3.1.I just play single,not server

**Comment by Caltinor** [comment]
Try turning off mob scaling and then booting up

**Comment by NeoStarWonV** [comment]
what the mob scaling is?

**Comment by NeoStarWonV** [comment]
is that a mod？

**Comment by NeoStarWonV** [comment]
![image](https://github.com/user-attachments/assets/f69762f0-b7a0-4558-a607-8d232336c016)
is this？

**Comment by TheTaterLord** [comment]
Caltinor refernced the feature of PMMO called Mob scaling it will be in the config for the mod

**Comment by NeoStarWonV** [comment]
ok I will try it，thank you

**Comment by NeoStarWonV** [comment]
it's working!thank you.you are my hero.
