### ISSUE TITLE
Mob scaling isnt adjustable for me

### ISSUE THREAD

**Issue by Moldx3** [Caltinor/Project-MMO-2.0#597]
**Describe the bug**
When chaning the number of mobscaling i receive the following error in the server console:
[18:18:50] [Server thread/ERROR] [ha.pm.co.re.TomlConfigHelper/]: Config failure: Using default config value due to parsing error: Not a number: SimpleCommentedConfig:{combat=1.0E-7}; Not a number: SimpleCommentedConfig:{combat=1.0E-4}; Not a number: SimpleCommentedConfig:{combat=0.001} missed input: SimpleCommentedConfig:{max_health=SimpleCommentedConfig:{combat=0.001}, attack_damage=SimpleCommentedConfig:{combat=1.0E-4}, movement_speed=SimpleCommentedConfig:{combat=1.0E-7}} missed input: SimpleCommentedConfig:{minecraft:generic=SimpleCommentedConfig:{max_health=SimpleCommentedConfig:{combat=0.001}, attack_damage=SimpleCommentedConfig:{combat=1.0E-4}, movement_speed=SimpleCommentedConfig:{combat=1.0E-7}}}

I added values above 1 and the standard values as decimals and the error comes up. Without changing the values the error message doesnt come up.

**Expected behavior**
The scaling should be changed instead it falls back to default values.

**To Reproduce**
1. Go to 'serverconfig and adjust the values of pmmo-server.toml of mob scaling'
2. Start the server join with a player and the message is shown in the server log

**Screenshots**

![2024-09-27_20h34_01](https://github.com/user-attachments/assets/6afe2974-e25f-4108-a9e2-3eedfdbd5025)
![2024-09-27_20h34_11](https://github.com/user-attachments/assets/d8ef97eb-a28b-40a8-b4e7-e97493382fb9)

**Versions:**
 - Minecraft: 1.20.1
 - Loader: (47.3.10)
 - PMMO: pmmo-1.20.1-1.4.25.jar

**Additional context**
We were playing on a 1.19.2 server before and i copied the values of the server (not override all just changed the values) on the older server it was working.

**Comment by Caltinor** [comment]
Forge converts the raw numbers into the E-notation when it parses them, but does not read them unless it's part of the default value.  You will have to use the raw number to get Forge's config system to accept your value.

**Comment by Moldx3** [comment]
Thanks for the quick reply! It's the same with raw numbers.
![grafik](https://github.com/user-attachments/assets/3dde2980-564d-4b40-926d-9da7173c3be1)
5 is a bit random, it says the same with similiar values as the default value as well.

**Comment by Caltinor** [comment]
can you share what your config looks like after you edit it?

**Comment by Moldx3** [comment]
Attached the one from 1.19.2 and the one causing problem 1.20.1
[pmmo-server1.19.2.txt](https://github.com/user-attachments/files/17168833/pmmo-server1.19.2.txt)
[pmmo-server1.20.1.txt](https://github.com/user-attachments/files/17168837/pmmo-server1.20.1.txt)

Cant upload .toml here you can download it here https://we.tl/t-nSP6iplTqK

**Comment by Caltinor** [comment]
![image](https://github.com/user-attachments/assets/5e5d29c7-a34f-463a-84fe-25bf51e500df)
this might be the issue.  make sure it's `."minecraft:generic.max_health"]` not `."minecraft:generic".max_health]`  and repeat for the other attributes.

**Comment by Moldx3** [comment]
Thanks! I changed it and it works.
I think we had a similiar issue with the scaling with 1.19.2 because of a " was wrong and detected it by our own.
The pmmo-server was created like this by pmmo, is it possible to change it for future versions?

**Comment by Caltinor** [comment]
in 1.121 all of the toml configs are part of the datapack and they use JSON instead.  there's an additional option in the `genData` command to generate the configs.
