### ISSUE TITLE
1.12.2 How to disable the Log repeating "Can't Print XP to Console" when it is set to False

### ISSUE THREAD

**Issue by LawrenceindaSky** [Caltinor/Project-MMO-2.0#603]
Hiya! I was digging around a lot because of the issue saying it is normal during boot if JEI is installed, which it is, but its been over 8 hours and it is still going on, I have the config set to false, what can I do to disable the log spam? Its just a log print of XP so I don't think it is important to have lurking around on my private pack. No lag or issues are going on either, just the log spam. Thank you so much in advance!

![image_2024-10-17_040801512](https://github.com/user-attachments/assets/085c44e4-991d-4e80-b4ea-7a3eacf3e43b)
![image](https://github.com/user-attachments/assets/ba2efa53-7b6c-46f7-a3c3-fbc90f2b737d)

**Comment by SomewhatDamaged** [comment]
Thanks for the report!

Can you please copy and fill out the following to aid with reproduction?
```Markdown
**Versions:**
 - Minecraft: (eg 1.18.2)
 - Loader: (eg. Forge-40.1.20)
 - PMMO: 1.18.2-0.0.1
 - JEI
 ```

**Comment by LawrenceindaSky** [comment]
> Thanks for the report!
> 
> Can you please copy and fill out the following to aid with reproduction?
> 
> ```
> **Versions:**
>  - Minecraft: (eg 1.18.2)
>  - Loader: (eg. Forge-40.1.20)
>  - PMMO: 1.18.2-0.0.1
>  - JEI
> ```

Version:
- 1.12.2
- Forge 1.12.2-forge-14.23.5.2859
- PMMO: 1.12-3.45.1523
- JEI jei_1.12.2-4.16.1.302

**Comment by Caltinor** [comment]
1.12 is no longer in development.  The author who maintained it has retired.
