### ISSUE TITLE
[Bug] Curio slots do not apply bonuses and requirements are ignored

### ISSUE THREAD

**Issue by schindlershadow** [Caltinor/Project-MMO-2.0#606]
**Describe the bug**
Curio slot items should apply buffs/debuffs but do not in 1.21.1. this should be a feature according to #236

**Expected behavior**
Curio slot items apply buffs/debuffs and enforce requirements

**Screenshots**
quiver should give 5% boost to archery xp
![image](https://github.com/user-attachments/assets/500340b0-6b5a-4a08-881f-d50fa58a3dad)

not getting 5% boost in archery xp
![image](https://github.com/user-attachments/assets/7d92c436-a991-4c64-85ee-86a609f72a0b)

spellbook has 90 magic requirement
![image](https://github.com/user-attachments/assets/d3102b18-edb8-456c-8053-f9bfb104af33)

not getting debuff. I have 0 magic level
![image](https://github.com/user-attachments/assets/9c700739-be82-4401-8d99-ca112ba49376)

**Versions:**
 - Minecraft: 1.21.1
 - Loader: Neoforge 21.1.61
 - PMMO: 1.21-2.4.13

**Comment by Caltinor** [comment]
There is no curios compat in 1.21. Since curios doesn't exist in 1.21.   I haven't decided yet if I'm supporting any of the ports.
