### ISSUE TITLE
Add CGM Gunslinging XP for 1.20.1+

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#607]
This is to remind me to do this.

```
				[XP_Gains.Event_XP_Specifics.Damage.DEAL_DAMAGE."cgm:bullet"]
					gunslinging = 1
```

**Comment by Caltinor** [comment]
I wouldn't even bother with 1.19.4.  In 14 months it has just over 4k downloads.  There's no demand for an update on that version.

**Comment by SomewhatDamaged** [comment]
No probs. I need to balance out how much XP this is giving. I'd set it to 15 in a quick test and got 3 levels with my first bit of burst fire with an assault rifle.

I really like how custom damage types make this so easy to do. (:

**Comment by Caltinor** [comment]
yeah.  Mojang has been gradually making MC more data driven which means my configurations need to more dynamic.  Damage Types are an example of that.  Enchantments in 1.21 follow that same concept.  it's Exciting stuff.

**Comment by SomewhatDamaged** [comment]
1.20.1: https://github.com/Caltinor/Project-MMO-2.0/pull/608
1.21.1: https://github.com/Caltinor/Project-MMO-2.0/pull/609

**Comment by SomewhatDamaged** [comment]
Turned them both into drafts. I should just make an `#pmmo:gun_damage` tag and put this (and Scorched Guns' `scguns:bullet`) into that tag.
