### ISSUE TITLE
Frostwalker gives Building experience (on rework) and Magic experience (on legacy)

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#61]
**Describe the bug**
The `Frostwalker` enchantment on boots creates ice blocks on water letting you walk over it.

In the rework (1.18.2 and 1.19) this gives Building experience when it creates the ice blocks.
In the legacy mod (1.18.2 and earlier) this gives Magic experience when it creates the ice blocks.

**Expected behavior**
It should not give any experience for creating ice blocks.

**To Reproduce**
1. Enchant a pair of boots with Frostwalker 2 (ensure you have the skill level to wear the boots)
2. Equip them
3. Walk on water
4. Gain xp

**Versions:**
 - Minecraft: 1.18.2 and 1.19
 - Loader: Forge-40.1.68 and 41.1.0
 - PMMO: 1.18.2-3.69.11 and 1.19-0.3.1

**Comment by Caltinor** [comment]
So this is intended behavior. If you don't want, or need to nerf, the XP,  give ice a block place xp_value according to your preference.

**Comment by Caltinor** [comment]
Reopened to set the XP type to magic at least for consistency.
