### ISSUE TITLE
Percentage based attribute perks

### ISSUE THREAD

**Issue by Ikxale** [Caltinor/Project-MMO-2.0#610]
**Describe the solution you'd like**
Ability to define perks to give %total and %base change to an attribute

**Why is this feature needed**
Currently attribute based perk increases are static. this means that at 0.01 per level by level 300 you deal 3 more damage per hit. due to how minecraft handles attack speed and damage this means you deal MUCH more damage proportional to how fast you can swing.
If it were instead a percentage per level increase then the baseline per-tool balance of vanilla combat will be maintained. 

**Describe alternatives you've considered**
using a wholly different mod for stat progression.  there aren't many good options i can think of. but im hardly that smart.

**Additional context**
vanilla has a sword deals 7 damage 1.6 times per second for 11.2 dps. with 3 increased damage that is brough to 10 damage 1.6 times per second for 16.0 dps. 
an axe meanwhile has 9 damge once per second. adding 3 simply increases the axe's damage per second to 12. clearly an uneven increase in power.
With a percentage based increase the DPS and DPH of both weapons would scale far more equally with a sword ending at 22.4 DPS (14 per hit) and an axe at 18dps (and 18 dph). this is significantly more balanced for late game PVP and PVE situations

**Comment by Caltinor** [comment]
Attributes perks do have the option for multiplicative bonuses.  please see the [wiki section on configuration.](https://github.com/Caltinor/Project-MMO-2.0/blob/main/wiki/core/perks.md#pmmoattribute)
