### ISSUE TITLE
`/pmmo genData withDefaults` Doesn't Populate Tags

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#611]
**Describe the bug**
When generating a datapack and using `withDefaults`, the `data/pmmo/tags/` values are not populated.

**Expected behavior**
`withDefaults` should generate the current tags in use.

**To Reproduce**
1. Generate a pack with `withDefaults`
2. Look in the tags
3. Panic because you think your code didn't work
4. Examine the file that generates tag files
5. Cry because all it does is make the files

**Versions:**
 - Minecraft: 1.20.1 and 1.21.1
 - Loader: All of them
 - PMMO: Latest

**Additional context**

https://github.com/user-attachments/assets/5c950688-0e9f-4e3f-8ca9-050cd1880e13

**Comment by Caltinor** [comment]
After reviewing this, I don't really have a good way to implement defaults in tags.  In general, tags are meant to be additive in nature.  so a blank tag generated by the command is meant to give you the option of simply adding a new value, start from scratch by setting replace to true, or use the `"remove":[]` property to subtract from previous tags.  As a whole adding the existing values is contrary to the core design of tags that Mojang has given us and i'd like to keep my designs in line with that intent.
