### ISSUE TITLE
`Party Range` Extras

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#613]
**Describe the solution you'd like**
Allow for "as long as they're on the same dimension" range as well as "no range/dimension limit".

**Why is this feature needed**
Seems easy to add and would allow for some interesting party dynamics.

**Describe alternatives you've considered**
Watching Minecraft videos on YouTube until their algorithm gives me no suggestions except Minecraft videos.

**Additional context**

https://github.com/user-attachments/assets/d6c1c2f9-cd70-4018-973b-9232777dc604

**Comment by Caltinor** [comment]
This would pair nicely with #553
