### ISSUE TITLE
Export Player stats 

### ISSUE THREAD

**Issue by Moldx3** [Caltinor/Project-MMO-2.0#616]
**Describe the solution you'd like**
I would Like to have a Feature which Exports Level stats of all Players.

**Why is this feature needed**
We would Like to Display a Kind of Scoreboard on our Website to encourage Players to Play. Also its funny. A simple .csv document or something readable would be Great.

**Describe alternatives you've considered**
Asking Players to Note and forward their Level progression.

**Additional context**
I took a Look at the Server Date and commands of pmmo but none exported readable data. In case I missed something please let me know.

**Comment by Caltinor** [comment]
If you use an NBT editor, you can crack open the pmmo.dat and export that to text. You can then clean up the data to import into the format you want for your website.

**Comment by Moldx3** [comment]
Okay. I found a way to read the .dat file of pmmo. Do you know a command to force the creation of pmmo.dat? I used „pmmo genData forPlayers <Playername>“.
Appreciate your help :)

**Comment by Caltinor** [comment]
It's created automatically by the game in your `/data/` folder.
