### ISSUE TITLE
Crazy mobs scaling

### ISSUE THREAD

**Issue by Chikaze** [Caltinor/Project-MMO-2.0#617]
My total level exceeds 500, naturally generating a multitude of mobs with Crazy attributes without the use of data packets. 
Therefore, I copied the "easy" folder to "saves/.../datapacks/". Apart from "mob_scaling", everything else seems to be effective.
As a result, mobs with 100 times the normal attributes are continuously spawned, boasting HP of 1000+ and Crazy movespeeds, posing a one-hit kill threat to players.

**Versions:**
 - Minecraft: 1.21.1
 - Loader: NeoForge 21.1.77
 - PMMO: 2.4.14
 - Single Player

**Comment by SomewhatDamaged** [comment]
You'll need to edit: `minecraft/saves/<save name>/datapacks/generated_data/data/pmmo/config/server.json`

The section:
```JSON
  "mob_scaling": {
    "use_exponential_formula": true,
    "per_level": 1.0,
    "power_base": 1.104088404342588,
    "ratios": {
      "minecraft:generic.attack_damage": {
        "combat": 1.0E-4
      },
      "minecraft:generic.movement_speed": {
        "combat": 1.0E-6
      },
      "minecraft:generic.max_health": {
        "combat": 0.001
      }
    },
    "enabled": true,
    "scaling_aoe": 150,
    "base_level": 0,
    "boss_scaling": 1.1
  },
  ```
Change `"enabled": true,` to `"enabled": false,`
That will stop new monsters spawning with crazy attributes, but the ones in the world already will retain theirs. You'll have to kill them with commands.

**Comment by SomewhatDamaged** [comment]
Then you need to kill the mobs with a command, because the code only alters new monsters—not ones already spawned.

**Comment by SomewhatDamaged** [comment]
Can you drop your `server.json` in here and I can test this?

**Comment by SomewhatDamaged** [comment]
Editing the JAR is not how you do this. You generate a datapack with the following commands (in order):

`/pmmo genData begin`
`/pmmo genData withConfigs`
`/pmmo genData withoutObjects`
`/pmmo genData create`

Then you will have a datapack with the config files to edit, as per [this comment](https://github.com/Caltinor/Project-MMO-2.0/issues/617#issuecomment-2486984956)

**Comment by Caltinor** [comment]
Do you have more than one datapack with PMMO files?

**Comment by Caltinor** [comment]
try this.  
1. create a new world with cheats enabled.  
2. in the world creation menu, go into the datapacks menu and remove the default pack, but enable the easy pack
3. start your world.
4. give yourself 1k levels in combat
5. set the time to night and see if the monsters become strong.

if they are not, do this next.
1. run the following commands in sequence
`/pmmo genData withConfigs`
`/pmmo genData withoutObjects`
`/pmmo genData create`
2. go into the server.json and enable mob scaling
3. save the file and switch back over to your game and run the following commands in sequence
`/datapack list`
`/datapack enable <the generated pack from the prompt>`
2. now set the time to night and see if you get crazy mobs.


we are essentially testing your issue in reverse but using a default instance as a test

**Comment by Caltinor** [comment]
neither me, nor the discord helpers have been able to recreate this bug.  when we change the config, things work exactly as expected.  are you using a hybrid setup like Magma/Mohist/etc?  or are you using Syntra Connector  also, are you using pmmo downloaded from CurseForge/Modrinth?

**Comment by Caltinor** [comment]
that log does not include the exception you mentioned.  please provide a log which contains the error.
