### ISSUE TITLE
 I can't level up endurance by taking damage

### ISSUE THREAD

**Issue by HenriqueNO** [Caltinor/Project-MMO-2.0#62]
When the mod is in conjunction with the other first aid mod, I can't level up the harden, I like both mods and I had to remove the first aid to play, I hope this can be fixed so I can have fun with both mods with my friends.

mine version 1.16.5
first aid 1.9.8
project mmo 3.67.6
forge 36.2.39

**Comment by TheTaterLord** [comment]
first aid and pmmo are incompatible due to the way first aid interrupts the way damage is dealt to the player

**Comment by Caltinor** [comment]
Duplicate of #52
