### ISSUE TITLE
Enchantments Imposing Debuff Despite Requirements Disabled

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#64]
**Describe the bug**
In `pmmo-server.toml` I have disabled the following:
```
	#Should requirements apply for the applicable action type
	[Requirements.Req_Enabled]
		"WEAR Req Enabled" = false
		"USE_ENCHANTMENT Req Enabled" = false
		"TOOL Req Enabled" = false
		"WEAPON Req Enabled" = false
		"USE Req Enabled" = false
		"PLACE Req Enabled" = false
		"BREAK Req Enabled" = false
		"KILL Req Enabled" = false
		"TRAVEL Req Enabled" = false
		"RIDE Req Enabled" = false
		"TAME Req Enabled" = false
		"BREED Req Enabled" = false
		"INTERACT Req Enabled" = false
		"ENTITY_INTERACT Req Enabled" = false
```
This results in weapons/armor/tools all now lacking any requirements (confirmed with tooltips), but as soon as you put Mending on a sword you get Weakness 3 applied.

**Expected behavior**
There should be no requirements, hidden or shown, for any items/enchantments.

**To Reproduce**
1. Edit `.minecraft\saves\<save name>\serverconfig\pmmo-server.toml` to reflect the above changes.
2. Load into creative game and get a diamond sword. 
3. Verify that holding sword has no negatives
4. Enchant sword to have Mending
5. Verify that holding sword now inflicts Weakness 3

**Screenshots**
Sword without mending
![Sword Without Mending](https://user-images.githubusercontent.com/6394544/183563379-b22e1a0a-6829-4e7d-9325-f7090a91f61d.jpg)
Sword with mending
![Sword With Mending](https://user-images.githubusercontent.com/6394544/183563401-303494ec-1672-48e0-914f-54197bcdbb51.jpg)

**Versions:**
 - Minecraft: 1.19
 - Loader: Forge 41.1.0
 - PMMO: 1.19-0.3.2

**Comment by Caltinor** [comment]
This was brought to my attention already in discord and was resolved in 08f3a0cc2af86fa5be8d62bda322a7e329882fbc.  This will be in the next release.
