### ISSUE TITLE
Mining Fatigue-like Effect on Random Blocks

### ISSUE THREAD

**Issue by josephgilbert** [Caltinor/Project-MMO-2.0#66]
**Describe the bug**
There are two ways I can explain this.  1. Random blocks seem to have random hardness above what they usually have.  2. The player seems to randomly get a random level of mining fatigue while mining certain blocks.  Note that no mining fatigue debuff is actually present, or at least none show up on the GUI.  In either case, random blocks take longer to mine than others of the same block.  Sometimes the block won't drop after being mined.

**Expected behavior**
Not having some blocks randomly be slower to mine (not trying to come off as snarky, I just don't know what else to put here).

**To Reproduce**
Uncertain.  It could very well be an incorrect configuration setting. 
I specifically started noticing this bug while in a taiga biome.  
Blocks like stone, logs, andesite, granite, diorite, dirt, and grass seem to exhibit this behavior frequently.
In fact, upon further testing, it seems only blocks that are more "natural" exhibit this behavior.  Blocks like cracked stone bricks, stone bricks, and wooden planks do not exhibit this issue.  

**Versions:**
-Minecraft 1.18.2
-Forge 40.1.73
-PMMO 2.0.0.10 (ALPHA 1.18.2)

**Additional context**
I understand that this is an alpha version of PMMO, so I understand fully that this type of bug is expected.  I have added my configuration settings as well, as it might just be something I messed up in them for this bug to occur.

[pmmo-AutoValues.txt](https://github.com/Caltinor/Project-MMO-2.0/files/9311511/pmmo-AutoValues.txt)
[pmmo-Globals.txt](https://github.com/Caltinor/Project-MMO-2.0/files/9311514/pmmo-Globals.txt)
[pmmo-Perks.txt](https://github.com/Caltinor/Project-MMO-2.0/files/9311516/pmmo-Perks.txt)
[pmmo-server.txt](https://github.com/Caltinor/Project-MMO-2.0/files/9311520/pmmo-server.txt)
[pmmo-Skills.txt](https://github.com/Caltinor/Project-MMO-2.0/files/9311522/pmmo-Skills.txt)

**Comment by Caltinor** [comment]
@josephgilbert another person described this issue as well, albeit with less useful detail.  Could you remove the entire `BREAK_SPEED` section from your `pmmo-perks.toml` and let me know if the issue persists?

**Comment by josephgilbert** [comment]
The issue has now been resolved.  I did exactly as you recommended and removed the BREAK_SPEED section from the perks file and restarted my game.  Everything appears to work normally now.  Thank you so much!

**Comment by josephgilbert** [comment]
Also sorry for commenting so much, one thing that I have just noticed is that when I bring up the skills tab, I notice that I have a +25.00% for mining, woodcutting, and excavation, as can be seen in the picture I've attached.  
![2022-08-11_15 49 28](https://user-images.githubusercontent.com/42681167/184234250-28d1c06a-cf37-416d-8dac-0d93a00a6ae2.png)

**Comment by Caltinor** [comment]
Are you wearing leather armor?  Oh wait that might be a biome bonus.

**Comment by josephgilbert** [comment]
Oh!  I don't know how to disable that with the new configs though.  If you can tell me how to turn off the biome bonuses, I'll test it out to see if that's what's causing the issue.

**Comment by Caltinor** [comment]
extract this in your save's datapack folder.  
[modifier-pack.zip](https://github.com/Caltinor/Project-MMO-2.0/files/9311986/modifier-pack.zip)

you should have the following path `yoursavename/datapacks/modifier-pack/data/minecraft/pmmo/dimensions/overworld.json`  edit this json file to set the bonuses you want.

**Comment by josephgilbert** [comment]
Ok, obviously I have no clue what I'm doing.  I tried deleting the section in the json file that set the bonuses, and that didn't seem to affect anything.  Literally, the bonuses were still active.  I then tried setting the bonuses to 0, and the issue is still persisting.  In fact, when I set it to 0, it displays --100% as the bonus
![2022-08-11_16 25 21](https://user-images.githubusercontent.com/42681167/184240069-44502020-43c8-42da-b09f-09edbc23e946.png)
.

**Comment by Caltinor** [comment]
Set them to 1.  It's a multiplier so 1.0= 1x gain aka normal xp

**Comment by josephgilbert** [comment]
Ok, I set the bonuses correctly, but the issue still persists  even without the bonuses present.

**Comment by josephgilbert** [comment]
I may try testing some more later, but for now I'm just going to downgrade to before the alpha.  I really can't figure out what's going on here.

**Comment by josephgilbert** [comment]
Ok.  First, I want to apologize for wasting so much of your time.  Second, I've done a bit more testing and have realized that it doesn't seem to be a bug with PMMO at all.  What it actually is is an issue with Valhesia Structures.  So again, my apologies.  I had assumed it was PMMO as I was using the alpha build and it was the only mod I could think would be the culprit.
