### ISSUE TITLE
Not gaining xp smithing for multiplayer gamers

### ISSUE THREAD

**Issue by Proxwian** [Caltinor/Project-MMO-2.0#67]
**Describe the bug**
When hosting local game for friend, my friend does not receieve any experience for smithing items in furnace. Only host gain xp from smithing

**Expected behavior**
All player can receive xp for smithing items in furnace.

**To Reproduce**
1. Start singleplayer game
2. Open world for LAN
3. Join as another player world just shared to LAN
4. Try to smith any ore in furnace
5. Not gaining xp for smithing

**Versions:**
 - Minecraft: 1.18.2
 - Loader: Forge-40.1.68
 - PMMO: 1.18.2-3.69.11

**Comment by Caltinor** [comment]
Furnaces are tied to players. Whoever placed the furnace gets the XP.

**Comment by Proxwian** [comment]
And if furnace was already placed by world generator? Nobody receives xp?

**Comment by Caltinor** [comment]
Correct.
