### ISSUE TITLE
Default mining level to break obsidian 460

### ISSUE THREAD

**Issue by Anasole** [Caltinor/Project-MMO-2.0#69]
**Describe the bug**
Excessive requirements to break some blocks

**Expected behavior**
Reasonable default level requirements for breaking blocks

**To Reproduce**
1. Attempt to break obsidian with a mining level less than 460
2. Displays message "You are not skilled enough to break obsidian"
3. Press keybind to display requirements, obsidian listed as level 460 to break.

**Screenshots**
![2022-08-19_11 18 47](https://user-images.githubusercontent.com/111286845/185651789-c6db66d6-3c7d-4a25-9da0-c953ea0840fb.png)
![2022-08-19_11 19 54](https://user-images.githubusercontent.com/111286845/185651917-9a8fdca7-2102-4ac5-935a-cd4c778dfda7.png)

**Versions:**
 - Minecraft: 1.19.2
 - Loader: Forge 43.0.11
 - PMMO: 1.19-0.3.3

**Additional context**
I tried the default 1.19 datapack and it did not change anything, seemed to have no impact at all.  I then added "requirement"[ "BREAK": { "mining":60} (copied format from another block and changed level to 60), still no impact.

**Comment by Caltinor** [comment]
Will be updated on next release.
