### ISSUE TITLE
Mending gives mining fatigue 3 incorrectly

### ISSUE THREAD

**Issue by josephgilbert** [Caltinor/Project-MMO-2.0#70]
**Describe the bug**
I receive a mining fatigue 3 debuff whenever I have a tool with mending in my hand or offhand.  The debuff is displayed in the inventory GUI correctly.  This is the only enchantment it seems to give the effect for which is why I think it's a bug.  This happens regardless of what the tier of tool is (i.e. diamond, gold, iron, etc.).  The other reason I think this is actually a bug is because I have it set so that enchantment use requirements are turned off.  The only settings related to requirements are the strict enforcement.  The issue seems to occur regardless of whether the requirements are strictly enforced or not.

**Expected behavior**
Not to have a debuff when holding tools with mending, or at the very least to not have this issue with only mending.

**To Reproduce**
Enchant a tool with mending.
Try holding the tool in your main or offhand.
Observe effects.

**Screenshots**

**Versions:**
-Minecraft 1.18.2
-Forge 40.1.73
-PMMO 2.0.0.10 (ALPHA 1.18.2)

**Additional context**
This only happens with this version of PMMO installed.  I have tested it with the mod installed and without it.  The issue only persists if the mod is installed.
[Config Files.zip](https://github.com/Caltinor/Project-MMO-2.0/files/9384780/Config.Files.zip)

**Comment by Caltinor** [comment]
This is because Mending requires Magic lvl30, however disabling the req in server-config should have disabled it.
