### ISSUE TITLE
Dynamic Tree Compatibility 1.18.2

### ISSUE THREAD

**Issue by Tsilliev** [Caltinor/Project-MMO-2.0#71]
**Describe the bug**
Cutting down dynamic trees yield 0 wood cutting exp.

**Versions:**
 - Minecraft: 1.18.2
 - Loader: (Forge-40.1.57)
 - PMMO: Project_MMO-1.18.2-3.69.11.jar
-DynamicTrees-1.18.2-0.11.0-Alpha2.jar

**Solution**
Playing around with configs for 2 hours managed to fix the problem.
Inside the file \config\pmmo\xp_value_break.json

Add the following text:
```
	"#dynamictrees:birch_branch":
	{
		"woodcutting": 8
	},
	"#dynamictrees:oak_branch":
	{
		"woodcutting": 8
	},
	"#dynamictrees:spruce_branch":
	{
		"woodcutting": 8
	},
	"#dynamictrees:jungle_branch":
	{
		"woodcutting": 8
	},
	"#dynamictrees:dark_oak_branch":
	{
		"woodcutting": 8
	},
	"#dynamictrees:acacia_branch":
	{
		"woodcutting": 8
	},
	"#dynamictrees:crimson_branch":
	{
		"woodcutting": 8
	},
	"#dynamictrees:warped_branch":
	{
		"woodcutting": 8
	},

```

**Comment by Caltinor** [comment]
You seem to have discovered how to configure the mod.   Is there anything else related to this that is actually a bug?

**Comment by Tsilliev** [comment]
After adding the other lines after birch_branch, it stopped counting woodcutting exp again.

**Comment by Caltinor** [comment]
I am not familiar with how DT does their IDs, but i'm assuming they provide these tags that you are using?  or are these tags you made?

**Comment by Tsilliev** [comment]
The tags are from dynamic tree-models-block
birch_branchjson
oak_branch.json
etc.
Strange thing is, when I started a new game, I get wood cutting exp with the numerious tags I am trying out in the xp_value_break which did not work in the previous save.

**Comment by Tsilliev** [comment]
I removed the xp_value_break file, so a new one can be made.
Restarted minecraft, made a new world and I am receiving wood cutting exp with default tags.
But when I go back to the save I still do not get woo d cutting exp, strange.

**Comment by Caltinor** [comment]
I am closing this until reliable reproduction steps can be determined.  Mod interaction bugs are very time consuming if we have to recreate the error on our own.  Please feel free to reopen this when you have those steps.
