### ISSUE TITLE
Cant level up any other things other then mining (Mineshafts and Monsters modpack)

### ISSUE THREAD

**Issue by dxrkable** [Caltinor/Project-MMO-2.0#74]
**Describe the bug**
When playing the modpack Mineshaft and Monsters the Mod doesnt let me level up any other stats other then the mining stat, leading to not being able to equip many armor pieces and weapons.

**Expected behavior**
That I should be able to level up other skills as well.

**Versions:**
 - Minecraft: (1.16.5)
 - Loader: (eg. Forge-36.2 20)
 - PMMO: 1.16.5-0.39

**Comment by Caltinor** [comment]
Mineshafts and Monsters is a modpack with a custom PMMO configuration.  You need to ask the authors of the pack.  We do not know anything about the configuration.
