### ISSUE TITLE
Support for 3 mods. Iron Furnace, mana and artifice, and tinkers construct workbenches

### ISSUE THREAD

**Issue by 78codemonkey** [Caltinor/Project-MMO-2.0#77]
**Describe the solution you'd like**
gain magic xp similar to ars nouvea and magic level requirements, and iron furnace similar setting to iron chest but correct corresponding xp gain when used (preferably less xp since it produces faster?)
for tinkers construct custom work benches bypass crafting level requirement(would like it to not bypass), correct tool setting?

**Why is this feature needed**
brings depth and experience to the game with custom modpack that is being made. And all three are download frequently.

**Describe alternatives you've considered**
For Mana and artifice adds golems, adding magic level requirements to use/craft - golemsan/blocks,items/spells, breaks immersion and using/creating adds xp to magic level. For iron furnace, time is faster but no corresponding xp gain is provided and since they are faster maybe provide less xp the higher the teir?. For Tinkers construct, mainly stop workbench from bypassing crafting level requirement and when crafting tolls/weapons, have (type level) and (combat level) requirement correspond material type on head/blade and not from bindings/hadles parts. 

**Additional context**
making mmo rpg but having hard time adding iron furnace, mana artifice, and adjustin tinkers

**Comment by Caltinor** [comment]
All of these features require someone to make an addon or the mod authors to add compat. It's not something pmmo is really in a position to add.

**Comment by TheTaterLord** [comment]
Okay so for all of the mods you want support the devs for those mods need to add pmmo support so they would need to fire of the correct events and most if not all modded crafted benches will bypass crafting requirements and there's nothing we can do about it

**Comment by Caltinor** [comment]
Well crafting reqs are removed. It's practically impossible to implement without breaking.  So we've stopped trying. But otherwise, yes you are correct.  We need events fired.

**Comment by 78codemonkey** [comment]
I have the pmmo nbt addon, but changes in it still not applying correctly.

**Comment by Caltinor** [comment]
That would be a bug.  What versions of forge, mc, and pmmo are you using?

**Comment by 78codemonkey** [comment]
mc 1.18.2, 
forge 40.1.76, 
pmmo nbt 1.18-1.2.1, 
pmmo 1.18.2-3.69.11

**Comment by Caltinor** [comment]
Okay. Drop the file you changed here and let's take a look.

**Comment by 78codemonkey** [comment]
[Reqs_json.zip](https://github.com/Caltinor/Project-MMO-2.0/files/9486161/Reqs_json.zip)
holds 3 changed nbt files from pmmo nbt

**Comment by Caltinor** [comment]
> [Reqs_json.zip](https://github.com/Caltinor/Project-MMO-2.0/files/9486161/Reqs_json.zip) holds 3 changed nbt files from pmmo nbt
> 
> have not added iron furnaces or mana and artifice items to the pmmo code yet and unsure how with mana and artifice (spell use gain mana xp when spells are custom made in game)

iron furnaces and mana and artifice will require those authors add compat or someone else make an addon.  nothing exists for 1.18 that does that currently and the NBT addon doesn't do what you need for those two mods.

As for the NBT files, they look fine.  did you restart the server after NBT config changes, or use `/nbtreload`?

**Comment by 78codemonkey** [comment]
made a post on pmmo and nbt page, https://github.com/Caltinor/PMMO-and-NBT-Compat/issues/3.
on there is how i'm trying to get tinkers tools going

**Comment by Caltinor** [comment]
Since you have cloned this issue on the NBT Compat github. I am closing this as duplicate.

**Comment by 78codemonkey** [comment]
ok
