### ISSUE TITLE
First Aid & PMMO ( Do not gain endurance xp)

### ISSUE THREAD

**Issue by TheeMrCheeky** [Caltinor/Project-MMO-2.0#83]
**Describe the bug**
Don't gain endurance xp when taking damage

**Versions:**
 - Minecraft: 1.16.5
 - Loader: 36.2.34
 - PMMO: Project_MMO-1.16.5-3.67.6.jar

**Additional context**
Just making this so it is known. Idk if it is on your end or theirs I also submitted a thing to them as well

firstaid-1.9.8.jar

**Comment by Caltinor** [comment]
First aid overrides most of Mineraft's damage behavior with its own.  As a result, PMMO has no way to detect when damage is dealt or received.  This is a known incompatibility.
