### ISSUE TITLE
Cooking in the Furnace

### ISSUE THREAD

**Issue by Leannuts** [Caltinor/Project-MMO-2.0#86]
I seem to crash as soon I start cooking something in the furnace and now I have no way of stopping it. According to the crash log it looks like it's furnacehandler is the start of the issue. 
[crash-2022-09-19_11.02.42-server.txt](https://github.com/Caltinor/Project-MMO-2.0/files/9600621/crash-2022-09-19_11.02.42-server.txt)

**Comment by Caltinor** [comment]
update to 2.0.0.10.  this has been fixed.

**Comment by Leannuts** [comment]
oh well then thank you for the quick response.
