### ISSUE TITLE
No strength xp when doing anything combat related. 

### ISSUE THREAD

**Issue by ExoDash** [Caltinor/Project-MMO-2.0#87]
**Describe the bug**
strength xp wasn't moving when doing anything combat related. 
**Expected behavior**
The xp to go: +0.12
**To Reproduce**
1. steal my account
2. open world
3. hit rabbit 
4. see strength not move

**Screenshots**

**Versions:**
 - Minecraft: 1.16.5
 - Loader:  Forge-40.1.20
 - PMMO: 1.16.5-3.67.6

**Additional context**
im using a modpack called senpais x-hardcore-x

**Comment by Caltinor** [comment]
Unfortunately i am unable to perform step 1 in your reproduction.  

On a serious note, are you by chance using a mod such as First Aid mod or anything that alters how damage is dealt/received?

**Comment by ExoDash** [comment]
sorry for the late reply. I have scaling health but that seems to be it.

**Comment by ExoDash** [comment]
I also have shield mechanics which give damage reduction instead of flat out stopping damage

**Comment by Caltinor** [comment]
It might. If it alters how damage is dealt and received and it doesn't manage the Forge events in a compat friendly way, it may be.  Try removing some of these mods and see if functionality returns.  We can look deeper once we know which mods are interacting with pmmo to get this behavior.

**Comment by ExoDash** [comment]
right, thanks.

**Comment by ExoDash** [comment]
It wasn't shield mechanics. But I'm afraid to disable scaling health as it might off balance everything.

**Comment by ExoDash** [comment]
Oh btw im using a modpack called senpais x-hardcore-x
