### ISSUE TITLE
Disable Fireworks Perk [enhancement]

### ISSUE THREAD

**Issue by SomewhatDamaged** [Caltinor/Project-MMO-2.0#88]
**Describe the solution you'd like**
An option (maybe even a keybind) to disable fireworks on a per-client basis.

**Why is this feature needed**
Some people don't like explosions, I guess. Had a request for it in #questions and figured it sounded somewhat sane.
Right now, from what I can see, the only way to disable them is to comment out/delete the perk triggers in `pmmo-Perks.toml` (which is a server-side config).

**Describe alternatives you've considered**
Keybind to toggle fireworks on/off.
`minecraft/config/pmmo-client.toml` option to disable them.
Maybe both?

**Comment by Caltinor** [comment]
Unfortunately, the fireworks are an in-world entity, which means they exist on the server.  A client-side disabling would be a massive effort.  

I will also add my comments from the #questions discord channel so that context is added here as well
> Hmm a config option for a perk.   It's super niche, so I'm inclined not to implement but if someone can come up with why perk disabling might be useful, I'll consider it.

**Comment by SomewhatDamaged** [comment]
If it has to be a serverside thing anyway, leaving it as something that you have to go into configs to disable is reasonable. Thanks for the explanation.
