### ISSUE TITLE
No way to open the Project MMO menu

### ISSUE THREAD

**Issue by EliDaHawkMan** [Caltinor/Project-MMO-2.0#90]
I cannot open the menu for the mod. 
When I go to the keybinds, there is not even an option for the menu keybind. I can't even use the mod.

 - Minecraft: 1.19.2
 - Loader: Forge 43.1.24
 - PMMO: 1.19-0.4.1

![Project MMO](https://user-images.githubusercontent.com/114627897/192909946-798cf438-92e0-4c8f-bfbc-a08073f5bec1.PNG)

**Comment by Caltinor** [comment]
If you are looking for this menu,
![image](https://user-images.githubusercontent.com/62700786/192911269-93455f68-dc15-4660-a5ca-eea651e5fc8b.png)
it has not been implemented yet, and is currently under redesign. 

"p" should still open a menu which shows details for the object you are looking at.

**Comment by EliDaHawkMan** [comment]
Is there an estimated date that it will be implemented?

**Comment by Caltinor** [comment]
There is not.  It is a very complex problem.  The old menu benefited from many skills and abilities being hard-coded, so the glossary could display them easily using those hard-coded setups.  The reworked pmmo has no hard-coding, so the glossary has to be designed in a dynamic way.  It is a work in progress.  You can follow that progress in Issue #5
