### ISSUE TITLE
Crashing on generating new world on server. 

### ISSUE THREAD

**Issue by nokosi1736** [Caltinor/Project-MMO-2.0#92]
**Describe the bug**
Describe exactly what you observed
When trying to generate a new map it gets to around 42% before crashing the server, it loads the map fine in singleplayer
**Expected behavior**
to be able to generate a map in multiplayer for a server
**To Reproduce**

**Screenshots**

**Versions:**
 - Minecraft: 1.19.2
 - Loader: forge 43.1.30
 - PMMO: 1.19-0.4.1

**Additional context**
When I removed the mod from my server I could generate a load a new map.

**Comment by Caltinor** [comment]
Please provide a crash log.

**Comment by ProsperCraft** [comment]
Not sure if this is the same crash, but I tried to make a new world and it crashed my client on the first try-
https://gist.githubusercontent.com/ProsperCraft/d748bdaf37df76f542fdd88c5ef503f8/raw/e87fe3185501841d233fef674aac2b2669199b6e/gistfile1.txt
pmmo-1.19-0.4.2
Forge .32

**Comment by ProsperCraft** [comment]
But oddly, the server didn't crash on creating a world.

**Comment by ProsperCraft** [comment]
But single player still does, tried again - https://gist.githubusercontent.com/ProsperCraft/0a925b9bb5f14b8b1d765a688011dd66/raw/3ca7b135d4863ca4dad4e34ab4a994b58feaed01/gistfile1.txt

**Comment by Caltinor** [comment]
I see the issue. It's related to loot tables being called during worldgen and pmmo not having cached the server instance at that stage.  The attached file should fix your issue.  if it does i'll push a hotfix version.
[pmmo-1.19-0.4.2a.zip](https://github.com/Caltinor/Project-MMO-2.0/files/9696924/pmmo-1.19-0.4.2a.zip)

**Comment by ProsperCraft** [comment]
I can confirm that this fixes the problem.

**Comment by Caltinor** [comment]
Thank you. I will get an update pushed today.
