### ISSUE TITLE
[1.16.5] Dedicated server crash on load due to FTB quests mod interaction.

### ISSUE THREAD

**Issue by ProsperCraft** [Caltinor/Project-MMO-2.0#95]
**Describe the bug**
The client loads fine, but when I try to load the dedicated server with FTB quests, teams, lib on it, it crashes on load.

**Versions:**
 - Minecraft:  1.16.5
 - Loader: forge-1.16.5-36.2.39
 - PMMO: Project_MMO-1.16.5-3.67.6, pmmobridge-1.16.5-1.0.7, 

**Additional context**
Crash report 
(https://gist.githubusercontent.com/ProsperCraft/55de8c58ee960ba6ecdedef7af9e6ce1/raw/5a696aab95ebf10613ef741eda73be73b250b95a/gistfile1.txt)

**Comment by ProsperCraft** [comment]
Roll FTB Quests back 51 builds to 1 year ago?

**Comment by Caltinor** [comment]
Yes.  Harmony switched to supporting the betas during 1.16 and it didn't make sense to support both versions.  This beta is what eventually became 1.17+ (the backend code at least).  So this made pmmo port-ready.
