### ISSUE TITLE
game freezes then crashes

### ISSUE THREAD

**Issue by SniffSniff125** [Caltinor/Project-MMO-2.0#99]
i was playing normally, then i got some really heavy lag spikes, then minecraft crashed

i experienced small lag spikes, i was playing as i always do in my free time, i destroyed an oak log, i did the same action before without any kind of problem.
i got other mods, none of which gave me any problem, until i installed project mmo, i dont think it was a compatibility issue, i was able to launch the game and play normally for a while.

**To Reproduce**
i'm sadly unable to give instructions on how to reproduce this issue, i did not do any "special" action, i was just gathering materials
**Screenshots**
i can't provide a screenshot, my game just freezed for a second then shut down

**Versions:**
 - Minecraft: 1.18.2
 - Loader: 40.1.80
 - PMMO: 1.18.2-3.69.11

**Additional context**
i'm sorry for any format error, i deleted a part of the text by accident, im new on github and i can't find a reset button
here is the log, i hope this helps
[crash-2022-10-07_20.59.02-server.txt](https://github.com/Caltinor/Project-MMO-2.0/files/9736928/crash-2022-10-07_20.59.02-server.txt)

**Comment by Caltinor** [comment]
Upon initial review, the source seems to be Stack Refill.  Now this may be an interaction between the mods, so I contacted the author of Stack Refill for their insight.  if this is something pmmo is doing that is creating conflict with Stack Refill, I will address it.  Right now though, I don't have enough information to diagnose the problem.

**Comment by ricksouth** [comment]
This has been fixed in version 3.2 of Stack Refill. Not exactly sure how the pair variable was null, but I've added an extra check to ignore it when it is.
